-- Versioned official-source registry for DMV site-plan intake.
-- These records are discovery gates, not dimensional rules. Except where a
-- deterministic rule pack exists, automation must resolve parcel zone,
-- overlays, and current local standards before generating regulated geometry.

INSERT INTO "jurisdiction_rule_versions" (
  "id", "jurisdictionCode", "agency", "ruleKey", "version", "projectTypes",
  "permitTypes", "applicability", "requirements", "sourceUrl", "sourceTitle",
  "lastVerifiedAt", "confidence", "humanReviewRequired"
)
VALUES
  ('dmv-source-us-dc-dc-1', 'US-DC-DC', 'DC Office of Zoning', 'OFFICIAL_SOURCE_REGISTRY', 1,
   ARRAY['NEW_SINGLE_FAMILY','RESIDENTIAL_INFILL'], ARRAY['BUILDING','SITE_PLAN'],
   '{"serviceArea":"DMV","lotCountMin":1,"lotCountMax":6}'::jsonb,
   '{"automationMode":"SOURCE_LOOKUP_REQUIRED","zoningMap":"https://maps.dcoz.dc.gov/","permitSource":"https://dob.dc.gov/service/get-building-permit","requiredInputs":["parcel","zone","overlays","effectiveRuleVersion"]}'::jsonb,
   'https://dcoz.dc.gov/page/zoning-regulations-2016', 'DC Zoning Regulations of 2016',
   TIMESTAMP '2026-07-23 00:00:00', 0.9500, true),
  ('dmv-source-us-md-montgomery-1', 'US-MD-MONTGOMERY', 'Montgomery Planning', 'OFFICIAL_SOURCE_REGISTRY', 1,
   ARRAY['NEW_SINGLE_FAMILY','RESIDENTIAL_INFILL'], ARRAY['BUILDING','SEDIMENT_CONTROL','STORMWATER'],
   '{"serviceArea":"DMV","lotCountMin":1,"lotCountMax":6}'::jsonb,
   '{"automationMode":"SOURCE_LOOKUP_REQUIRED","zoningMap":"https://mcatlas.org/","permitSource":"https://www.montgomerycountymd.gov/DPS/","requiredInputs":["parcel","zone","overlays","effectiveRuleVersion"]}'::jsonb,
   'https://montgomeryplanning.org/development/zoning/', 'Montgomery County Zoning',
   TIMESTAMP '2026-07-23 00:00:00', 0.9500, true),
  ('dmv-source-us-md-prince-georges-1', 'US-MD-PRINCE_GEORGES', 'M-NCPPC Prince George''s County Planning Department', 'OFFICIAL_SOURCE_REGISTRY', 1,
   ARRAY['NEW_SINGLE_FAMILY','RESIDENTIAL_INFILL'], ARRAY['BUILDING','SITE_ROAD','SEDIMENT_CONTROL','STORMWATER'],
   '{"serviceArea":"DMV","lotCountMin":1,"lotCountMax":6}'::jsonb,
   '{"automationMode":"DETERMINISTIC_RULES","zoningMap":"https://www.pgatlas.com/","permitSource":"https://www.princegeorgescountymd.gov/departments-offices/permitting-inspections-and-enforcement","requiredInputs":["parcel","zone","overlays","effectiveRuleVersion"]}'::jsonb,
   'https://www.pgplanning.org/countywide-planning/zoning/zoning-ordinance', 'Prince George''s County Zoning Ordinance',
   TIMESTAMP '2026-07-23 00:00:00', 0.9500, true),
  ('dmv-source-us-va-arlington-1', 'US-VA-ARLINGTON', 'Arlington County', 'OFFICIAL_SOURCE_REGISTRY', 1,
   ARRAY['NEW_SINGLE_FAMILY','RESIDENTIAL_INFILL'], ARRAY['BUILDING','LAND_DISTURBANCE'],
   '{"serviceArea":"DMV","lotCountMin":1,"lotCountMax":6}'::jsonb,
   '{"automationMode":"SOURCE_LOOKUP_REQUIRED","permitSource":"https://www.arlingtonva.us/Government/Programs/Building/Permits","requiredInputs":["parcel","zone","overlays","effectiveRuleVersion"]}'::jsonb,
   'https://www.arlingtonva.us/Government/Programs/Building/Codes-Ordinances/Zoning', 'Arlington County Zoning Ordinance',
   TIMESTAMP '2026-07-23 00:00:00', 0.9500, true),
  ('dmv-source-us-va-alexandria-1', 'US-VA-ALEXANDRIA', 'City of Alexandria', 'OFFICIAL_SOURCE_REGISTRY', 1,
   ARRAY['NEW_SINGLE_FAMILY','RESIDENTIAL_INFILL'], ARRAY['BUILDING','GRADING'],
   '{"serviceArea":"DMV","lotCountMin":1,"lotCountMax":6}'::jsonb,
   '{"automationMode":"SOURCE_LOOKUP_REQUIRED","permitSource":"https://www.alexandriava.gov/permits","requiredInputs":["parcel","zone","overlays","effectiveRuleVersion"]}'::jsonb,
   'https://www.alexandriava.gov/zoning/zoning-ordinance', 'City of Alexandria Zoning Ordinance',
   TIMESTAMP '2026-07-23 00:00:00', 0.9500, true),
  ('dmv-source-us-va-fairfax-county-1', 'US-VA-FAIRFAX_COUNTY', 'Fairfax County', 'OFFICIAL_SOURCE_REGISTRY', 1,
   ARRAY['NEW_SINGLE_FAMILY','RESIDENTIAL_INFILL'], ARRAY['BUILDING','SITE','LAND_DISTURBANCE'],
   '{"serviceArea":"DMV","lotCountMin":1,"lotCountMax":6}'::jsonb,
   '{"automationMode":"SOURCE_LOOKUP_REQUIRED","zoningMap":"https://www.fairfaxcounty.gov/gisapps/Jade/","permitSource":"https://www.fairfaxcounty.gov/plan2build/plus","requiredInputs":["parcel","zone","overlays","effectiveRuleVersion"]}'::jsonb,
   'https://www.fairfaxcounty.gov/planning-development/zoning-ordinance', 'Fairfax County Zoning Ordinance',
   TIMESTAMP '2026-07-23 00:00:00', 0.9500, true),
  ('dmv-source-us-va-loudoun-1', 'US-VA-LOUDOUN', 'Loudoun County', 'OFFICIAL_SOURCE_REGISTRY', 1,
   ARRAY['NEW_SINGLE_FAMILY','RESIDENTIAL_INFILL'], ARRAY['BUILDING','GRADING','LAND_DISTURBANCE'],
   '{"serviceArea":"DMV","lotCountMin":1,"lotCountMax":6}'::jsonb,
   '{"automationMode":"SOURCE_LOOKUP_REQUIRED","zoningMap":"https://logis.loudoun.gov/weblogis/","permitSource":"https://www.loudoun.gov/121/Building-Development","requiredInputs":["parcel","zone","overlays","effectiveRuleVersion"]}'::jsonb,
   'https://www.loudoun.gov/zoningordinance', 'Loudoun County Zoning Ordinance',
   TIMESTAMP '2026-07-23 00:00:00', 0.9500, true),
  ('dmv-source-us-va-prince-william-1', 'US-VA-PRINCE_WILLIAM', 'Prince William County', 'OFFICIAL_SOURCE_REGISTRY', 1,
   ARRAY['NEW_SINGLE_FAMILY','RESIDENTIAL_INFILL'], ARRAY['BUILDING','SITE','LAND_DISTURBANCE'],
   '{"serviceArea":"DMV","lotCountMin":1,"lotCountMax":6}'::jsonb,
   '{"automationMode":"SOURCE_LOOKUP_REQUIRED","zoningMap":"https://gisweb.pwcva.gov/webapps/CountyMapper/","permitSource":"https://www.pwcva.gov/department/development-services","requiredInputs":["parcel","zone","overlays","effectiveRuleVersion"]}'::jsonb,
   'https://www.pwcva.gov/department/planning-office/zoning-ordinance', 'Prince William County Zoning Ordinance',
   TIMESTAMP '2026-07-23 00:00:00', 0.9500, true)
ON CONFLICT ("jurisdictionCode", "ruleKey", "version") DO NOTHING;
