#!/usr/bin/env node
/**
 * Schema Merger — Composes modular schema-src/ files into one schema.prisma
 *
 * Usage: npx tsx scripts/merge-schema.ts
 *
 * Reads all .prisma files from schema-src/ in a deterministic order:
 *   1. 00-generator.prisma (generator block)
 *   2. 01-datasource.prisma (datasource block)
 *   3. Domain directories in alphabetical order, enums.prisma then models.prisma
 *
 * Outputs: prisma/schema.generated.prisma
 *
 * Developer workflow:
 *   - Edit files in schema-src/<domain>/
 *   - Run `npx tsx scripts/merge-schema.ts` to regenerate
 *   - Run `npx prisma generate --schema=prisma/schema.generated.prisma`
 */

import * as fs from 'fs'
import * as path from 'path'

const SCHEMA_SRC = path.join(__dirname, '..', 'schema-src')
const OUTPUT = path.join(__dirname, '..', 'prisma', 'schema.generated.prisma')

// Domain ordering — controls the order of blocks in the generated schema
const DOMAIN_ORDER = [
  'foundation',
  'identity',
  'engagement',  // canonical commercial-relationship layer (Engagement, enums)
  'ddts',
  'land',
  'feasibility',
  'development',
  'pm',
  'payments',
  'operations',
  'marketplace',
  'documents',
  'workflow',
  'integrations',
  'analytics',
]

function collectFiles(): string[] {
  const files: string[] = []

  // Top-level files first (generator, datasource)
  const topLevel = fs.readdirSync(SCHEMA_SRC)
    .filter(f => f.endsWith('.prisma'))
    .sort()
  for (const f of topLevel) {
    files.push(path.join(SCHEMA_SRC, f))
  }

  // Domain directories in specified order
  for (const domain of DOMAIN_ORDER) {
    const domainDir = path.join(SCHEMA_SRC, domain)
    if (!fs.existsSync(domainDir)) continue

    const domainFiles = fs.readdirSync(domainDir)
      .filter(f => f.endsWith('.prisma'))
      .sort((a, b) => {
        // enums first, then models, then others
        if (a === 'enums.prisma') return -1
        if (b === 'enums.prisma') return 1
        if (a === 'models.prisma') return -1
        if (b === 'models.prisma') return 1
        return a.localeCompare(b)
      })

    for (const f of domainFiles) {
      files.push(path.join(domainDir, f))
    }
  }

  return files
}

function merge() {
  const files = collectFiles()
  console.log(`Merging ${files.length} schema files...`)

  const parts: string[] = [
    `// =============================================================================`,
    `// KEALEE PLATFORM — GENERATED PRISMA SCHEMA`,
    `// =============================================================================`,
    `// DO NOT EDIT THIS FILE DIRECTLY.`,
    `// Edit files in schema-src/ and run: npx tsx scripts/merge-schema.ts`,
    `// Generated: ${new Date().toISOString()}`,
    `// =============================================================================`,
    ``,
  ]

  for (const filePath of files) {
    const relative = path.relative(SCHEMA_SRC, filePath)
    const content = fs.readFileSync(filePath, 'utf-8').trim()
    parts.push(`// --- ${relative} ---`)
    parts.push(content)
    parts.push('')
  }

  const merged = parts.join('\n')
  fs.writeFileSync(OUTPUT, merged + '\n')

  // Validate: count models and enums
  const modelCount = (merged.match(/^model\s+\w+\s*\{/gm) || []).length
  const enumCount = (merged.match(/^enum\s+\w+\s*\{/gm) || []).length

  console.log(`\nOutput: ${OUTPUT}`)
  console.log(`Contains: ${modelCount} models, ${enumCount} enums`)
  console.log(`Size: ${(merged.length / 1024).toFixed(1)} KB`)
}

merge()
