import { RuleSeed } from "../types";

export const ruleSeeds: RuleSeed[] = [
  // ── Approval rules ──────────────────────────────────────────────────────────
  {
    code: "rule_payment_requires_approval",
    version: "1.0.0",
    status: "active",
    priority: 100,
    type: "approval_rule",
    description: "Any Stripe checkout creation requires explicit user or operator approval.",
    when: { toolName: "create_checkout" },
    effect: { requireApproval: true, approvalRole: "homeowner_or_operator", message: "Review your selected package before payment." },
  },
  {
    code: "rule_contractor_assign_requires_approval",
    version: "1.0.0",
    status: "active",
    priority: 100,
    type: "approval_rule",
    description: "Contractor assignment requires operator approval. Contractor must be verified.",
    when: { toolName: "assign_contractor" },
    effect: { requireApproval: true, approvalRole: "internal_operator", message: "Contractor assignment must be reviewed before confirming.", requireContractorVerified: true },
  },
  {
    code: "rule_send_external_message_requires_approval",
    version: "1.0.0",
    status: "active",
    priority: 90,
    type: "approval_rule",
    description: "Sending email or SMS to external parties requires operator approval.",
    when: { toolName: ["send_email", "send_sms"] },
    effect: { requireApproval: true, approvalRole: "internal_operator" },
  },
  {
    code: "rule_permit_submission_requires_approved_scope",
    version: "1.0.0",
    status: "active",
    priority: 95,
    type: "approval_rule",
    description: "Permit submission prep requires an approved scope and uploaded drawings.",
    when: { toolName: "submit_permit", missingAny: ["approvedScope", "uploadedDrawings"] },
    effect: { blockExecution: true, riskFlag: "permit_submission_missing_docs", message: "Scope and drawings must be approved before permit submission." },
  },
  {
    code: "rule_lender_output_requires_operator",
    version: "1.0.0",
    status: "active",
    priority: 95,
    type: "approval_rule",
    description: "Any tool that generates lender-facing reports or triggers disbursement requires finance_reviewer approval.",
    when: { toolName: ["generate_lender_report", "release_draw"], outputType: "lender_facing" },
    effect: { requireApproval: true, approvalRole: "finance_reviewer" },
  },
  {
    code: "rule_irreversible_milestone_requires_approval",
    version: "1.0.0",
    status: "active",
    priority: 100,
    type: "approval_rule",
    description: "Creating an irreversible milestone (PAID, COMPLETED) requires operator approval.",
    when: { toolName: "update_milestone_status", targetStatus: ["PAID", "COMPLETED"] },
    effect: { requireApproval: true, approvalRole: "internal_operator_or_finance_reviewer" },
  },

  // ── Risk / guard rules ──────────────────────────────────────────────────────
  {
    code: "rule_missing_address_blocks_zoning",
    version: "1.0.0",
    status: "active",
    priority: 80,
    type: "guard_rule",
    description: "Zoning check cannot run without an address or parcel identifier.",
    when: { toolName: "check_zoning", missingFields: ["address"] },
    effect: { blockExecution: true, riskFlag: "missing_address", message: "A property address is required to run a zoning check." },
  },
  {
    code: "rule_missing_project_type_blocks_estimate",
    version: "1.0.0",
    status: "active",
    priority: 70,
    type: "guard_rule",
    description: "Cost estimate confidence is very low without a project type.",
    when: { toolName: "create_estimate", missingFields: ["projectType"] },
    effect: { riskFlag: "low_estimate_confidence", warnOnly: true, message: "Project type is missing — estimate will be very rough." },
  },
  {
    code: "rule_commercial_high_complexity_routes_to_professional",
    version: "1.0.0",
    status: "active",
    priority: 85,
    type: "routing_rule",
    description: "Commercial or high-complexity scopes (>10,000 sqft or developer deal >$5M) must be routed to professional review, not auto-run.",
    when: { projectType: ["commercial_ti", "developer_deal"], threshold: { squareFootage: 10000, budget: 5000000 } },
    effect: { escalateTo: "internal_operator", riskFlag: "high_complexity_project", message: "This project requires professional review before proceeding." },
  },
  {
    code: "rule_unverified_contractor_blocked",
    version: "1.0.0",
    status: "active",
    priority: 100,
    type: "guard_rule",
    description: "A contractor who has not completed verification cannot be assigned to a project.",
    when: { toolName: "assign_contractor", contractorVerified: false },
    effect: { blockExecution: true, riskFlag: "unverified_contractor", message: "Contractor must complete verification before being assigned." },
  },
  {
    code: "rule_historic_address_triggers_bar_review_flag",
    version: "1.0.0",
    status: "active",
    priority: 60,
    type: "risk_rule",
    description: "Addresses in known historic districts (Alexandria Old Town, DC historic overlay) trigger a historic review risk flag.",
    when: { jurisdictionCode: ["dc", "alexandria_va"], zoningOverlay: "historic" },
    effect: { riskFlag: "historic_review_required", warnOnly: true, message: "This address may require Board of Architectural Review (BAR) approval." },
  },
  {
    code: "rule_budget_under_threshold_warns",
    version: "1.0.0",
    status: "active",
    priority: 50,
    type: "risk_rule",
    description: "If stated budget is more than 40% below the estimated cost range midpoint, flag it.",
    when: { toolName: "create_estimate", budgetBelowEstimateBy: 0.4 },
    effect: { riskFlag: "budget_below_estimate", warnOnly: true, message: "Stated budget may be insufficient for the estimated scope." },
  },
];
