'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Play, ArrowRight } from 'lucide-react'
import { VideoModal } from '@/components/ui/VideoModal'

const SERVICES = [
  {
    id: 'concept',
    title: 'AI Concept Engine',
    badge: 'AI-powered',
    badgeColor: '#C8521A',
    price: 'From $395',
    desc: 'Describe your project in plain language. Our AI generates design concepts, cost bands, and a permit-ready package — delivered in days, not months.',
    bullets: ['Concept visuals generated by AI', 'Cost band + permit risk score', 'Jurisdiction-specific filing checklist'],
    watchLabel: 'Watch Demo',
    startLabel: 'Start a Project',
    startHref: '/concept',
    img: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=700&q=80',
  },
  {
    id: 'permits',
    title: 'Permit Services',
    badge: 'AI-reviewed',
    badgeColor: '#2ABFBF',
    price: 'From $149',
    desc: 'Our AI reviews your plans against jurisdiction requirements before submission, dramatically reducing back-and-forth with reviewers.',
    bullets: ['AI pre-submission review', 'First-cycle approval focus', 'DC / MD / VA jurisdictions'],
    watchLabel: 'See How It Works',
    startLabel: 'Get Permits',
    startHref: '/permits',
    img: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=700&q=80',
  },
  {
    id: 'pm',
    title: 'Construction Management',
    badge: 'Full OS',
    badgeColor: '#3A7D52',
    price: 'Per project',
    desc: 'Milestone payments held in escrow and released when work is verified. Digital twin tracks every phase, inspection, and lien waiver.',
    bullets: ['Escrow-backed milestone payments', 'AI scheduling + progress tracking', 'Digital twin for every project'],
    watchLabel: 'Watch Demo',
    startLabel: 'Learn More',
    startHref: '/developers',
    img: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=700&q=80',
  },
]

export function CoreServicesSection() {
  const [videoOpen, setVideoOpen] = useState<string | null>(null)

  return (
    <section className="py-20 bg-white">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        <div className="mb-12 text-center">
          <span className="section-label">Core Services</span>
          <h2 className="mt-3 text-3xl font-bold font-display sm:text-4xl" style={{ color: '#1A2B4A' }}>
            Three services. One connected platform.
          </h2>
          <p className="mt-4 max-w-xl mx-auto text-gray-500">
            Each service is AI-assisted and connects to the next — so your project never gets stuck in a handoff.
          </p>
        </div>

        <div className="grid gap-8 md:grid-cols-3">
          {SERVICES.map(s => (
            <div
              key={s.id}
              className="flex flex-col overflow-hidden rounded-2xl border border-gray-100 bg-white transition-shadow hover:shadow-lg"
            >
              {/* Image */}
              <div className="relative h-44 overflow-hidden">
                <img src={s.img} alt={s.title} className="h-full w-full object-cover" />
                <div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent" />
                <div className="absolute bottom-3 left-3 flex items-center gap-2">
                  <span
                    className="rounded-full px-2.5 py-1 text-xs font-semibold text-white"
                    style={{ background: s.badgeColor }}
                  >
                    {s.badge}
                  </span>
                  <span className="text-xs font-semibold text-white">{s.price}</span>
                </div>
              </div>

              {/* Content */}
              <div className="flex flex-1 flex-col p-6">
                <h3 className="text-lg font-bold font-display" style={{ color: '#1A2B4A' }}>{s.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-gray-500">{s.desc}</p>

                <ul className="mt-4 space-y-1.5">
                  {s.bullets.map(b => (
                    <li key={b} className="flex items-center gap-2 text-xs text-gray-600">
                      <span style={{ color: s.badgeColor }}>✓</span> {b}
                    </li>
                  ))}
                </ul>

                <div className="mt-6 flex gap-2">
                  <button
                    onClick={() => setVideoOpen(s.id)}
                    className="flex items-center gap-1.5 rounded-lg border px-3 py-2 text-xs font-semibold transition-colors hover:bg-gray-50"
                    style={{ borderColor: s.badgeColor, color: s.badgeColor }}
                  >
                    <Play className="h-3 w-3" /> {s.watchLabel}
                  </button>
                  <Link
                    href={s.startHref}
                    className="flex flex-1 items-center justify-center gap-1.5 rounded-lg px-3 py-2 text-xs font-semibold text-white transition-opacity hover:opacity-90"
                    style={{ background: s.badgeColor }}
                  >
                    {s.startLabel} <ArrowRight className="h-3 w-3" />
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {SERVICES.map(s => (
        <VideoModal
          key={s.id}
          isOpen={videoOpen === s.id}
          onClose={() => setVideoOpen(null)}
          title={`${s.title} — Demo`}
        />
      ))}
    </section>
  )
}
