import { IntentSeed } from "../types";

export const intentSeeds: IntentSeed[] = [
  {
    code: "design_concept",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    label: "AI Design Concept",
    description: "User wants early concepting, layout direction, or visual design before full plans. Maps to the AI Concept Engine.",
    entrySignals: ["concept", "design idea", "layout", "floor plan", "what can fit", "render", "what would it look like", "garden design", "interior design"],
    defaultPrimaryAgent: "design",
    defaultWorkflowTemplate: "wf_homeowner_concept_v1",
    requiredFields: ["projectType", "scopeSummary"],
    optionalFields: ["address", "budgetRange", "photos", "stylePreferences"],
    upsellTargets: ["feasibility_light", "permit_path_review", "architect_handoff"],
  },
  {
    code: "renovation",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    label: "Home Renovation",
    description: "User wants to renovate an existing home — kitchen, bath, addition, full renovation.",
    entrySignals: ["renovate", "remodel", "kitchen", "bathroom", "addition", "expand", "gut", "update"],
    defaultPrimaryAgent: "design",
    defaultWorkflowTemplate: "wf_homeowner_concept_v1",
    requiredFields: ["projectType", "address"],
    optionalFields: ["scopeSummary", "budgetRange", "photos", "timeline"],
    upsellTargets: ["design_concept", "permit_path_review", "full_permit_coordination", "contractor_match"],
  },
  {
    code: "new_build",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    label: "New Construction",
    description: "User wants to build a new structure on a lot they own or are acquiring.",
    entrySignals: ["build", "new home", "new house", "ground up", "new construction", "build on lot", "vacant lot"],
    defaultPrimaryAgent: "estimate",
    defaultWorkflowTemplate: "wf_new_build_v1",
    requiredFields: ["address", "projectType"],
    optionalFields: ["scopeSummary", "budgetRange", "lotSize", "squareFootage"],
    upsellTargets: ["feasibility_light", "permit_path_review", "architect_handoff", "contractor_match"],
  },
  {
    code: "adu",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    label: "ADU / In-Law Suite",
    description: "User wants to add an accessory dwelling unit — basement, detached, or garage conversion.",
    entrySignals: ["adu", "in-law suite", "basement unit", "carriage house", "garage apartment", "backyard unit", "secondary unit", "accessory dwelling"],
    defaultPrimaryAgent: "design",
    defaultWorkflowTemplate: "wf_homeowner_concept_v1",
    requiredFields: ["address", "projectType"],
    optionalFields: ["scopeSummary", "budgetRange", "photos"],
    upsellTargets: ["feasibility_light", "permit_path_review", "full_permit_coordination"],
  },
  {
    code: "permit_only",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    label: "Permit Help Only",
    description: "User already has plans or scope and needs permit path, prep, or submission support.",
    entrySignals: ["permit", "approve plans", "pull permit", "submit permit", "permit status", "permit help", "building permit"],
    defaultPrimaryAgent: "permit",
    defaultWorkflowTemplate: "wf_permit_only_v1",
    requiredFields: ["address", "permitNeed"],
    optionalFields: ["uploadedPlans", "jurisdictionHint", "projectType"],
    upsellTargets: ["permit_prep", "full_permit_coordination"],
  },
  {
    code: "feasibility_light",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    label: "Quick Feasibility Check",
    description: "User wants to know if their project is viable before committing to design or permits.",
    entrySignals: ["feasibility", "can I build", "is it possible", "how much would it cost", "rough cost", "is it worth it", "viability"],
    defaultPrimaryAgent: "feasibility",
    defaultWorkflowTemplate: "wf_feasibility_light_v1",
    requiredFields: ["projectType", "address"],
    optionalFields: ["scopeSummary", "budgetRange"],
    upsellTargets: ["design_concept", "developer_feasibility", "estimate_only"],
  },
  {
    code: "developer_feasibility",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    label: "Developer Feasibility",
    description: "Developer or investor wants pro forma, IRR, capital stack modeling, or entitlement support for a deal.",
    entrySignals: ["developer", "pro forma", "investment", "irr", "cap rate", "multifamily", "land deal", "entitlement", "capital stack", "waterfall"],
    defaultPrimaryAgent: "developer",
    defaultWorkflowTemplate: "wf_developer_feasibility_v1",
    requiredFields: ["address", "projectType"],
    optionalFields: ["unitCount", "budgetRange", "scopeSummary", "targetIRR"],
    upsellTargets: ["capital_stack_modeling", "entitlement_support"],
  },
  {
    code: "estimate_only",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    label: "Cost Estimate Only",
    description: "User needs a construction cost estimate without concept or permit work.",
    entrySignals: ["estimate", "how much", "cost breakdown", "price out", "budget for", "cost to build", "square foot cost"],
    defaultPrimaryAgent: "estimate",
    defaultWorkflowTemplate: "wf_estimate_only_v1",
    requiredFields: ["projectType"],
    optionalFields: ["address", "scopeSummary", "squareFootage", "budgetRange"],
    upsellTargets: ["feasibility_light", "design_concept", "contractor_match"],
  },
  {
    code: "contractor_match",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    label: "Find a Contractor",
    description: "User wants to find, compare, or hire a verified contractor for their project.",
    entrySignals: ["contractor", "find a gc", "general contractor", "who can build", "get bids", "need a contractor", "hire someone"],
    defaultPrimaryAgent: "marketplace",
    defaultWorkflowTemplate: "wf_contractor_match_v1",
    requiredFields: ["projectType", "address"],
    optionalFields: ["scopeSummary", "budgetRange", "timeline"],
    upsellTargets: ["full_permit_coordination", "pm_package"],
  },
  {
    code: "construction_execution",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    label: "Active Construction Management",
    description: "Project is under construction — user needs PM oversight, milestone tracking, draws, and field ops.",
    entrySignals: ["construction started", "under construction", "need pm", "milestone", "draw request", "manage build", "progress tracking"],
    defaultPrimaryAgent: "construction",
    defaultWorkflowTemplate: "wf_construction_execution_v1",
    requiredFields: ["projectId"],
    optionalFields: ["milestoneId", "progressNote"],
    upsellTargets: ["pm_package", "payment_disbursement"],
  },
  {
    code: "payment_disbursement",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    label: "Milestone Payment / Draw",
    description: "Contractor or owner needs to submit, approve, or release a milestone payment.",
    entrySignals: ["payment", "draw", "release funds", "approve milestone", "pay contractor", "draw request", "lender disbursement"],
    defaultPrimaryAgent: "payments",
    defaultWorkflowTemplate: "wf_milestone_payment_v1",
    requiredFields: ["projectId", "milestoneId"],
    optionalFields: ["amount", "lenderContact"],
    upsellTargets: ["finance_trust_onboarding"],
  },
];
