import { ReviewQueue } from '@/components/professional-review/ReviewQueue'
import { DesignConceptQueue } from '@/components/professional-review/DesignConceptQueue'

export const dynamic = 'force-dynamic'

/**
 * OS Architecture — the licensed architect's desk.
 *
 * Two queues on one page: the design concepts (the concept-package products,
 * generated by DesignBot) awaiting an architect's review, and the site plans
 * whose dwelling — footprint, finished floor, entries — is the architect's
 * subject on the shared site-plan workflow.
 */
export default async function ArchitectReviewQueuePage() {
  return (
    <ReviewQueue discipline="architect">
      <DesignConceptQueue />
    </ReviewQueue>
  )
}
