ALTER TYPE "FeasibilityTypology" ADD VALUE IF NOT EXISTS 'ADU';
ALTER TYPE "FeasibilityTypology" ADD VALUE IF NOT EXISTS 'ADDITION';
ALTER TYPE "FeasibilityTypology" ADD VALUE IF NOT EXISTS 'POOL';
ALTER TYPE "FeasibilityTypology" ADD VALUE IF NOT EXISTS 'NEW_HOME';
