/**
 * Prince George's County — dimensional standards from the adopted Zoning Ordinance.
 *
 * SOURCE   online.encodeplus.com — the county's publication of "Zoning Ordinance,
 *          Subdivision Regulations & Landscape Manual (Effective 4/1/2022)".
 * METHOD   Machine-extracted from each zone's "Intensity and Dimensional
 *          Standards" table via a colspan/rowspan-aware grid parser. The
 *          Transit-Oriented tables nest Core/Edge headers over use types and
 *          RTO-L/RTO-H share one table, so a flat parser mis-assigns columns —
 *          which would produce a wrong buildable envelope.
 * STATUS   MACHINE-EXTRACTED, NOT VERIFIED BY A REVIEWER.
 *
 * Before using a number from here:
 *
 * 1. Standards vary BY USE TYPE within a zone. `useColumns` names them;
 *    `values` is positional against that array.
 * 2. The county says "yard depth", not "setback".
 * 3. Footnote markers like "(4)" are RETAINED IN THE VALUE STRING on purpose.
 *    "45 (4)" is not the number 45 — it is 45 subject to footnote 4. Use
 *    parsePgStandardValue(); never coerce these to numbers blindly.
 * 4. LCD, LMUTC, LMXC and RMH are absent because Sec. 27-4205 publishes no
 *    dimensional table for them — those legacy comprehensive-design zones are
 *    governed by their prior approved plans.
 *
 * Regenerate with scripts/extract-pg-dimensions.py; do not hand-edit.
 */

export interface PgDimensionalRow {
  standard: string
  values: string[]
}

export interface PgZoneDimensionalTable {
  zone: string
  section: string
  useColumns: string[]
  rows: PgDimensionalRow[]
  notes: string[]
  source: {
    publication: string
    url: string
    effectiveDate: string
    retrievedAt: string
    extraction: 'machine'
    verifiedBy: string | null
    verifiedAt: string | null
  }
}

const EFFECTIVE = "2022-04-01"
const RETRIEVED = "2026-08-20"
const PUBLICATION = "Prince George's County Zoning Ordinance, Subdivision Regulations & Landscape Manual (Effective 4/1/2022)"
const VIEWER = "https://online.encodeplus.com/regs/princegeorgescounty-md/"

export const PG_ZONE_DIMENSIONAL_TABLES: Readonly<Record<string, PgZoneDimensionalTable>> = {
  "ROS": {
    zone: "ROS", section: "27-4201",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["0.05", "No requirement"] },
      { standard: "Net lot area, min. (ac) (2)", values: ["20.00", "20.00"] },
      { standard: "Lot width, min. (ft)", values: ["300", "300"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["240", "240"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["2", "10"] },
      { standard: "Front yard depth, min. (ft)", values: ["50", "50"] },
      { standard: "Side yard depth, min. (ft) (3)", values: ["20", "20"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["35", "35"] },
      { standard: "Accessory structure height, max. (ft) (4)", values: ["15", "15"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) Not applicable to land in public ownership. (3) On corner lot, min. side yard depth alongsid"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "AG": {
    zone: "AG", section: "27-4201",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["0.20", "No requirement"] },
      { standard: "Net lot area, min. (ac)", values: ["5.00", "5.00"] },
      { standard: "Lot width, min. (ft)", values: ["300", "300"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["240", "240"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["5", "25"] },
      { standard: "Front yard depth, min. (ft)", values: ["50", "50"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["20", "20"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["35", "35"] },
      { standard: "Accessory structure height, max. (ft) (3)", values: ["15", "15"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 50 ft.❻ (3) May be increased for cert"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "AR": {
    zone: "AR", section: "27-4201",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["0.50", "No requirement"] },
      { standard: "Net lot area, min. (ac)", values: ["2.00", "2.00"] },
      { standard: "Lot width, min. (ft)", values: ["150", "150"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["120", "120"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["10", "25"] },
      { standard: "Front yard depth, min. (ft)", values: ["50", "50"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["17", "17"] },
      { standard: "Rear yard depth, min. (ft)", values: ["35", "35"] },
      { standard: "Principal structure height, max. (ft)", values: ["50", "50"] },
      { standard: "Accessory structure height, max. (ft) (3) (4)", values: ["15", "15"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 50 ft.❻ (3) May be increased for cert"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RE": {
    zone: "RE", section: "27-4202",
    useColumns: ["Agricultural Uses", "Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["No requirement", "1.08", "No requirement"] },
      { standard: "Net lot area, min.", values: ["2 ac", "40,000", "40,000"] },
      { standard: "Lot width, min. (ft)", values: ["50", "120(4)", "50"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["40", "70", "40"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["20", "20", "60"] },
      { standard: "Front yard depth, min. (ft)", values: ["25", "25", "25"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["17", "17", "17"] },
      { standard: "Rear yard depth, min. (ft)", values: ["25", "25", "25"] },
      { standard: "Principal structure height, max. (ft)", values: ["35", "35", "35"] },
      { standard: "Accessory structure height, max. (ft) (3)", values: ["15", "15", "15"] },
      { standard: "Single-Family Detached Dwellings and Agricultural and Other Uses", values: ["Single-Family Detached Dwellings and Agricultural and Other Uses", "Single-Family Detached Dwellings and Agricultural and Other Uses", "Single-Family Detached Dwellings and Agricultural and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 25 ft.❻ (3) May be increased for cert"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RR": {
    zone: "RR", section: "27-4202",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["2.17", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["20,000", "20,000"] },
      { standard: "Lot width, min. (ft)", values: ["80(4)", "100"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["70", "70"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["25", "60"] },
      { standard: "Front yard depth, min. (ft)", values: ["25", "25"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["8", "8"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["40", "40"] },
      { standard: "Accessory structure height, max. (ft) (3)", values: ["15", "15"] },
      { standard: "Single-Family Detached Dwellings and Other Uses", values: ["Single-Family Detached Dwellings and Other Uses", "Single-Family Detached Dwellings and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 25 ft.❻ (3) May be increased for cert"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RSF-95": {
    zone: "RSF-95", section: "27-4202",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["4.58", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["9,500", "9,500"] },
      { standard: "Lot width, min. (ft)", values: ["75", "75"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["50 (4)", "60"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["30", "60"] },
      { standard: "Front yard depth, min. (ft)", values: ["25", "25"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["8", "8"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["40", "40"] },
      { standard: "Accessory structure height, max. (ft) (3)", values: ["15", "15"] },
      { standard: "Single-Family Detached Dwellings and Other Uses", values: ["Single-Family Detached Dwellings and Other Uses", "Single-Family Detached Dwellings and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 25 ft.❻ (3) May be increased for cert"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RSF-65": {
    zone: "RSF-65", section: "27-4202",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["6.7", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["6,500", "6,500"] },
      { standard: "Lot width, min. (ft)", values: ["65", "45"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["45 (4)", "36"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["35", "60"] },
      { standard: "Front yard depth, min. (ft)", values: ["25", "25"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["8", "8"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["40", "40"] },
      { standard: "Accessory structure height, max. (ft) (3)", values: ["15", "15"] },
      { standard: "Single-Family Detached Dwellings and Other Uses", values: ["Single-Family Detached Dwellings and Other Uses", "Single-Family Detached Dwellings and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 25 ft.❻ (3) May be increased for cert"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RSF-A": {
    zone: "RSF-A", section: "27-4202",
    useColumns: ["", "Single-Family Detached Dwelling", "Two-Family Dwelling", "Three-Family Dwelling", "Townhouse Dwelling", "Other Uses", ""],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["Density, max. (du/ac of net lot area)", "8.70", "32.66", "12.44", "16.33", "No requirement", ""] },
      { standard: "Net lot area, min. (sf)", values: ["Net lot area, min. (sf)", "5,000", "No requirement", "No requirement", "No requirement", "6,500", ""] },
      { standard: "Lot width, min. (ft)", values: ["❶ Lot width, min. (ft)", "45 (10)", "60 (8)", "40", "20 (5)", "45", ""] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["Lot frontage (width) at front street line, min. (ft)", "40", "48 (9)", "32", "16", "36", ""] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["Lot coverage, max. (% of net lot area)", "40", "45 (2)", "40 (2)", "45 (2)", "60", ""] },
      { standard: "Front yard depth, min. (ft)", values: ["❷ Front yard depth, min. (ft)", "15", "15", "15", "15", "15", ""] },
      { standard: "Side yard depth, min. (ft)", values: ["❸ Side yard depth, min. (ft)", "8 (3)", "8 (4)", "8 (4)", "8 (4)", "8 (3)", ""] },
      { standard: "Rear yard depth, min. (ft)", values: ["❹ Rear yard depth, min. (ft)", "20", "20 (7)", "20", "20 (7)", "20", ""] },
      { standard: "Principal structure height, max. (ft)", values: ["❺ Principal structure height, max. (ft)", "40", "50", "40", "50", "40", ""] },
      { standard: "Accessory structure height, max. (ft) (6)", values: ["Accessory structure height, max. (ft) (6)", "25", "25", "25", "25", "25", ""] },
      { standard: "Single-Family Dwellings and Two- and Three- Family Dwellings", values: ["Single-Family Dwellings and Two- and Three- Family Dwellings", "Single-Family Dwellings and Two- and Three- Family Dwellings", "Single-Family Dwellings and Two- and Three- Family Dwellings", "Townhouse Dwellings and Other Uses", "Townhouse Dwellings and Other Uses", "Townhouse Dwellings and Other Uses", "Townhouse Dwellings and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) Applicable to the lot coverage of the development lot as a whole rather than individual lots"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RMF-12": {
    zone: "RMF-12", section: "27-4202",
    useColumns: ["Single-Family Detached Dwelling", "Two-Family Dwelling", "Three-Family Dwelling", "Townhouse Dwelling", "Multifamily Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["8.70", "24.00", "10.00", "12.00", "12.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["5,000", "No requirement", "No requirement", "No requirement", "9,000", "14,000"] },
      { standard: "Lot width, min. (ft)", values: ["50", "60 (2)(8)", "60 (2)", "20 (2)(6)", "75 (2)", "75 (2)"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["40", "48 (9)", "48", "16", "60", "60"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["30", "35 (3)", "35 (3)", "35 (3)", "35", "20"] },
      { standard: "Green area, min. (% of net lot area)", values: ["No requirement", "No requirement", "No requirement", "50", "50", "70"] },
      { standard: "Front yard depth, min. (ft)", values: ["15", "15", "15", "15", "15", "20"] },
      { standard: "Side yard depth, min. (ft)", values: ["8", "8 (4)", "8 (4)", "8 (4)", "8 (5)", "8 (5)"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20", "20", "20", "20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["40", "50", "40", "50", "50", "40"] },
      { standard: "Accessory structure height, max. (ft) (7)", values: ["15", "15", "15", "15", "15", "15"] },
      { standard: "Single-Family Detached Dwellings", values: ["Single-Family Detached Dwellings", "Single-Family Detached Dwellings", "Two- and Three-Family Dwellings", "Two- and Three-Family Dwellings", "Two- and Three-Family Dwellings", "Two- and Three-Family Dwellings"] },
      { standard: "Townhouse Dwellings", values: ["Townhouse Dwellings", "Townhouse Dwellings", "Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 100 ft on corner lots.❻ (3) Applicable to the building coverage of the development lot as a "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RMF-20": {
    zone: "RMF-20", section: "27-4202",
    useColumns: ["Two-Family Dwelling", "Three-Family Dwelling", "Townhouse Dwelling", "Multifamily Dwelling", "Other Uses", ""],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["40.00", "14.00", "20.00", "20.00", "No requirement", ""] },
      { standard: "Net lot area, min. (sf)", values: ["No requirement", "No requirement", "No requirement", "7,500", "7,500", ""] },
      { standard: "Lot width, min. (ft)", values: ["60 (2)(9)", "60 (2)", "20 (7)", "60 (2)", "60 (2)", ""] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["48 (10)", "48", "16", "48", "48", ""] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["35 (3)", "35 (3)", "40 (3)", "40", "60", ""] },
      { standard: "Green area, min. (% of net lot area)", values: ["No requirement", "No requirement", "50", "60", "No requirement", ""] },
      { standard: "Front yard depth, min. (ft)", values: ["15", "15", "15", "15", "0", ""] },
      { standard: "Side yard depth, min. (ft)", values: ["8 (4)", "8 (4)", "8 (4)", "8 (5)", "8 (5)", ""] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20", "20", "20", "20", ""] },
      { standard: "Principal structure height, max. (ft) (6)", values: ["50", "50", "50", "50", "50", ""] },
      { standard: "Accessory structure height, max. (ft) (7)(8)", values: ["15", "15", "15", "15", "15", ""] },
      { standard: "Two- and Three-Family Dwellings", values: ["Two- and Three-Family Dwellings", "Two- and Three-Family Dwellings", "Two- and Three-Family Dwellings", "Townhouse Dwellings", "Townhouse Dwellings", "Townhouse Dwellings"] },
      { standard: "Multifamily Dwellings and Other Uses", values: ["Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 80 ft on corner lots.❻ (3) Applicable to the building coverage of the development lot as a w"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RMF-48": {
    zone: "RMF-48", section: "27-4202",
    useColumns: ["Multifamily Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["48.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["7,500", "7,500"] },
      { standard: "Lot width, min. (ft)", values: ["75 (2)", "75 (2)"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["60", "60"] },
      { standard: "Lot coverage, max. (% of development lot as a whole)", values: ["60", "60"] },
      { standard: "Front yard depth, min. (ft)", values: ["15", "15"] },
      { standard: "Side yard depth, min. (ft) (both yards total/either yard) (3)", values: ["8", "8"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["110 (4)(5)", "110 (5)"] },
      { standard: "Accessory structure height, max. (ft) (6)", values: ["15", "15"] },
      { standard: "Multifamily Dwellings and Other Uses", values: ["Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 100 ft on corner lots. ❻ (3) On corner lot, min. side yard depth alongside street = 30 ft. ❼"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "CN": {
    zone: "CN", section: "27-4203",
    useColumns: ["Single-Family Detached Dwelling", "Two-Family Dwelling", "Townhouse Dwelling, including “Dwelling, Live-Work” uses", "Multifamily Dwelling (2)", "Other Uses", ""],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["9.00", "24.00", "12.00", "12.00", "No requirement", ""] },
      { standard: "Net lot area, min. (sf)", values: ["4,000", "No requirement", "No requirement", "9,000", "No requirement", ""] },
      { standard: "Lot width, min. (ft)", values: ["50", "50 (4)", "20", "75", "50", ""] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["60", "65 (3)", "65 (3)", "65", "65", ""] },
      { standard: "Front yard depth, min. (ft)", values: ["10", "No requirement", "No requirement", "No requirement", "No requirement", ""] },
      { standard: "Side yard depth, min. (ft)", values: ["5", "No requirement", "No requirement", "No requirement", "No requirement", ""] },
      { standard: "Rear yard depth , min. (ft)", values: ["15", "15", "15", "20", "20", ""] },
      { standard: "Principal structure height, max. (ft)", values: ["35", "50", "50", "50", "50", ""] },
      { standard: "Multifamily Dwellings and Other Uses", values: ["Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses", "Multifamily Dwellings and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) The standards in this column apply to multifamily dwellings as stand-alone development. Dwel"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "CS": {
    zone: "CS", section: "27-4203",
    useColumns: ["Multifamily Dwelling, Artists' Residential Studio, Live-Work Dwelling (2)", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["20.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["7,500", "5,000"] },
      { standard: "Lot width, min. (ft)", values: ["60 (3)", "50"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["40", "No requirement"] },
      { standard: "Front yard depth, min. (ft) (4)", values: ["15", "10"] },
      { standard: "Side yard depth, min. (ft) (4)", values: ["8", "0"] },
      { standard: "Rear yard depth, min. (ft) (4)", values: ["20", "0"] },
      { standard: "Principal structure height, max. (ft)", values: ["50", "50"] },
      { standard: "Multifamily Dwelling and Other Uses", values: ["Multifamily Dwelling and Other Uses", "Multifamily Dwelling and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) The standards in this column apply to multifamily dwellings, artists' residential studios, a"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "CGO": {
    zone: "CGO", section: "27-4203",
    useColumns: ["Two-Family Dwelling", "Townhouse Dwelling", "Multifamily Dwelling, Artists’ Residential Studio, Live-Work Dwelling (2)", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["40.00", "20.00", "48.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["No requirement", "No requirement", "7,500", "No requirement"] },
      { standard: "Lot width, min. (ft)", values: ["20", "20", "50", "No requirement"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["65 (3)", "65 (3)", "70", "No requirement"] },
      { standard: "Front yard depth, min. (ft)", values: ["10", "10", "10", "0"] },
      { standard: "Side yard depth, min. (ft)", values: ["8 (4)", "8 (4)", "8", "0"] },
      { standard: "Rear yard depth, min. (ft)", values: ["15", "15", "15", "0"] },
      { standard: "Principal structure height, max. (ft) (5) (6)", values: ["50", "50", "86", "No requirement"] },
      { standard: "Multifamily Dwelling and Other Uses", values: ["Multifamily Dwelling and Other Uses", "Multifamily Dwelling and Other Uses", "Multifamily Dwelling and Other Uses", "Multifamily Dwelling and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) The standards in this column apply to multifamily dwellings, artists’ residential studios, a"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "IE": {
    zone: "IE", section: "27-4203",
    useColumns: ["Multifamily Dwelling, Artists’ Residential Studio, Live-Work Dwelling (2)", "Other Uses Inside the Capital Beltway", "Other Uses Outside the Capital Beltway"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["20.00", "No requirement", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["10,000", "No requirement", "No requirement"] },
      { standard: "Lot width, min. (ft)", values: ["75", "No requirement", "No requirement"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["45", "90", "65 (6)"] },
      { standard: "Green area, min. (% of net lot area)", values: ["25", "10", "30 (6)"] },
      { standard: "Front yard depth, min. (ft)", values: ["10", "10", "10"] },
      { standard: "Side yard depth, min. (ft) (both yards total)", values: ["20", "20", "20"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0/20 (5)", "0/20 (5)", "0/20 (5)"] },
      { standard: "Building separation, min. (ft)", values: ["25 or height of taller building (3), whichever is greater", "25 or height of taller building (3), whichever is greater", "25 or height of taller building (3), whichever is greater"] },
      { standard: "Principal structure height, max. (ft) (4)", values: ["50", "No requirement", "No requirement"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) The standards in this column apply to multifamily dwellings, artists’ residential studios, a"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "IH": {
    zone: "IH", section: "27-4203",
    useColumns: ["Multifamily Dwelling, Artists’ Residential Studio, Live-Work Dwelling (2)", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["12.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["10,000", "10,000"] },
      { standard: "Lot width, min. (ft)", values: ["75", "75"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["No requirement", "No requirement"] },
      { standard: "Green area, min. (% of net lot area) (5)", values: ["10", "10"] },
      { standard: "Front yard depth, min. (ft)", values: ["25", "25"] },
      { standard: "Side yard depth, min. (ft) (both yards total)", values: ["30", "30"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0/20 (4)", "0/20 (4)"] },
      { standard: "Principal structure height, max. (ft) (3)", values: ["No requirement", "No requirement"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) The standards in this column apply to multifamily dwellings, artists’ residential studios, a"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "NAC": {
    zone: "NAC", section: "27-4204",
    useColumns: ["All Uses"],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["200 | 600"] },
      { standard: "Lot area, min. (sf)", values: ["5,000 (2)"] },
      { standard: "Lot width, min. (ft)", values: ["50 (3)"] },
      { standard: "Density, min. | max. (du/ac of net lot area) (4)", values: ["10.00 | 90.00"] },
      { standard: "Floor area ratio (FAR), min. | max. (5)", values: ["0.25 | 2.0"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["40 | 100"] },
      { standard: "Build-to line, min. | max. (ft) (6)(7)", values: ["15 | 35"] },
      { standard: "Building width in build-to zone, min. (% of lot width) (7)(8)", values: ["60"] },
      { standard: "Front yard depth, min. (ft)", values: ["0"] },
      { standard: "Side yard depth, min. (ft)", values: ["0"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0"] },
      { standard: "Building façade fenestration/transparency, min. (% of street-level façade area)", values: ["40"] },
      { standard: "Building façade fenestration/transparency, min. (% of street-level façade area)", values: ["35"] },
      { standard: "Principal structure height, min. |max. (ft)", values: ["No requirement | 60"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 1,200 sf for townhouse lots. (3) 18 ft for townhouse lots. (4) Applicable to residential dev"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "TAC-C": {
    zone: "TAC-C", section: "27-4204",
    useColumns: ["All Uses"],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["200 | 600"] },
      { standard: "Lot area, min. (sf)", values: ["1,500 (3)"] },
      { standard: "Lot width, min. (ft)", values: ["20 (4)"] },
      { standard: "Density, min. | max. (du/ac of net lot area) (5)", values: ["15.00 | 120.00"] },
      { standard: "Floor area ratio (FAR), min. | max. (6)", values: ["0.5 | 2.5"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["50 | 100"] },
      { standard: "Build-to line, min. | max. (ft) (7)(8)", values: ["15| 27"] },
      { standard: "Building width in build-to zone, min. (% of lot width) (8)(9)", values: ["70"] },
      { standard: "Front yard depth, min. (ft)", values: ["0"] },
      { standard: "Side yard depth, min. (ft)", values: ["0"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["40"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["35"] },
      { standard: "❻ Principal structure height, min. | max. (ft)", values: ["24 | 80"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) These standards do not apply to blocks in Edge areas that are entirely located more than one"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "TAC-E": {
    zone: "TAC-E", section: "27-4204",
    useColumns: ["Nonresidential & Mixed-Use", "Residential"],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["400 | 800 (2)", "400 | 800 (2)"] },
      { standard: "Lot area, min. (sf)", values: ["3,000", "5,000 (3)"] },
      { standard: "Lot width, min. (ft)", values: ["30", "50 (4)"] },
      { standard: "Density, min. | max. (du/ac of net lot area) (5)", values: ["5.00 | 100.00 (11)", "5.00 | 100.00"] },
      { standard: "Floor area ratio (FAR), min. | max. (6)", values: ["0.25 | 1.5", "No requirement"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["40 | 85", "No requirement | 75"] },
      { standard: "Build-to line, min. | max. (ft) (7)(8)", values: ["6 | 26 (2)", "6 |26 (2)"] },
      { standard: "Building width in build-to zone, min. (% of lot width) (8)(9)", values: ["50", "50"] },
      { standard: "Front yard depth, min. (ft)", values: ["0", "10"] },
      { standard: "Side yard depth, min. (ft)", values: ["0", "5 (10)"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0", "5"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["35", "No requirement"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["35", "No requirement"] },
      { standard: "❻ Principal structure height, min. | max. (ft)", values: ["No requirement | 70", "No requirement | 70"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) These standards do not apply to blocks in Edge areas that are entirely located more than one"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "LTO-C": {
    zone: "LTO-C", section: "27-4204",
    useColumns: ["All Uses"],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["200 | 600"] },
      { standard: "Lot area, min. (sf)", values: ["1,500"] },
      { standard: "Lot width, min. (ft)", values: ["20"] },
      { standard: "Density, min. | max. (du/ac of net lot area) (4)", values: ["20.00 | 150.00"] },
      { standard: "Floor area ratio (FAR), min. | max. (5)", values: ["0.5 | 3.0"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["65 | 100"] },
      { standard: "Build-to line, min. | max. (ft) (6)(7)", values: ["15| 27"] },
      { standard: "Building width in build-to zone, min. (% of lot width) (7)(8)", values: ["70"] },
      { standard: "Front yard depth, min. (ft)", values: ["0"] },
      { standard: "Side yard depth, min. (ft)", values: ["0"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["50"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["45"] },
      { standard: "Principal structure height, min. | max. (ft)", values: ["24 | 100"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 1,000 sf for townhouse lots. (3) 16 ft for townhouse lots. (4) Applicable to residential dev"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "LTO-E": {
    zone: "LTO-E", section: "27-4204",
    useColumns: ["Nonresidential & Mixed-Use", "Residential"],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["400 | 800", "400 | 800"] },
      { standard: "Lot area, min. (sf)", values: ["3,000", "5,000 (2)"] },
      { standard: "Lot width, min. (ft)", values: ["30", "50 (3)"] },
      { standard: "Density, min. | max. (du/ac of net lot area) (4)", values: ["10.00 | 120.00 (10)", "10.00 | 120.00"] },
      { standard: "Floor area ratio (FAR), min. | max. (5)", values: ["0.25 | 2.0", "No requirement"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["50 | 90", "No requirement | 90"] },
      { standard: "Build-to line, min. | max. (ft) (6)(7)", values: ["11 | 31", "11 | 31"] },
      { standard: "Building width in build-to zone, min. (% of lot width) (7)(8)", values: ["50", "50"] },
      { standard: "Front yard depth, min. (ft)", values: ["0", "10"] },
      { standard: "Side yard depth, min. (ft)", values: ["0", "5 (9)"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0", "0"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["40", "No requirement"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["35", "No requirement"] },
      { standard: "Principal structure height, min. | max. (ft)", values: ["No requirement | 80", "No requirement | 80"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 1,000 sf for townhouse lots. (3) 16 ft for townhouse lots. (4) Applicable to residential dev"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RTO-L-C": {
    zone: "RTO-L-C", section: "27-4204",
    useColumns: ["All Uses"],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["200 | 600"] },
      { standard: "Lot area, min. (sf)", values: ["1,500"] },
      { standard: "Lot width, min. (ft)", values: ["20"] },
      { standard: "Density, min. | max. (du/ac of net lot area) (4)", values: ["30.00 | 175.00"] },
      { standard: "Floor area ratio (FAR), min. | max. (5)", values: ["1.0 | 4.0"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["70 | 100"] },
      { standard: "Build-to line, min. | max. (ft) (6)(7)", values: ["20 | 30"] },
      { standard: "Building width in build-to zone, min. (% of lot width) (7)(8)", values: ["80"] },
      { standard: "Front yard depth, min. (ft)", values: ["0"] },
      { standard: "Side yard depth, min. (ft)", values: ["0"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["50"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["45"] },
      { standard: "Principal structure height, min. | max. (ft)", values: ["35 | No requirement (10)"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 1,000 sf for townhouse lots. (3) 16 ft for townhouse lots. (4) Applicable to residential dev"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RTO-L-E": {
    zone: "RTO-L-E", section: "27-4204",
    useColumns: ["Nonresidential & Mixed-Use", "Residential"],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["400 | 800", "400 | 800"] },
      { standard: "Lot area, min. (sf)", values: ["3,000", "5,000 (2)"] },
      { standard: "Lot width, min. (ft)", values: ["30", "50 (3)"] },
      { standard: "Density, min. | max. (du/ac of net lot area) (4)", values: ["20.00 | 140.00 (12)", "20.00 | 140.00"] },
      { standard: "Floor area ratio (FAR), min. | max. (5)", values: ["0.25 | 2.5", "No requirement"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["50 | 90", "No requirement | 80"] },
      { standard: "Build-to line, min. | max. (ft) (6)(7)", values: ["15 | 27", "15 | 35"] },
      { standard: "Building width in build-to zone, min. (% of lot width) (7)(8)", values: ["70", "70"] },
      { standard: "Front yard depth, min. (ft)", values: ["0", "10"] },
      { standard: "Side yard depth, min. (ft)", values: ["0", "5 (9)"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0", "0"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["40", "No requirement"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["45", "No requirement"] },
      { standard: "Principal structure height, min. | max. (ft)", values: ["35 | 126 (10)", "35 | 126 (10)"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 1,000 sf for townhouse lots. (3) 16 ft for townhouse lots. (4) Applicable to residential dev"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RTO-H-C": {
    zone: "RTO-H-C", section: "27-4204",
    useColumns: ["All Uses"],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["200 | 600"] },
      { standard: "Lot area, min. (sf)", values: ["1,500"] },
      { standard: "Lot width, min. (ft)", values: ["20"] },
      { standard: "Density, min. | max. (du/ac of net lot area) (4)", values: ["30.00 | 250.00"] },
      { standard: "Floor area ratio (FAR), min. | max. (5)", values: ["1.5 | 5.0"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["70 | 100"] },
      { standard: "Build-to line, min. | max. (ft) (6)(7)", values: ["20 | 30"] },
      { standard: "Building width in build-to zone, min. (% of lot width) (7)(8)", values: ["80"] },
      { standard: "Front yard depth, min. (ft)", values: ["0"] },
      { standard: "Side yard depth, min. (ft)", values: ["0"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["50"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["45"] },
      { standard: "Principal structure height, min. | max. (ft)", values: ["45 |  No requirement (11)"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 1,000 sf for townhouse lots. (3) 16 ft for townhouse lots. (4) Applicable to residential dev"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RTO-H-E": {
    zone: "RTO-H-E", section: "27-4204",
    useColumns: ["Nonresidential & Mixed-Use", "Residential"],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["400 | 800", "400 | 800"] },
      { standard: "Lot area, min. (sf)", values: ["3,000", "5,000 (2)"] },
      { standard: "Lot width, min. (ft)", values: ["30", "50 (3)"] },
      { standard: "Density, min. | max. (du/ac of net lot area) (4)", values: ["20.00 | 175.00 (12)", "20.00 | 175.00"] },
      { standard: "Floor area ratio (FAR), min. | max. (5)", values: ["0.5 | 3.0", "No requirement"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["50 | 90", "No requirement | 80"] },
      { standard: "Build-to line, min. | max. (ft) (6)(7)", values: ["15 | 27", "15 | 35"] },
      { standard: "Building width in build-to zone, min. (% of lot width) (7)(8)", values: ["70", "70"] },
      { standard: "Front yard depth, min. (ft)", values: ["0", "10"] },
      { standard: "Side yard depth, min. (ft)", values: ["0", "5 (9)"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0", "0"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["50", "No requirement"] },
      { standard: "Building façade fenestration/transparency min. (% of street-level façade area)", values: ["45", "No requirement"] },
      { standard: "Principal structure height, min. | max. (ft)", values: ["35| 182 (11)", "35| 182 (11)"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 1,000 sf for townhouse lots. (3) 16 ft for townhouse lots. (4) Applicable to residential dev"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "R-PD": {
    zone: "R-PD", section: "27-4300",
    useColumns: [""],
    rows: [
      { standard: "Density, min. (du/net lot areas)", values: ["1.00"] },
      { standard: "Density, max. (du/net lot area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Net lot area, min. (sf)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Lot width, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Front yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Side yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Rear yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Principal structure height, max. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
    ],
    notes: ["NOTES: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. NOTES: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) See measurement rules and "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "NAC-PD": {
    zone: "NAC-PD", section: "27-4300",
    useColumns: ["All Uses", ""],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Lot area, min. | max. (sf.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Lot width, min. (ft)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Density, min. (du/ net lot area) (2)", values: ["10.00", ""] },
      { standard: "Floor area ratio (FAR), min. (3)", values: ["0.25", ""] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Density, max. (du/net lot area) (2)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Floor area ratio (FAR), min. (3)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Density, min. (du/net lot areas)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Front yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Build-to line, min. | max. (ft.) (4)(5)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building width in build-to zone, min. (% of lot width)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Front yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Side yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Rear yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building façade transparency, min. (% of street-level façade area) (6)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building façade transparency, min. (% of street-level façade area) (6)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Principal structure height, max. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
    ],
    notes: ["NOTES: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) Applicable to residential development and the residential component of mixed-use development."],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "TAC-PD": {
    zone: "TAC-PD", section: "27-4300",
    useColumns: ["Core (1) / All Uses", "Edge (1) / Nonresidential & Mixed-Use", "Edge (1) / Residential", ""],
    rows: [
      { standard: "Block length, min. | max. (ft.)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", ""] },
      { standard: "Lot area, min. | max. (sf.)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", ""] },
      { standard: "Lot width, min. (ft.)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", ""] },
      { standard: "Density, min. (du/net lot area) (3)", values: ["15.00", "10.00 (8)", "5.00", ""] },
      { standard: "Floor area ratio (FAR), min. (4)", values: ["0.50", "0.25", "No requirement", ""] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Density, max. (du/net lot area) (3)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Floor area ratio (FAR), max. (4)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Build-to line, min. | max. (ft.) (5)(6)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building width in build-to zone, min. (% of lot width) (7)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Front yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Side yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Rear yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building façade transparency, min. (% of street-level façade area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building façade transparency, min. (% of street-level façade area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Principal and accessory structure height, max. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Notes: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) A Core area and an Edge area may have been designated by the applicable Area Master Plan or Sector Plan. Where a Core area is not designated, the PD Zone may not incorporate standards applicable to a Core area. (2) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (3) Applicable to residential development and the residential component of mixed-use development. (4) Applicable to nonresidential development. (5) The area between the minimum and maximum build-to lines that extends the width of the lot constitutes the build-to zone. (6) The remaining build-to zone width may be occupied by outdoor gathering spaces, walkways, landscaped areas, stormwater management facilities that use Environmental Site Design techniques, and driveways (subject to Section 27-6206(b)(1)). (7) Where existing buildings along a street frontage are all located behind the build-to zone, such buildings may not be extended to the rear or side unless they are first extended frontwards to comply with the maximum build-to line standard and the minimum building width in build-to zone standard. (8) For the residential component of mixed-use development only.", values: ["Notes: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) A Core area and an Edge area may have been designated by the applicable Area Master Plan or Sector Plan. Where a Core area is not designated, the PD Zone may not incorporate standards applicable to a Core area. (2) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (3) Applicable to residential development and the residential component of mixed-use development. (4) Applicable to nonresidential development. (5) The area between the minimum and maximum build-to lines that extends the width of the lot constitutes the build-to zone. (6) The remaining build-to zone width may be occupied by outdoor gathering spaces, walkways, landscaped areas, stormwater management facilities that use Environmental Site Design techniques, and driveways (subject to Section 27-6206(b)(1)). (7) Where existing buildings along a street frontage are all located behind the build-to zone, such buildings may not be extended to the rear or side unless they are first extended frontwards to comply with the maximum build-to line standard and the minimum building width in build-to zone standard. (8) For the residential component of mixed-use development only.", "Notes: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) A Core area and an Edge area may have been designated by the applicable Area Master Plan or Sector Plan. Where a Core area is not designated, the PD Zone may not incorporate standards applicable to a Core area. (2) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (3) Applicable to residential development and the residential component of mixed-use development. (4) Applicable to nonresidential development. (5) The area between the minimum and maximum build-to lines that extends the width of the lot constitutes the build-to zone. (6) The remaining build-to zone width may be occupied by outdoor gathering spaces, walkways, landscaped areas, stormwater management facilities that use Environmental Site Design techniques, and driveways (subject to Section 27-6206(b)(1)). (7) Where existing buildings along a street frontage are all located behind the build-to zone, such buildings may not be extended to the rear or side unless they are first extended frontwards to comply with the maximum build-to line standard and the minimum building width in build-to zone standard. (8) For the residential component of mixed-use development only.", "Notes: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) A Core area and an Edge area may have been designated by the applicable Area Master Plan or Sector Plan. Where a Core area is not designated, the PD Zone may not incorporate standards applicable to a Core area. (2) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (3) Applicable to residential development and the residential component of mixed-use development. (4) Applicable to nonresidential development. (5) The area between the minimum and maximum build-to lines that extends the width of the lot constitutes the build-to zone. (6) The remaining build-to zone width may be occupied by outdoor gathering spaces, walkways, landscaped areas, stormwater management facilities that use Environmental Site Design techniques, and driveways (subject to Section 27-6206(b)(1)). (7) Where existing buildings along a street frontage are all located behind the build-to zone, such buildings may not be extended to the rear or side unless they are first extended frontwards to comply with the maximum build-to line standard and the minimum building width in build-to zone standard. (8) For the residential component of mixed-use development only.", "Notes: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) A Core area and an Edge area may have been designated by the applicable Area Master Plan or Sector Plan. Where a Core area is not designated, the PD Zone may not incorporate standards applicable to a Core area. (2) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (3) Applicable to residential development and the residential component of mixed-use development. (4) Applicable to nonresidential development. (5) The area between the minimum and maximum build-to lines that extends the width of the lot constitutes the build-to zone. (6) The remaining build-to zone width may be occupied by outdoor gathering spaces, walkways, landscaped areas, stormwater management facilities that use Environmental Site Design techniques, and driveways (subject to Section 27-6206(b)(1)). (7) Where existing buildings along a street frontage are all located behind the build-to zone, such buildings may not be extended to the rear or side unless they are first extended frontwards to comply with the maximum build-to line standard and the minimum building width in build-to zone standard. (8) For the residential component of mixed-use development only."] },
    ],
    notes: [],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "LTO-PD": {
    zone: "LTO-PD", section: "27-4300",
    useColumns: ["Core (1) / All Uses", "Edge (1) / Nonresidential & Mixed-Use", "Edge (1) / Residential", ""],
    rows: [
      { standard: "Block length, min. | max. (ft.)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", ""] },
      { standard: "Lot area, min. | max. (sf.)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", ""] },
      { standard: "Lot width, min. (ft.)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", ""] },
      { standard: "Density, min. (du/net lot area) (3)", values: ["10.00", "10.00 (8)", "10.00", ""] },
      { standard: "Floor area ratio (FAR), min. (4)", values: ["0.50", "0.25", "No requirement", ""] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Density, max. (du/net lot area) (3)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Floor area ratio (FAR), max. (4)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Build-to line, min. | max. (ft.) (5)(6)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building width in build-to zone, min. (% of lot width) (7)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Front yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Side yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Rear yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building façade transparency, min. (% of street-level façade area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building façade transparency, min. (% of street-level façade area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Principal and accessory structure height, max. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
    ],
    notes: ["NOTES: sf = square feet; ft = feet; du = dwelling unit; ac = acre (1) A Core area and an Edge area may have been designated by the applicable Area Master Plan or Sector Plan. Where a Core area is not designated, the PD Zone may not incorporate standards applicable to a Core area. (2) See measurement"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RTO-PD": {
    zone: "RTO-PD", section: "27-4300",
    useColumns: ["Core (1) / All Uses", "Edge (1) / Nonresidential & Mixed-Use", "Edge (1) / Residential", ""],
    rows: [
      { standard: "Block length, min. | max. (ft.)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", ""] },
      { standard: "Lot area, min. | max. (sf.)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", ""] },
      { standard: "Lot width, min. (ft.)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", "To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))", ""] },
      { standard: "Density, min. (du/net lot area) (3)", values: ["30.00", "20.00 (8)", "20.00", ""] },
      { standard: "Floor area ratio (FAR), min. (4)", values: ["1.00", "0.25", "No requirement", ""] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Density, max. (du/net lot area) (3)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Floor area ratio (FAR), max. (4)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Build-to line, min. | max. (ft.) (5)(6)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building width in build-to zone, min. (% of lot width) (7)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Front yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Side yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Rear yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building façade transparency, min. (% of street-level façade area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Building façade transparency, min. (% of street-level façade area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
      { standard: "Principal and accessory structure height, max. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", "To be established in PD Basic Plan (see Section 27-4301(d))", ""] },
    ],
    notes: ["NOTES: sf = square feet; ft = feet; du = dwelling unit; ac = acre (1) A Core area and an Edge area may have been designated by the applicable Area Master Plan or Sector Plan. Where a Core area is not designated, the PD Zone may not incorporate standards applicable to a Core area. (2) See measurement"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "MU-PD": {
    zone: "MU-PD", section: "27-4300",
    useColumns: ["All Uses"],
    rows: [
      { standard: "Lot area, min. | max. (sf.)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))"] },
      { standard: "Lot width, min. (ft)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))"] },
      { standard: "Density, min. (du/net lot area) (2)", values: ["6.00"] },
      { standard: "Density, max. (net lot area) (2)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Floor area ratio (FAR), max. (3)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Front yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Side yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Rear yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Principal and accessory structure height, max. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Notes: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) Applicable to residential development and the residential component of mixed-use development. (3) Applicable to nonresidential development.", values: ["Notes: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) Applicable to residential development and the residential component of mixed-use development. (3) Applicable to nonresidential development."] },
    ],
    notes: [],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "IE-PD": {
    zone: "IE-PD", section: "27-4300",
    useColumns: ["All Uses"],
    rows: [
      { standard: "Density, max. (du/net lot area) (2)", values: ["12.00"] },
      { standard: "Lot area, min. | max. (sf.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Lot width, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Floor area ratio (FAR), min. | max. (3)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Front yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Side yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Rear yard depth, min. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Principal structure height, max. (ft.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Notes: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) Applicable to residential development and the residential component of mixed-use development. (3) Applicable to nonresidential development.", values: ["Notes: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) Applicable to residential development and the residential component of mixed-use development. (3) Applicable to nonresidential development."] },
    ],
    notes: [],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
}

/**
 * Zones with no dimensional table in the ordinance. Sec. 27-4205 legacy
 * comprehensive-design zones are governed by their prior approved plans, so
 * there is nothing to extract — a reviewer must consult the approved plan.
 */
export const PG_ZONES_REQUIRING_MANUAL_TRANSCRIPTION: readonly string[] = [
  "RMH", "LCD", "LMXC", "LMUTC",
]
