/**
 * Prince George's County — dimensional standards, extracted from the adopted
 * Zoning Ordinance (Subtitle 27, effective 2022-04-01).
 *
 * SOURCE  online.encodeplus.com/regs/princegeorgescounty-md — the county's own
 *         publication of "Zoning Ordinance, Subdivision Regulations, &
 *         Landscape Manual (Effective 4/1/2022)".
 * METHOD  Machine-extracted from the "Intensity and Dimensional Standards"
 *         table in each zone's subsection.
 * STATUS  MACHINE-EXTRACTED, NOT YET VERIFIED BY A REVIEWER.
 *
 * Read this before using a number from here:
 *
 * 1. Standards are PER USE TYPE within a zone, not one set per zone. RSF-A has
 *    different lot coverage for a townhouse than for a two-family dwelling.
 *    `useColumns` names the columns; `values` is positional against them.
 * 2. The county says "yard depth", not "setback". Front/side/rear yard depth is
 *    the setback equivalent.
 * 3. Footnote markers like "(2)" are PRESERVED IN THE VALUE STRING deliberately.
 *    They carry legal conditions that change the number. A value of "45 (4)" is
 *    not the number 45 — it is 45 subject to footnote 4. Never strip them and
 *    never coerce these to numbers without reading the footnote.
 * 4. Some zones are absent — see PG_ZONES_REQUIRING_MANUAL_TRANSCRIPTION.
 *
 * Generated by scripts/extract-pg-dimensions.py. Do not hand-edit; re-run and
 * re-review instead.
 */

export interface PgDimensionalRow {
  /** Standard name exactly as printed in the ordinance. */
  standard: string
  /** Positional against `useColumns`. Footnote markers retained. */
  values: string[]
}

export interface PgZoneDimensionalTable {
  zone: string
  section: string
  /** Use types the standards vary by. */
  useColumns: string[]
  rows: PgDimensionalRow[]
  notes: string[]
  source: {
    publication: string
    url: string
    effectiveDate: string
    retrievedAt: string
    extraction: 'machine'
    /** null until a qualified reviewer signs off. */
    verifiedBy: string | null
    verifiedAt: string | null
  }
}

const EFFECTIVE = "2022-04-01"
const RETRIEVED = "2026-08-20"
const PUBLICATION = "Prince George's County Zoning Ordinance, Subdivision Regulations & Landscape Manual (Effective 4/1/2022)"
const VIEWER = "https://online.encodeplus.com/regs/princegeorgescounty-md/doc-viewer.aspx"

export const PG_ZONE_DIMENSIONAL_TABLES: Readonly<Record<string, PgZoneDimensionalTable>> = {
  "ROS": {
    zone: "ROS",
    section: "27-4201",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["0.05", "No requirement"] },
      { standard: "Net lot area, min. (ac) (2)", values: ["20.00", "20.00"] },
      { standard: "Lot width, min. (ft)", values: ["300", "300"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["240", "240"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["2", "10"] },
      { standard: "Front yard depth, min. (ft)", values: ["50", "50"] },
      { standard: "Side yard depth, min. (ft) (3)", values: ["20", "20"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["35", "35"] },
      { standard: "Accessory structure height, max. (ft) (4)", values: ["15", "15"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) Not applicable to land in public ownership. (3) On corner lot, min. side yard depth alongside street = 50 ft.❻ (4) May be increased for certain purposes by approval of a special exception purs"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "AG": {
    zone: "AG",
    section: "27-4201",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["0.20", "No requirement"] },
      { standard: "Net lot area, min. (ac)", values: ["5.00", "5.00"] },
      { standard: "Lot width, min. (ft)", values: ["300", "300"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["240", "240"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["5", "25"] },
      { standard: "Front yard depth, min. (ft)", values: ["50", "50"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["20", "20"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["35", "35"] },
      { standard: "Accessory structure height, max. (ft) (3)", values: ["15", "15"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 50 ft.❻ (3) May be increased for certain purposes by approval of a special exception pursuant to Section 27-3604, Special Exception, and "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "AR": {
    zone: "AR",
    section: "27-4201",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["0.50", "No requirement"] },
      { standard: "Net lot area, min. (ac)", values: ["2.00", "2.00"] },
      { standard: "Lot width, min. (ft)", values: ["150", "150"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["120", "120"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["10", "25"] },
      { standard: "Front yard depth, min. (ft)", values: ["50", "50"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["17", "17"] },
      { standard: "Rear yard depth, min. (ft)", values: ["35", "35"] },
      { standard: "Principal structure height, max. (ft)", values: ["50", "50"] },
      { standard: "Accessory structure height, max. (ft) (3) (4)", values: ["15", "15"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 50 ft.❻ (3) May be increased for certain purposes by approval of a special exception pursuant to Section 27-3604, Special Exception. (4) "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RE": {
    zone: "RE",
    section: "27-4202",
    useColumns: ["Agricultural Uses", "Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["No requirement", "1.08", "No requirement"] },
      { standard: "Net lot area, min.", values: ["2 ac", "40,000", "40,000"] },
      { standard: "Lot width, min. (ft)", values: ["50", "120(4)", "50"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["40", "70", "40"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["20", "20", "60"] },
      { standard: "Front yard depth, min. (ft)", values: ["25", "25", "25"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["17", "17", "17"] },
      { standard: "Rear yard depth, min. (ft)", values: ["25", "25", "25"] },
      { standard: "Principal structure height, max. (ft)", values: ["35", "35", "35"] },
      { standard: "Accessory structure height, max. (ft) (3)", values: ["15", "15", "15"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 25 ft.❻ (3) May be increased for certain purposes by approval of a special exception pursuant to Section 27-3604, Special Exception, and "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RR": {
    zone: "RR",
    section: "27-4202",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["2.17", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["20,000", "20,000"] },
      { standard: "Lot width, min. (ft)", values: ["80(4)", "100"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["70", "70"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["25", "60"] },
      { standard: "Front yard depth, min. (ft)", values: ["25", "25"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["8", "8"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["40", "40"] },
      { standard: "Accessory structure height, max. (ft) (3)", values: ["15", "15"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 25 ft.❻ (3) May be increased for certain purposes by approval of a special exception pursuant to Section 27-3604, Special Exception, and "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RSF-95": {
    zone: "RSF-95",
    section: "27-4202",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["4.58", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["9,500", "9,500"] },
      { standard: "Lot width, min. (ft)", values: ["75", "75"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["50 (4)", "60"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["30", "60"] },
      { standard: "Front yard depth, min. (ft)", values: ["25", "25"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["8", "8"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["40", "40"] },
      { standard: "Accessory structure height, max. (ft) (3)", values: ["15", "15"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 25 ft.❻ (3) May be increased for certain purposes by approval of a special exception pursuant to Section 27-3604, Special Exception. (4) "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RSF-65": {
    zone: "RSF-65",
    section: "27-4202",
    useColumns: ["Single-Family Detached Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["6.7", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["6,500", "6,500"] },
      { standard: "Lot width, min. (ft)", values: ["65", "45"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["45 (4)", "36"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["35", "60"] },
      { standard: "Front yard depth, min. (ft)", values: ["25", "25"] },
      { standard: "Side yard depth, min. (ft) (2)", values: ["8", "8"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["40", "40"] },
      { standard: "Accessory structure height, max. (ft) (3)", values: ["15", "15"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) On corner lot, min. side yard depth alongside street = 25 ft.❻ (3) May be increased for certain purposes by approval of a special exception pursuant to Section 27-3604, Special Exception. (4) "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RSF-A": {
    zone: "RSF-A",
    section: "27-4202",
    useColumns: ["Single-Family Detached Dwelling", "Two-Family Dwelling", "Three-Family Dwelling", "Townhouse Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["8.70", "32.66", "12.44", "16.33", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["5,000", "No requirement", "No requirement", "No requirement", "6,500"] },
      { standard: "Lot width, min. (ft)", values: ["45 (10)", "60 (8)", "40", "20 (5)", "45"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["40", "48 (9)", "32", "16", "36"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["40", "45 (2)", "40 (2)", "45 (2)", "60"] },
      { standard: "Front yard depth, min. (ft)", values: ["15", "15", "15", "15", "15"] },
      { standard: "Side yard depth, min. (ft)", values: ["8 (3)", "8 (4)", "8 (4)", "8 (4)", "8 (3)"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20 (7)", "20", "20 (7)", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["40", "50", "40", "50", "40"] },
      { standard: "Accessory structure height, max. (ft) (6)", values: ["25", "25", "25", "25", "25"] },
      { standard: "Single-Family Dwellings and Two- and Three- Family Dwellings", values: ["Townhouse Dwellings and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) Applicable to the lot coverage of the development lot as a whole rather than individual lots under townhouse units. (3) On corner lot, min. side yard depth alongside street = 25 ft.❻ (4) Appli"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RMF-12": {
    zone: "RMF-12",
    section: "27-4202",
    useColumns: ["Single-Family Detached Dwelling", "Two-Family Dwelling", "Three-Family Dwelling", "Townhouse Dwelling", "Multifamily Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["8.70", "24.00", "10.00", "12.00", "12.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["5,000", "No requirement", "No requirement", "No requirement", "9,000", "14,000"] },
      { standard: "Lot width, min. (ft)", values: ["50", "60 (2)(8)", "60 (2)", "20 (2)(6)", "75 (2)", "75 (2)"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["40", "48 (9)", "48", "16", "60", "60"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["30", "35 (3)", "35 (3)", "35 (3)", "35", "20"] },
      { standard: "Green area, min. (% of net lot area)", values: ["No requirement", "No requirement", "No requirement", "50", "50", "70"] },
      { standard: "Front yard depth, min. (ft)", values: ["15", "15", "15", "15", "15", "20"] },
      { standard: "Side yard depth, min. (ft)", values: ["8", "8 (4)", "8 (4)", "8 (4)", "8 (5)", "8 (5)"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20", "20", "20", "20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["40", "50", "40", "50", "50", "40"] },
      { standard: "Accessory structure height, max. (ft) (7)", values: ["15", "15", "15", "15", "15", "15"] },
      { standard: "Single-Family Detached Dwellings", values: ["Two- and Three-Family Dwellings"] },
      { standard: "Townhouse Dwellings", values: ["Multifamily Dwellings and Other Uses"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 100 ft on corner lots.❻ (3) Applicable to the building coverage of the development lot as a whole rather than individual lots under townhouse units. (4) Applicable to buildings on the edges of"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RMF-20": {
    zone: "RMF-20",
    section: "27-4202",
    useColumns: ["Two-Family Dwelling", "Three-Family Dwelling", "Townhouse Dwelling", "Multifamily Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["40.00", "14.00", "20.00", "20.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["No requirement", "No requirement", "No requirement", "7,500", "7,500"] },
      { standard: "Lot width, min. (ft)", values: ["60 (2)(9)", "60 (2)", "20 (7)", "60 (2)", "60 (2)"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["48 (10)", "48", "16", "48", "48"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["35 (3)", "35 (3)", "40 (3)", "40", "60"] },
      { standard: "Green area, min. (% of net lot area)", values: ["No requirement", "No requirement", "50", "60", "No requirement"] },
      { standard: "Front yard depth, min. (ft)", values: ["15", "15", "15", "15", "0"] },
      { standard: "Side yard depth, min. (ft)", values: ["8 (4)", "8 (4)", "8 (4)", "8 (5)", "8 (5)"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20", "20", "20", "20"] },
      { standard: "Principal structure height, max. (ft) (6)", values: ["50", "50", "50", "50", "50"] },
      { standard: "Accessory structure height, max. (ft) (7)(8)", values: ["15", "15", "15", "15", "15"] },
      { standard: "Two- and Three-Family Dwellings", values: ["Townhouse Dwellings"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 80 ft on corner lots.❻ (3) Applicable to the building coverage of the development lot as a whole rather than individual lots under townhouse units. (4) Applicable to buildings on the edges of "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "RMF-48": {
    zone: "RMF-48",
    section: "27-4202",
    useColumns: ["Multifamily Dwelling", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["48.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["7,500", "7,500"] },
      { standard: "Lot width, min. (ft)", values: ["75 (2)", "75 (2)"] },
      { standard: "Lot frontage (width) at front street line, min. (ft)", values: ["60", "60"] },
      { standard: "Lot coverage, max. (% of development lot as a whole)", values: ["60", "60"] },
      { standard: "Front yard depth, min. (ft)", values: ["15", "15"] },
      { standard: "Side yard depth, min. (ft) (both yards total/either yard) (3)", values: ["8", "8"] },
      { standard: "Rear yard depth, min. (ft)", values: ["20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["110 (4)(5)", "110 (5)"] },
      { standard: "Accessory structure height, max. (ft) (6)", values: ["15", "15"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 100 ft on corner lots. ❻ (3) On corner lot, min. side yard depth alongside street = 30 ft. ❼ (4) At least 80% of buildings in the multifamily development must be ≥ 52 ft high. (5) Provided tho"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "CN": {
    zone: "CN",
    section: "27-4203",
    useColumns: ["Single-Family Detached Dwelling", "Two-Family Dwelling", "Townhouse Dwelling, including “Dwelling, Live-Work” uses", "Multifamily Dwelling (2)", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["9.00", "24.00", "12.00", "12.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["4,000", "No requirement", "No requirement", "9,000", "No requirement"] },
      { standard: "Lot width, min. (ft)", values: ["50", "50 (4)", "20", "75", "50"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["60", "65 (3)", "65 (3)", "65", "65"] },
      { standard: "Front yard depth, min. (ft)", values: ["10", "No requirement", "No requirement", "No requirement", "No requirement"] },
      { standard: "Side yard depth, min. (ft)", values: ["5", "No requirement", "No requirement", "No requirement", "No requirement"] },
      { standard: "Rear yard depth , min. (ft)", values: ["15", "15", "15", "20", "20"] },
      { standard: "Principal structure height, max. (ft)", values: ["35", "50", "50", "50", "50"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) The standards in this column apply to multifamily dwellings as stand-alone development. Dwelling units above ground-level nonresidential development shall be subject to the maximum density sta"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "CS": {
    zone: "CS",
    section: "27-4203",
    useColumns: ["Multifamily Dwelling, Artists' Residential Studio, Live-Work Dwelling (2)", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["20.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["7,500", "5,000"] },
      { standard: "Lot width, min. (ft)", values: ["60 (3)", "50"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["40", "No requirement"] },
      { standard: "Front yard depth, min. (ft) (4)", values: ["15", "10"] },
      { standard: "Side yard depth, min. (ft) (4)", values: ["8", "0"] },
      { standard: "Rear yard depth, min. (ft) (4)", values: ["20", "0"] },
      { standard: "Principal structure height, max. (ft)", values: ["50", "50"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) The standards in this column apply to multifamily dwellings, artists' residential studios, and live-work dwellings as stand-alone development. Dwelling units above ground-level nonresidential "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "CGO": {
    zone: "CGO",
    section: "27-4203",
    useColumns: ["Two-Family Dwelling", "Townhouse Dwelling", "Multifamily Dwelling, Artists’ Residential Studio, Live-Work Dwelling (2)", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["40.00", "20.00", "48.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["No requirement", "No requirement", "7,500", "No requirement"] },
      { standard: "Lot width, min. (ft)", values: ["20", "20", "50", "No requirement"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["65 (3)", "65 (3)", "70", "No requirement"] },
      { standard: "Front yard depth, min. (ft)", values: ["10", "10", "10", "0"] },
      { standard: "Side yard depth, min. (ft)", values: ["8 (4)", "8 (4)", "8", "0"] },
      { standard: "Rear yard depth, min. (ft)", values: ["15", "15", "15", "0"] },
      { standard: "Principal structure height, max. (ft) (5) (6)", values: ["50", "50", "86", "No requirement"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) The standards in this column apply to multifamily dwellings, artists’ residential studios, and live-work dwellings as stand-alone development. Dwelling units above ground-level nonresidential "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "IE": {
    zone: "IE",
    section: "27-4203",
    useColumns: ["Multifamily Dwelling, Artists’ Residential Studio, Live-Work Dwelling (2)", "Other Uses Inside the Capital Beltway", "Other Uses Outside the Capital Beltway"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["20.00", "No requirement", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["10,000", "No requirement", "No requirement"] },
      { standard: "Lot width, min. (ft)", values: ["75", "No requirement", "No requirement"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["45", "90", "65 (6)"] },
      { standard: "Green area, min. (% of net lot area)", values: ["25", "10", "30 (6)"] },
      { standard: "Front yard depth, min. (ft)", values: ["10", "10", "10"] },
      { standard: "Side yard depth, min. (ft) (both yards total)", values: ["20", "20", "20"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0/20 (5)", "0/20 (5)", "0/20 (5)"] },
      { standard: "Building separation, min. (ft)", values: ["25 or height of taller building (3), whichever is greater", "25 or height of taller building (3), whichever is greater", "25 or height of taller building (3), whichever is greater"] },
      { standard: "Principal structure height, max. (ft) (4)", values: ["50", "No requirement", "No requirement"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) The standards in this column apply to multifamily dwellings, artists’ residential studios, and live-work dwellings as stand-alone development. Dwelling units above ground-level nonresidential "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "IH": {
    zone: "IH",
    section: "27-4203",
    useColumns: ["Multifamily Dwelling, Artists’ Residential Studio, Live-Work Dwelling (2)", "Other Uses"],
    rows: [
      { standard: "Density, max. (du/ac of net lot area)", values: ["12.00", "No requirement"] },
      { standard: "Net lot area, min. (sf)", values: ["10,000", "10,000"] },
      { standard: "Lot width, min. (ft)", values: ["75", "75"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["No requirement", "No requirement"] },
      { standard: "Green area, min. (% of net lot area) (5)", values: ["10", "10"] },
      { standard: "Front yard depth, min. (ft)", values: ["25", "25"] },
      { standard: "Side yard depth, min. (ft) (both yards total)", values: ["30", "30"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0/20 (4)", "0/20 (4)"] },
      { standard: "Principal structure height, max. (ft) (3)", values: ["No requirement", "No requirement"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) The standards in this column apply to multifamily dwellings, artists’ residential studios, and live-work dwellings as stand-alone development. Dwelling units above ground-level nonresidential "],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "NAC": {
    zone: "NAC",
    section: "27-4204",
    useColumns: ["All Uses"],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["200 | 600"] },
      { standard: "Lot area, min. (sf)", values: ["5,000 (2)"] },
      { standard: "Lot width, min. (ft)", values: ["50 (3)"] },
      { standard: "Density, min. | max. (du/ac of net lot area) (4)", values: ["10.00 | 90.00"] },
      { standard: "Floor area ratio (FAR), min. | max. (5)", values: ["0.25 | 2.0"] },
      { standard: "Lot coverage, min. | max. (% of net lot area)", values: ["40 | 100"] },
      { standard: "Build-to line, min. | max. (ft) (6)(7)", values: ["15 | 35"] },
      { standard: "Building width in build-to zone, min. (% of lot width) (7)(8)", values: ["60"] },
      { standard: "Front yard depth, min. (ft)", values: ["0"] },
      { standard: "Side yard depth, min. (ft)", values: ["0"] },
      { standard: "Rear yard depth, min. (ft)", values: ["0"] },
      { standard: "Building façade fenestration/transparency, min. (% of street-level façade area)", values: ["Abutting or facing a street frontage or pedestrian way", "40"] },
      { standard: "Facing a transit station or public gathering space", values: ["35"] },
      { standard: "Principal structure height, min. |max. (ft)", values: ["No requirement | 60"] },
    ],
    notes: ["NOTES: du/ac = dwelling units per acre; sf = square feet; ft = feet (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) 1,200 sf for townhouse lots. (3) 18 ft for townhouse lots. (4) Applicable to residential development and the residential component of mixed-use development. (5) Applicable to nonresidential de"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "R-PD": {
    zone: "R-PD",
    section: "27-4300",
    useColumns: [],
    rows: [
      { standard: "Density, min. (du/net lot areas)", values: ["All Uses", "1.00"] },
      { standard: "Density, max. (du/net lot area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
    ],
    notes: ["NOTES: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards."],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "NAC-PD": {
    zone: "NAC-PD",
    section: "27-4300",
    useColumns: ["All Uses"],
    rows: [
      { standard: "Block length, min. | max. (ft)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Density, min. (du/ net lot area) (2)", values: ["10.00"] },
      { standard: "Lot coverage, max. (% of net lot area)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
      { standard: "Building façade transparency, min. (% of street-level façade area) (6)", values: ["Abutting or facing a street frontage or pedestrian way"] },
    ],
    notes: ["NOTES: sf = square feet; ft. = feet; du = dwelling unit; ac = acre (1) See measurement rules and allowed exceptions in Section 27-2200, Measurement and Exceptions of Intensity and Dimensional Standards. (2) Applicable to residential development and the residential component of mixed-use development. (3) Applicable to nonresidential development. (4) The area between the minimum and maximum build-to"],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "MU-PD": {
    zone: "MU-PD",
    section: "27-4300",
    useColumns: ["All Uses"],
    rows: [
      { standard: "Lot area, min. | max. (sf.)", values: ["To be established in PD Basic Plan and PD Conditions of Approval (see Section 27-4301(d))"] },
      { standard: "Density, min. (du/net lot area) (2)", values: ["6.00"] },
      { standard: "Density, max. (net lot area) (2)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
    ],
    notes: [],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
  "IE-PD": {
    zone: "IE-PD",
    section: "27-4300",
    useColumns: ["All Uses"],
    rows: [
      { standard: "Density, max. (du/net lot area) (2)", values: ["12.00"] },
      { standard: "Lot area, min. | max. (sf.)", values: ["To be established in PD Basic Plan (see Section 27-4301(d))"] },
    ],
    notes: [],
    source: { publication: PUBLICATION, url: VIEWER, effectiveDate: EFFECTIVE,
      retrievedAt: RETRIEVED, extraction: 'machine', verifiedBy: null, verifiedAt: null },
  },
}

/**
 * Zones whose ordinance tables use NESTED column headers (Core/Edge crossed with
 * use type, and RTO-L and RTO-H sharing one table). A flat parser mis-assigns
 * those columns, and a mis-assigned column is a wrong buildable envelope, so
 * they are excluded rather than guessed. These need manual transcription.
 *
 * Also excluded: the Sec. 27-4205 "Other Base Zones" (RMH, LCD, LMXC, LMUTC)
 * publish no dimensional table — legacy comprehensive-design zones are governed
 * by their prior approved plans.
 */
export const PG_ZONES_REQUIRING_MANUAL_TRANSCRIPTION: readonly string[] = [
  "LTO",
  "LTO-PD",
  "RTO-H",
  "RTO-PD",
  "TAC",
  "TAC-PD",
  "TAC-C", "TAC-E", "LTO-C", "LTO-E", "RTO-L-C", "RTO-L-E", "RTO-H-C", "RTO-H-E",
  "RMH", "LCD", "LMXC", "LMUTC",
]
