import { RolePermissionSeed } from "../types";

export const rolePermissionSeeds: RolePermissionSeed[] = [
  {
    code: "homeowner",
    version: "1.0.0",
    status: "active",
    source: "portal-owner",
    roleName: "Homeowner / Project Owner",
    description: "End-user who owns a property and wants design, permits, construction, or PM services.",
    portalAccess: ["portal-owner", "web-main"],
    requiresVerification: false,
    permissions: [
      "session.create",
      "task.create",
      "task.read.own",
      "project.read.own",
      "project.create",
      "document.upload.own",
      "milestone.read.own",
      "milestone.approve.own",
      "payment.initiate.own",
      "message.send",
      "concept.purchase",
      "permit.request",
    ],
  },
  {
    code: "developer",
    version: "1.0.0",
    status: "active",
    source: "portal-developer",
    roleName: "Developer / Investor",
    description: "Real estate developer or investor running multifamily, mixed-use, or land deals.",
    portalAccess: ["portal-developer", "web-main"],
    requiresVerification: false,
    permissions: [
      "session.create",
      "task.create",
      "task.read.own",
      "project.read.own",
      "project.create",
      "document.upload.own",
      "feasibility.request",
      "pro_forma.view.own",
      "capital_stack.view.own",
      "milestone.read.own",
      "payment.initiate.own",
      "message.send",
    ],
  },
  {
    code: "contractor",
    version: "1.0.0",
    status: "active",
    source: "portal-contractor",
    roleName: "General Contractor",
    description: "Licensed contractor receiving bids, submitting draws, and managing construction.",
    portalAccess: ["portal-contractor"],
    requiresVerification: true,
    permissions: [
      "project.read.assigned",
      "milestone.read.assigned",
      "milestone.submit_draw",
      "document.upload.assigned",
      "message.send",
      "bid.submit",
      "bid.view.own",
      "payment.view.own",
    ],
  },
  {
    code: "architect",
    version: "1.0.0",
    status: "active",
    source: "m-architect",
    roleName: "Architect",
    description: "Licensed architect reviewing designs, uploading drawings, and signing off on submittals.",
    portalAccess: ["m-architect"],
    requiresVerification: true,
    permissions: [
      "project.read.assigned",
      "document.upload.assigned",
      "document.review",
      "design.approve",
      "permit.review",
      "milestone.read.assigned",
      "message.send",
    ],
  },
  {
    code: "engineer",
    version: "1.0.0",
    status: "active",
    source: "m-engineer",
    roleName: "Engineer",
    description: "Structural, MEP, or civil engineer reviewing drawings and providing stamped calculations.",
    portalAccess: ["m-engineer"],
    requiresVerification: true,
    permissions: [
      "project.read.assigned",
      "document.upload.assigned",
      "document.review",
      "calculation.submit",
      "message.send",
    ],
  },
  {
    code: "lender",
    version: "1.0.0",
    status: "active",
    source: "m-finance-trust",
    roleName: "Lender / Finance Reviewer",
    description: "Construction lender or draw inspector reviewing milestone status and disbursement.",
    portalAccess: ["m-finance-trust"],
    requiresVerification: true,
    permissions: [
      "project.read.assigned",
      "milestone.read.assigned",
      "draw.approve",
      "draw.reject",
      "document.read.assigned",
      "lender_report.view",
      "message.send",
    ],
  },
  {
    code: "internal_operator",
    version: "1.0.0",
    status: "active",
    source: "command-center",
    roleName: "KeaCore Operator",
    description: "Internal Kealee team member supervising agent runs, approvals, and escalations.",
    portalAccess: ["command-center"],
    requiresVerification: false,
    permissions: [
      "session.read",
      "session.update",
      "task.read",
      "task.retry",
      "task.cancel",
      "plan.read",
      "approval.decide",
      "tool.execute.manual",
      "risk.override",
      "agent.re_route",
      "note.inject",
      "mode.change",
      "message.send",
    ],
  },
  {
    code: "admin",
    version: "1.0.0",
    status: "active",
    source: "admin-console",
    roleName: "Platform Admin",
    description: "Kealee platform admin with full access to users, orgs, projects, and system config.",
    portalAccess: ["admin-console", "command-center"],
    requiresVerification: false,
    permissions: [
      "*",
    ],
  },
  {
    code: "finance_reviewer",
    version: "1.0.0",
    status: "active",
    source: "m-finance-trust",
    roleName: "Finance Reviewer",
    description: "Internal Kealee finance/trust reviewer who validates draw requests and escrow conditions.",
    portalAccess: ["m-finance-trust", "command-center"],
    requiresVerification: false,
    permissions: [
      "project.read",
      "milestone.read",
      "draw.review",
      "draw.approve",
      "draw.reject",
      "escrow.view",
      "lender_report.generate",
      "document.read",
    ],
  },
  {
    code: "permit_reviewer",
    version: "1.0.0",
    status: "active",
    source: "m-permits-inspections",
    roleName: "Permit Reviewer",
    description: "Internal Kealee permit specialist who reviews permit readiness and submittals.",
    portalAccess: ["m-permits-inspections", "command-center"],
    requiresVerification: false,
    permissions: [
      "project.read",
      "document.read",
      "permit.review",
      "permit.submit",
      "permit.track",
      "permit.comment_respond",
      "message.send",
    ],
  },
];
