// apps/m-marketplace/app/network/page.tsx
// Construction Network Search & Browse Page

import type { Metadata } from 'next';
import { NetworkSearchClient } from '../../components/NetworkSearchClient';

export const dynamic = 'force-static';

export const metadata: Metadata = {
  title: 'Kealee Construction Network | Find Contractors & Professionals',
  description:
    'Search verified contractors, architects, engineers, and construction professionals in the DC-Baltimore corridor. Fair bid rotation. Licensed & insured.',
  openGraph: {
    title: 'Kealee Construction Network',
    description:
      'Find the right construction professional for your project. Verified, licensed, and insured.',
    url: 'https://kealee.com/network',
    siteName: 'Kealee',
    images: [
      {
        url: '/og-network.png',
        width: 1200,
        height: 630,
        alt: 'Kealee Construction Network',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
};

// Mock profiles data
const mockProfiles = [
  {
    id: '1',
    slug: 'precision-build-co',
    businessName: 'Precision Build Co.',
    ownerName: 'Marcus Johnson',
    type: 'General Contractor',
    trades: ['General Construction', 'Renovation', 'Additions', 'Custom Homes'],
    rating: 4.9,
    reviews: 127,
    location: 'Bethesda, MD',
    distance: '8 mi',
    stats: { projectsCompleted: 245, yearsExperience: 18, responseTime: '2h' },
    badges: ['Top Rated', 'Verified', 'Fast Response'],
    availability: 'available' as const,
    ctaHref: '/network/precision-build-co',
  },
  {
    id: '2',
    slug: 'capital-electric',
    businessName: 'Capital Electric Services',
    ownerName: 'Sarah Chen',
    type: 'Specialty Contractor',
    trades: ['Electrical', 'Panel Upgrades', 'EV Charging', 'Smart Home', 'Commercial'],
    rating: 4.8,
    reviews: 89,
    location: 'Silver Spring, MD',
    distance: '5 mi',
    stats: { projectsCompleted: 312, yearsExperience: 12, responseTime: '1h' },
    badges: ['Licensed Master', 'Fast Response'],
    availability: 'available' as const,
    ctaHref: '/network/capital-electric',
  },
  {
    id: '3',
    slug: 'harbor-view-architects',
    businessName: 'Harbor View Architects',
    ownerName: 'David Park',
    type: 'Architect',
    trades: ['Residential', 'Commercial', 'Historic', 'Sustainable Design'],
    rating: 4.9,
    reviews: 64,
    location: 'Baltimore, MD',
    distance: '35 mi',
    stats: { projectsCompleted: 89, yearsExperience: 22, responseTime: '4h' },
    badges: ['AIA Member', 'LEED AP', 'Top Rated'],
    availability: 'busy' as const,
    ctaHref: '/network/harbor-view-architects',
  },
  {
    id: '4',
    slug: 'dc-plumbing-masters',
    businessName: 'DC Plumbing Masters',
    ownerName: 'James Wilson',
    type: 'Specialty Contractor',
    trades: ['Plumbing', 'Water Heaters', 'Gas Lines', 'Bathroom Remodel'],
    rating: 4.7,
    reviews: 203,
    location: 'Washington, DC',
    distance: '2 mi',
    stats: { projectsCompleted: 567, yearsExperience: 25, responseTime: '30m' },
    badges: ['Emergency Service', 'Licensed Master'],
    availability: 'available' as const,
    ctaHref: '/network/dc-plumbing-masters',
  },
  {
    id: '5',
    slug: 'metro-hvac-solutions',
    businessName: 'Metro HVAC Solutions',
    ownerName: 'Michael Torres',
    type: 'Specialty Contractor',
    trades: ['HVAC', 'Heating', 'Air Conditioning', 'Ductwork', 'Mini-Splits'],
    rating: 4.8,
    reviews: 156,
    location: 'Arlington, VA',
    distance: '6 mi',
    stats: { projectsCompleted: 423, yearsExperience: 15, responseTime: '2h' },
    badges: ['NATE Certified', 'Energy Star Partner'],
    availability: 'available' as const,
    ctaHref: '/network/metro-hvac-solutions',
  },
  {
    id: '6',
    slug: 'coastal-roofing',
    businessName: 'Coastal Roofing & Exteriors',
    ownerName: 'Amanda Roberts',
    type: 'Specialty Contractor',
    trades: ['Roofing', 'Siding', 'Gutters', 'Windows', 'Storm Damage'],
    rating: 4.6,
    reviews: 178,
    location: 'Annapolis, MD',
    distance: '28 mi',
    stats: { projectsCompleted: 389, yearsExperience: 20, responseTime: '3h' },
    badges: ['GAF Master Elite', 'Storm Specialist'],
    availability: 'busy' as const,
    ctaHref: '/network/coastal-roofing',
  },
  {
    id: '7',
    slug: 'nova-concrete',
    businessName: 'NoVA Concrete & Masonry',
    ownerName: 'Carlos Rodriguez',
    type: 'Specialty Contractor',
    trades: ['Concrete', 'Masonry', 'Foundations', 'Driveways', 'Patios'],
    rating: 4.9,
    reviews: 94,
    location: 'Fairfax, VA',
    distance: '12 mi',
    stats: { projectsCompleted: 234, yearsExperience: 28, responseTime: '4h' },
    badges: ['Commercial Certified', 'Verified'],
    availability: 'available' as const,
    ctaHref: '/network/nova-concrete',
  },
  {
    id: '8',
    slug: 'green-structural-eng',
    businessName: 'Green Structural Engineering',
    ownerName: 'Dr. Emily Nguyen',
    type: 'Engineer',
    trades: ['Structural', 'Seismic', 'Foundation', 'Steel', 'Residential'],
    rating: 5.0,
    reviews: 47,
    location: 'Rockville, MD',
    distance: '15 mi',
    stats: { projectsCompleted: 156, yearsExperience: 18, responseTime: '1d' },
    badges: ['PE Licensed', 'LEED AP', 'Top Rated'],
    availability: 'available' as const,
    ctaHref: '/network/green-structural-eng',
  },
  {
    id: '9',
    slug: 'dmv-painting',
    businessName: 'DMV Painting Professionals',
    ownerName: 'Kevin Brown',
    type: 'Specialty Contractor',
    trades: ['Interior Painting', 'Exterior Painting', 'Cabinet Refinishing', 'Wallpaper'],
    rating: 4.7,
    reviews: 312,
    location: 'Columbia, MD',
    distance: '20 mi',
    stats: { projectsCompleted: 678, yearsExperience: 14, responseTime: '2h' },
    badges: ['Fast Turnaround', 'Eco-Friendly'],
    availability: 'available' as const,
    ctaHref: '/network/dmv-painting',
  },
];

export default function NetworkSearchPage() {
  return <NetworkSearchClient initialProfiles={mockProfiles} />;
}
