/**
 * Marketing compatibility facade.
 *
 * All amounts are sourced from @kealee/core-rules. Keep this module only so
 * existing campaigns can migrate without maintaining a second price book.
 */
export {
  ADU_BUNDLE_PRICE,
  CONCEPT_BATH_ADVANCED,
  CONCEPT_BATH_FULL,
  CONCEPT_BATH_PRICE,
  CONCEPT_COMMERCIAL_PRICE,
  CONCEPT_DEVELOPER_PRICE,
  CONCEPT_EXTERIOR_PRICE,
  CONCEPT_INTERIOR_RENO_PRICE,
  CONCEPT_KITCHEN_ADVANCED,
  CONCEPT_KITCHEN_FULL,
  CONCEPT_KITCHEN_PRICE,
  CONCEPT_LANDSCAPE_PRICE,
  CONCEPT_START_PRICE,
  CONCEPT_TIER_PRICES,
  CONCEPT_WHOLE_HOME_ADVANCED,
  CONCEPT_WHOLE_HOME_FULL,
  CONCEPT_WHOLE_HOME_PRICE,
  CONTRACTOR_MATCH_PRICE,
  DESIGN_ESTIMATE_PERMIT_BUNDLE,
  ESTIMATION_CERTIFIED_PRICE,
  ESTIMATION_PRICE,
  PERMIT_BASIC_PRICE,
  PERMIT_PREMIUM_PRICE,
  PERMIT_STANDARD_PRICE,
  PM_ADVISORY_PRICE,
  formatPrice,
  startingAt,
} from '@kealee/core-rules'
