import { WorkflowTemplateSeed } from "../types";

export const workflowTemplateSeeds: WorkflowTemplateSeed[] = [
  {
    code: "wf_homeowner_concept_v1",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    name: "Homeowner Concept Workflow",
    appliesToIntents: ["design_concept", "renovation", "adu"],
    mode: "assisted",
    steps: [
      { order: 1, code: "create_project", type: "tool", target: "create_project", required: true, approvalRequired: false, stopOnFailure: true },
      { order: 2, code: "check_zoning", type: "tool", target: "check_zoning", required: false, approvalRequired: false },
      { order: 3, code: "run_feasibility", type: "tool", target: "run_feasibility", required: true, approvalRequired: false },
      { order: 4, code: "generate_concept_brief", type: "tool", target: "generate_concept_brief", required: true, approvalRequired: false },
      { order: 5, code: "create_estimate", type: "tool", target: "create_estimate", required: true, approvalRequired: false },
      { order: 6, code: "present_upgrade", type: "approval", target: "request_human_approval", required: true, approvalRequired: true },
    ],
    successCriteria: ["project_created", "concept_brief_generated", "estimate_generated", "next_paid_step_recommended"],
  },
  {
    code: "wf_permit_only_v1",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    name: "Permit-Only Review Workflow",
    appliesToIntents: ["permit_only"],
    mode: "assisted",
    steps: [
      { order: 1, code: "create_project", type: "tool", target: "create_project", required: true, approvalRequired: false, stopOnFailure: true },
      { order: 2, code: "check_zoning", type: "tool", target: "check_zoning", required: true, approvalRequired: false, stopOnFailure: true },
      { order: 3, code: "generate_concept_brief", type: "tool", target: "generate_concept_brief", required: false, approvalRequired: false },
      { order: 4, code: "present_permit_options", type: "approval", target: "request_human_approval", required: true, approvalRequired: true },
    ],
    successCriteria: ["project_created", "zoning_checked", "permit_path_recommended"],
  },
  {
    code: "wf_feasibility_light_v1",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    name: "Light Feasibility Workflow",
    appliesToIntents: ["feasibility_light"],
    mode: "assisted",
    steps: [
      { order: 1, code: "create_project", type: "tool", target: "create_project", required: true, approvalRequired: false, stopOnFailure: true },
      { order: 2, code: "check_zoning", type: "tool", target: "check_zoning", required: false, approvalRequired: false },
      { order: 3, code: "run_feasibility", type: "tool", target: "run_feasibility", required: true, approvalRequired: false },
      { order: 4, code: "create_estimate", type: "tool", target: "create_estimate", required: true, approvalRequired: false },
      { order: 5, code: "recommend_next_step", type: "approval", target: "request_human_approval", required: true, approvalRequired: true },
    ],
    successCriteria: ["feasibility_assessed", "estimate_generated", "next_paid_step_recommended"],
  },
  {
    code: "wf_developer_feasibility_v1",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    name: "Developer Feasibility Workflow",
    appliesToIntents: ["developer_feasibility"],
    mode: "assisted",
    steps: [
      { order: 1, code: "create_project", type: "tool", target: "create_project", required: true, approvalRequired: false, stopOnFailure: true },
      { order: 2, code: "check_zoning", type: "tool", target: "check_zoning", required: true, approvalRequired: false, stopOnFailure: true },
      { order: 3, code: "run_feasibility", type: "tool", target: "run_feasibility", required: true, approvalRequired: false },
      { order: 4, code: "generate_concept_brief", type: "tool", target: "generate_concept_brief", required: false, approvalRequired: false },
      { order: 5, code: "create_estimate", type: "tool", target: "create_estimate", required: true, approvalRequired: false },
      { order: 6, code: "present_developer_packages", type: "approval", target: "request_human_approval", required: true, approvalRequired: true },
    ],
    successCriteria: ["zoning_checked", "feasibility_assessed", "estimate_generated", "developer_package_recommended"],
  },
  {
    code: "wf_new_build_v1",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    name: "New Build Workflow",
    appliesToIntents: ["new_build"],
    mode: "assisted",
    steps: [
      { order: 1, code: "create_project", type: "tool", target: "create_project", required: true, approvalRequired: false, stopOnFailure: true },
      { order: 2, code: "check_zoning", type: "tool", target: "check_zoning", required: true, approvalRequired: false, stopOnFailure: true },
      { order: 3, code: "run_feasibility", type: "tool", target: "run_feasibility", required: true, approvalRequired: false },
      { order: 4, code: "generate_concept_brief", type: "tool", target: "generate_concept_brief", required: true, approvalRequired: false },
      { order: 5, code: "create_estimate", type: "tool", target: "create_estimate", required: true, approvalRequired: false },
      { order: 6, code: "approval_gate", type: "approval", target: "request_human_approval", required: true, approvalRequired: true },
    ],
    successCriteria: ["project_created", "zoning_verified", "feasibility_assessed", "concept_brief_generated", "estimate_generated"],
  },
  {
    code: "wf_estimate_only_v1",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    name: "Estimate Only Workflow",
    appliesToIntents: ["estimate_only"],
    mode: "autonomous",
    steps: [
      { order: 1, code: "create_project", type: "tool", target: "create_project", required: true, approvalRequired: false, stopOnFailure: true },
      { order: 2, code: "create_estimate", type: "tool", target: "create_estimate", required: true, approvalRequired: false },
    ],
    successCriteria: ["estimate_generated"],
  },
  {
    code: "wf_contractor_match_v1",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    name: "Contractor Match Workflow",
    appliesToIntents: ["contractor_match"],
    mode: "assisted",
    steps: [
      { order: 1, code: "create_project", type: "tool", target: "create_project", required: true, approvalRequired: false, stopOnFailure: true },
      { order: 2, code: "create_estimate", type: "tool", target: "create_estimate", required: false, approvalRequired: false },
      { order: 3, code: "assign_contractor", type: "tool", target: "assign_contractor", required: true, approvalRequired: true, stopOnFailure: true },
    ],
    successCriteria: ["project_created", "contractor_matched"],
  },
  {
    code: "wf_construction_execution_v1",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    name: "Construction Execution Workflow",
    appliesToIntents: ["construction_execution"],
    mode: "assisted",
    steps: [
      { order: 1, code: "update_project_context", type: "tool", target: "update_project_context", required: true, approvalRequired: false },
      { order: 2, code: "create_milestone_schedule", type: "tool", target: "create_milestone_schedule", required: false, approvalRequired: false },
    ],
    successCriteria: ["project_updated", "milestones_tracked"],
  },
  {
    code: "wf_milestone_payment_v1",
    version: "1.0.0",
    status: "active",
    source: "kealee_platform",
    name: "Milestone Payment Workflow",
    appliesToIntents: ["payment_disbursement"],
    mode: "operator",
    steps: [
      { order: 1, code: "approval_gate", type: "approval", target: "request_human_approval", required: true, approvalRequired: true, stopOnFailure: true },
      { order: 2, code: "create_checkout", type: "tool", target: "create_checkout", required: true, approvalRequired: true },
    ],
    successCriteria: ["milestone_approved", "payment_released"],
  },
];
