import { ServiceOfferingSeed } from "../types";

export const serviceOfferingSeeds: ServiceOfferingSeed[] = [
  // ── Concept Engine ──────────────────────────────────────────────────────────
  { code: "exterior_concept_essential", version: "1.0.0", status: "active", source: "stripe", name: "Essential Exterior Concept", category: "design", description: "3 exterior renders, design brief, permit path summary.", basePrice: 299, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_DESIGN_CONCEPT_VALIDATION", includedOutputs: ["exterior_renders_3", "design_brief", "permit_path_summary"], requiresApproval: true, availableForIntents: ["design_concept", "renovation", "adu"], upsellTargets: ["exterior_concept_professional", "permit_path_review"], deliveryDays: { min: 3, max: 5 } },
  { code: "exterior_concept_professional", version: "1.0.0", status: "active", source: "stripe", name: "Professional Exterior Concept", category: "design", description: "6 exterior + 2 landscape renders, full brief, PM review.", basePrice: 599, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_DESIGN_ADVANCED", includedOutputs: ["exterior_renders_6", "landscape_renders_2", "design_brief_full", "permit_path", "pm_review"], requiresApproval: true, availableForIntents: ["design_concept", "renovation", "adu", "new_build"], upsellTargets: ["permit_path_review", "full_permit_coordination"], deliveryDays: { min: 2, max: 3 } },
  { code: "exterior_concept_premium", version: "1.0.0", status: "active", source: "stripe", name: "Premium Exterior Concept", category: "design", description: "8 exterior + 4 landscape renders, material specs, revision round.", basePrice: 999, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_DESIGN_FULL", includedOutputs: ["exterior_renders_8", "landscape_renders_4", "material_spec_sheet", "permit_path_analysis", "pm_review", "revision_round_1"], requiresApproval: true, availableForIntents: ["design_concept", "renovation", "new_build"], upsellTargets: ["full_permit_coordination", "architect_handoff"], deliveryDays: { min: 1, max: 2 } },
  { code: "garden_concept_basic", version: "1.0.0", status: "active", source: "stripe", name: "AI Garden Concept", category: "design", description: "3 garden layouts, raised bed plan, irrigation overview, planting guide.", basePrice: 395, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_GARDEN_BASIC", includedOutputs: ["garden_layouts_3", "raised_bed_plan", "irrigation_overview", "planting_guide"], requiresApproval: true, availableForIntents: ["design_concept"], upsellTargets: ["garden_concept_advanced"], deliveryDays: { min: 5, max: 7 } },
  { code: "garden_concept_advanced", version: "1.0.0", status: "active", source: "stripe", name: "Advanced Garden Design", category: "design", description: "Plant lists, irrigation specs, 3D views, seasonal calendar.", basePrice: 750, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_GARDEN_ADVANCED", includedOutputs: ["garden_3d_views", "plant_list_detailed", "irrigation_specs", "seasonal_calendar", "revision_rounds_3"], requiresApproval: true, availableForIntents: ["design_concept"], upsellTargets: ["garden_concept_full", "contractor_match"], deliveryDays: { min: 5, max: 7 } },
  { code: "interior_concept_basic", version: "1.0.0", status: "active", source: "stripe", name: "AI Interior Concept", category: "design", description: "3 layout options, finish direction, rough cost range.", basePrice: 395, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_INTERIOR_BASIC", includedOutputs: ["interior_layouts_3", "finish_direction", "rough_cost_range"], requiresApproval: true, availableForIntents: ["design_concept", "renovation"], upsellTargets: ["interior_concept_advanced"], deliveryDays: { min: 5, max: 7 } },
  { code: "whole_home_concept_basic", version: "1.0.0", status: "active", source: "stripe", name: "AI Whole Home Concept", category: "design", description: "Floor plan direction, scope, material palette, rough cost range.", basePrice: 585, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_WHOLE_HOME_BASIC", includedOutputs: ["floor_plan_direction", "scope_summary", "material_palette", "rough_cost_range"], requiresApproval: true, availableForIntents: ["design_concept", "renovation", "new_build"], upsellTargets: ["whole_home_concept_advanced"], deliveryDays: { min: 5, max: 7 } },

  // ── Feasibility & Developer ─────────────────────────────────────────────────
  { code: "developer_feasibility", version: "1.0.0", status: "active", source: "stripe", name: "Full Feasibility Study", category: "feasibility", description: "Pro forma, IRR analysis, scenario modeling, go/no-go recommendation.", basePrice: 4500, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_DEV_FEASIBILITY", includedOutputs: ["pro_forma", "irr_analysis", "scenario_modeling", "go_nogo_recommendation"], requiresApproval: true, availableForIntents: ["developer_feasibility", "new_build"], upsellTargets: ["capital_stack_modeling", "entitlement_support"], deliveryDays: { min: 5, max: 10 } },
  { code: "pro_forma_analysis", version: "1.0.0", status: "active", source: "stripe", name: "Pro Forma Analysis", category: "feasibility", description: "Unit mix, cost/revenue assumptions, sensitivity analysis.", basePrice: 2500, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_DEV_PROFORMA", includedOutputs: ["pro_forma_model", "sensitivity_analysis"], requiresApproval: true, availableForIntents: ["developer_feasibility"], upsellTargets: ["developer_feasibility", "capital_stack_modeling"], deliveryDays: { min: 3, max: 7 } },

  // ── Permits ─────────────────────────────────────────────────────────────────
  { code: "permit_path_review", version: "1.0.0", status: "active", source: "stripe", name: "Permit Path Review", category: "permits", description: "Review project scope + jurisdiction rules, output permit path summary and checklist.", basePrice: 325, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_PERMIT_SIMPLE", includedOutputs: ["permit_path_summary", "required_docs_checklist", "jurisdiction_notes"], requiresApproval: true, availableForIntents: ["permit_only", "renovation", "adu", "design_concept"], upsellTargets: ["permit_prep", "full_permit_coordination"], deliveryDays: { min: 2, max: 5 } },
  { code: "permit_prep", version: "1.0.0", status: "active", source: "stripe", name: "Permit Prep Package", category: "permits", description: "Prepare permit application, organize docs, coordinate with owner/contractor.", basePrice: 500, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_PERMIT_PACKAGE", includedOutputs: ["completed_permit_application", "document_compilation", "submittal_checklist"], requiresApproval: true, availableForIntents: ["permit_only"], upsellTargets: ["full_permit_coordination"], deliveryDays: { min: 3, max: 7 } },
  { code: "full_permit_coordination", version: "1.0.0", status: "active", source: "stripe", name: "Full Permit Coordination", category: "permits", description: "End-to-end permit management: submit, track, respond to comments, get approval.", basePrice: 1000, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_PERMIT_COORDINATION", includedOutputs: ["permit_submission", "comment_response", "approval_tracking", "weekly_status_updates"], requiresApproval: true, availableForIntents: ["permit_only", "renovation", "adu", "new_build"], upsellTargets: ["pm_package_a"], deliveryDays: { min: 30, max: 180 } },

  // ── Estimation ──────────────────────────────────────────────────────────────
  { code: "estimate_basic", version: "1.0.0", status: "active", source: "stripe", name: "Basic Estimate", category: "estimate", description: "Detailed estimate for projects up to $100K.", basePrice: 500, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_ESTIMATE_DETAILED", includedOutputs: ["line_item_estimate", "csi_breakdown", "caveats"], requiresApproval: true, availableForIntents: ["estimate_only", "renovation"], upsellTargets: ["full_permit_coordination", "contractor_match"], deliveryDays: { min: 3, max: 5 } },

  // ── PM Packages (recurring) ─────────────────────────────────────────────────
  { code: "pm_package_a", version: "1.0.0", status: "active", source: "stripe", name: "PM Package A — Solo GC", category: "pm_managed", description: "5–10 hrs/week, 1 project, weekly reports. For solo general contractors.", basePrice: 1750, currency: "USD", billingType: "subscription", stripePriceEnvKey: "STRIPE_PRICE_PACKAGE_A", includedOutputs: ["weekly_pm_reports", "milestone_tracking", "field_coordination"], requiresApproval: true, availableForIntents: ["construction_execution"], upsellTargets: ["pm_package_b"], },
  { code: "pm_package_b", version: "1.0.0", status: "active", source: "stripe", name: "PM Package B — Growing Team", category: "pm_managed", description: "15–20 hrs/week, 3 projects, priority support.", basePrice: 3750, currency: "USD", billingType: "subscription", stripePriceEnvKey: "STRIPE_PRICE_PACKAGE_B", includedOutputs: ["weekly_pm_reports", "multi_project_tracking", "priority_support", "milestone_tracking"], requiresApproval: true, availableForIntents: ["construction_execution"], upsellTargets: ["pm_package_c"], },

  // ── Marketplace ─────────────────────────────────────────────────────────────
  { code: "contractor_lead", version: "1.0.0", status: "active", source: "stripe", name: "Contractor Lead", category: "marketplace", description: "Qualified lead delivered to a verified contractor.", basePrice: 50, currency: "USD", billingType: "one_time", stripePriceEnvKey: "STRIPE_PRICE_LISTING_BASIC", includedOutputs: ["qualified_lead_details", "project_scope_summary"], requiresApproval: false, availableForIntents: ["contractor_match"], upsellTargets: ["contractor_growth_package"] },
  { code: "contractor_growth_package", version: "1.0.0", status: "active", source: "stripe", name: "Contractor Growth Package", category: "marketplace", description: "Premium contractor listing + priority leads.", basePrice: 299, currency: "USD", billingType: "subscription", stripePriceEnvKey: "STRIPE_PRICE_LISTING_PRO", includedOutputs: ["premium_listing", "priority_leads", "kealee_verified_badge"], requiresApproval: true, availableForIntents: ["contractor_match"], upsellTargets: ["pm_package_a"] },

  // ── Finance / Trust ─────────────────────────────────────────────────────────
  { code: "finance_trust_onboarding", version: "1.0.0", status: "active", source: "kealee_platform", notes: "TODO: wire to finance-trust module", name: "Escrow / Finance Trust Onboarding", category: "finance", description: "Set up escrow account, lender portal access, and draw schedule for a project.", basePrice: 0, currency: "USD", billingType: "custom_quote", includedOutputs: ["escrow_account_setup", "lender_portal_access", "draw_schedule_template"], requiresApproval: true, availableForIntents: ["payment_disbursement", "construction_execution"], upsellTargets: [] },
];
