import { ServiceOfferingSeed } from "../types";

export const serviceOfferingSeeds: ServiceOfferingSeed[] = [
  {
    code: "ai_concept_basic",
    version: "1.0.0",
    status: "active",
    source: "kealee_pricing_strategy",
    notes: "Exterior concept = STRIPE_PRICE_DESIGN_CONCEPT_VALIDATION. Garden/interior/whole-home have separate STRIPE_PRICE_* keys.",
    name: "AI Concept Package",
    category: "design",
    description: "Early concept package for qualified residential or light-scope projects, including concept brief and basic buildability signal.",
    basePrice: 149,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_DESIGN_CONCEPT_VALIDATION",
    stripePriceKey: "STRIPE_PRICE_DESIGN_CONCEPT_VALIDATION",
    includedOutputs: ["concept_brief", "basic_buildability_review", "next_step_recommendation"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation"],
    qualificationRules: ["Best for early stage", "Not final construction documents", "Escalate complex scopes"],
    upsellTargets: ["feasibility_light_package", "permit_path_review"],
    deliveryWorkflowCode: "wf_homeowner_concept_v1"
  },
  {
    code: "feasibility_light_package",
    version: "1.0.0",
    status: "draft",
    notes: "TODO_VERIFY: No direct Stripe price found for standalone feasibility light — may be bundled or custom quote. Add Stripe product when ready.",
    name: "Feasibility Light",
    category: "feasibility",
    description: "Quick zoning-aware viability review with constraints, rough massing fit, and early risk notes.",
    basePrice: 295,
    currency: "USD",
    billingType: "one_time",
    includedOutputs: ["feasibility_summary", "risk_flags", "recommendation_path"],
    requiresApproval: true,
    availableForIntents: ["feasibility_light", "design_concept", "new_build", "developer_feasibility"],
    qualificationRules: ["Requires address or parcel", "Advisory only"],
    upsellTargets: ["permit_path_review", "developer_advisory"]
  },
  {
    code: "estimate_package",
    version: "1.0.0",
    status: "active",
    name: "Estimate Package",
    category: "estimate",
    description: "Rough order-of-magnitude estimate with scope assumptions and confidence notes.",
    basePrice: 249,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_ESTIMATE_DETAILED",
    stripePriceKey: "STRIPE_PRICE_ESTIMATE_DETAILED",
    includedOutputs: ["estimate_range", "assumption_log", "confidence_notes"],
    requiresApproval: true,
    availableForIntents: ["estimate_only", "renovation", "new_build"],
    qualificationRules: ["Confidence lower without plans", "Not a bid commitment"],
    upsellTargets: ["permit_path_review", "contractor_match"]
  },
  {
    code: "permit_path_review",
    version: "1.0.0",
    status: "active",
    name: "Permit Path Review",
    category: "permits",
    description: "Jurisdiction-specific permit route, likely filings, basic required documents, and key review risks.",
    basePrice: 325,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_PERMIT_SIMPLE",
    stripePriceKey: "STRIPE_PRICE_PERMIT_SIMPLE",
    includedOutputs: ["jurisdiction_summary", "permit_path", "required_docs_outline", "risk_flags"],
    requiresApproval: true,
    availableForIntents: ["permit_only", "renovation", "new_build", "design_concept"],
    qualificationRules: ["Requires address", "Output is planning support, not filing completion"],
    upsellTargets: ["permit_prep", "full_permit_coordination"]
  },
  {
    code: "permit_prep",
    version: "1.0.0",
    status: "active",
    name: "Permit Prep",
    category: "permits",
    description: "Permit readiness packaging, checklist completion, and submission prep support.",
    basePrice: 500,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_PERMIT_PACKAGE",
    stripePriceKey: "STRIPE_PRICE_PERMIT_PACKAGE",
    includedOutputs: ["submission_checklist", "application_package_review", "readiness_gaps"],
    requiresApproval: true,
    availableForIntents: ["permit_only", "renovation", "new_build"],
    qualificationRules: ["Best when plans exist", "Filing support may still require operator review"],
    upsellTargets: ["full_permit_coordination"]
  },
  {
    code: "full_permit_coordination",
    version: "1.0.0",
    status: "active",
    name: "Full Permit Coordination",
    category: "permits",
    description: "Hands-on permit coordination across submission, comments, revisions, and status management.",
    basePrice: 1000,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_PERMIT_COORDINATION",
    stripePriceKey: "STRIPE_PRICE_PERMIT_COORDINATION",
    includedOutputs: ["permit_case_management", "comment_tracking", "status_updates", "coordination_support"],
    requiresApproval: true,
    availableForIntents: ["permit_only", "renovation", "new_build", "developer_feasibility"],
    qualificationRules: ["Scope- and jurisdiction-dependent", "Operator assigned"],
    upsellTargets: ["contractor_match_service", "escrow_finance_trust"]
  },
  {
    code: "contractor_match_service",
    version: "1.0.0",
    status: "active",
    notes: "TODO_VERIFY: Maps to STRIPE_PRICE_LISTING_BASIC or a new product — confirm with marketplace team.",
    name: "Marketplace Match",
    category: "marketplace",
    description: "Readiness-based contractor matching and candidate routing.",
    basePrice: 50,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_LISTING_BASIC",
    stripePriceKey: "STRIPE_PRICE_LISTING_BASIC",
    includedOutputs: ["contractor_shortlist", "match_notes", "next_steps"],
    requiresApproval: true,
    availableForIntents: ["contractor_match", "renovation", "new_build"],
    qualificationRules: ["Project must meet readiness threshold", "Final assignment approval required"],
    upsellTargets: ["escrow_finance_trust", "construction_execution"]
  },
  {
    code: "contractor_growth_package",
    version: "1.0.0",
    status: "active",
    name: "Contractor Growth Package",
    category: "growth",
    description: "Contractor marketing/growth package including premium listing and priority leads.",
    basePrice: 299,
    currency: "USD",
    billingType: "subscription",
    stripeProductKey: "STRIPE_PRICE_LISTING_PRO",
    stripePriceKey: "STRIPE_PRICE_LISTING_PRO",
    includedOutputs: ["premium_listing", "priority_leads", "kealee_verified_badge"],
    requiresApproval: true,
    availableForIntents: ["contractor_match"],
    qualificationRules: ["Contractor must be verified"],
    upsellTargets: []
  },
  {
    code: "developer_advisory",
    version: "1.0.0",
    status: "active",
    name: "Developer Advisory / Feasibility",
    category: "developer",
    description: "Developer-focused feasibility and development advisory package for land and mixed-use opportunities.",
    basePrice: 4500,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_DEV_FEASIBILITY",
    stripePriceKey: "STRIPE_PRICE_DEV_FEASIBILITY",
    includedOutputs: ["developer_summary", "zoning_constraints", "feasibility_notes", "recommended_next_workstreams"],
    requiresApproval: true,
    availableForIntents: ["developer_feasibility"],
    qualificationRules: ["Address/parcel required", "Operator review recommended"],
    upsellTargets: ["capital_stack_advisory", "permit_strategy"]
  },
  {
    code: "escrow_finance_trust",
    version: "1.0.0",
    status: "draft",
    notes: "TODO_VERIFY: No direct Stripe price found for escrow onboarding — custom quote flow. Wire to finance-trust module when built.",
    name: "Escrow / Finance Trust Onboarding",
    category: "finance",
    description: "Setup package for milestone payment governance, escrow/trust flow, and lender/disbursement readiness.",
    basePrice: 0,
    currency: "USD",
    billingType: "custom_quote",
    includedOutputs: ["payment_governance_setup", "milestone_rules", "approval_matrix"],
    requiresApproval: true,
    availableForIntents: ["construction_execution", "payment_disbursement", "contractor_match"],
    qualificationRules: ["Project record required", "Financial controls required"],
    upsellTargets: []
  }
];
