import { ServiceOfferingSeed } from "../types";

// Source: stripe-products-env.txt (2026-03-24), homeowners/page.tsx, contractors/page.tsx,
//         developers/page.tsx, concept-engine/garden/page.tsx, ops-services/service-plan.service.ts
// All basePrice values match live customer-facing pages. stripePriceKey = exact STRIPE_PRICE_* env var name.

export const serviceOfferingSeeds: ServiceOfferingSeed[] = [

  // ── Design / Concept Engine ──────────────────────────────────────────────────

  {
    code: "ai_concept_basic",
    version: "1.1.0",
    status: "active",
    source: "homeowners_page_pricing",
    notes: "Exterior concept = STRIPE_PRICE_DESIGN_CONCEPT_VALIDATION ($585). Price corrected 2026-03-24 from $149 placeholder.",
    name: "AI Concept Design Package",
    category: "design",
    description: "3 property-specific exterior concept visuals, design direction summary, zoning brief, path-to-approval plan, 1 feedback round, downloadable PDF, and included design consultation.",
    basePrice: 585,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_DESIGN_CONCEPT_VALIDATION",
    stripePriceKey: "STRIPE_PRICE_DESIGN_CONCEPT_VALIDATION",
    includedOutputs: ["concept_brief", "3_concept_visuals", "zoning_brief", "path_to_approval_plan", "downloadable_pdf", "design_consultation"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation"],
    qualificationRules: ["Best for early stage", "Not final construction documents", "Escalate complex scopes"],
    upsellTargets: ["ai_concept_advanced", "permit_path_review", "estimate_package"],
    deliveryWorkflowCode: "wf_homeowner_concept_v1"
  },
  {
    code: "ai_concept_advanced",
    version: "1.0.0",
    status: "active",
    source: "homeowners_page_pricing",
    name: "Advanced AI Concept",
    category: "design",
    description: "3 floor plan options, 3D views, material suggestions, and up to 3 revision rounds. Full AI-powered concept with presentation-quality deliverables.",
    basePrice: 899,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_DESIGN_ADVANCED",
    stripePriceKey: "STRIPE_PRICE_DESIGN_ADVANCED",
    includedOutputs: ["3_floor_plan_options", "3d_views", "material_suggestions", "3_revision_rounds", "downloadable_pdf"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation", "new_build"],
    qualificationRules: ["Not permit-ready drawings", "Escalate structural/MEP complexity"],
    upsellTargets: ["full_design_package", "permit_path_review"],
    deliveryWorkflowCode: "wf_homeowner_concept_v1"
  },
  {
    code: "full_design_package",
    version: "1.0.0",
    status: "active",
    source: "homeowners_page_pricing",
    name: "Full Design Package",
    category: "design",
    description: "Permit-ready drawing set with up to 5 revision rounds. Includes all drawings required for permit application submission.",
    basePrice: 4499,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_DESIGN_FULL",
    stripePriceKey: "STRIPE_PRICE_DESIGN_FULL",
    includedOutputs: ["permit_ready_drawing_set", "5_revision_rounds", "full_design_documentation"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation", "new_build"],
    qualificationRules: ["Projects over $65k or structural complexity connected to licensed architect", "Requires permit package as next step"],
    upsellTargets: ["permit_prep", "full_permit_coordination"],
    deliveryWorkflowCode: "wf_homeowner_concept_v1"
  },

  // ── Garden / Farming Concepts ─────────────────────────────────────────────────

  {
    code: "garden_concept_basic",
    version: "1.0.0",
    status: "active",
    source: "concept_engine_garden_page",
    name: "AI Garden Concept",
    category: "design_garden",
    description: "AI garden layout, raised bed placement, irrigation overview, planting guide, seasonal calendar, and 3 concept layouts. Includes PDF package and consultation call.",
    basePrice: 395,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_GARDEN_BASIC",
    stripePriceKey: "STRIPE_PRICE_GARDEN_BASIC",
    includedOutputs: ["garden_layout", "raised_bed_placement", "irrigation_overview", "planting_guide", "seasonal_calendar", "pdf_package", "consultation_call"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation"],
    qualificationRules: ["All onsite installation by contractor of record", "Advisory and design only"],
    upsellTargets: ["garden_concept_advanced", "contractor_match_service"],
    deliveryWorkflowCode: "wf_homeowner_concept_v1"
  },
  {
    code: "garden_concept_advanced",
    version: "1.0.0",
    status: "active",
    source: "concept_engine_garden_page",
    name: "Advanced Garden Design",
    category: "design_garden",
    description: "Detailed plant lists, irrigation specs, 3D garden views, and up to 3 revision rounds. Full design package for raised beds, backyard farming, and irrigation.",
    basePrice: 750,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_GARDEN_ADVANCED",
    stripePriceKey: "STRIPE_PRICE_GARDEN_ADVANCED",
    includedOutputs: ["detailed_plant_lists", "irrigation_specs", "3d_garden_views", "3_revision_rounds", "pdf_package"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation"],
    qualificationRules: ["Advisory and design only — installation by contractor of record"],
    upsellTargets: ["garden_concept_full", "contractor_match_service"],
    deliveryWorkflowCode: "wf_homeowner_concept_v1"
  },
  {
    code: "garden_concept_full",
    version: "1.0.0",
    status: "active",
    source: "concept_engine_garden_page",
    name: "Full Landscape Design",
    category: "design_garden",
    description: "Permit-ready landscape plans and full contractor package. Complete landscape design for complex garden, farming, and outdoor living projects with up to 5 revision rounds.",
    basePrice: 2500,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_GARDEN_FULL",
    stripePriceKey: "STRIPE_PRICE_GARDEN_FULL",
    includedOutputs: ["permit_ready_landscape_plans", "full_contractor_package", "5_revision_rounds"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation", "new_build"],
    qualificationRules: ["Complex scope may require licensed landscape architect", "Installation by contractor of record"],
    upsellTargets: ["permit_path_review", "contractor_match_service"]
  },

  // ── Interior / Whole Home Concepts ────────────────────────────────────────────

  {
    code: "interior_reno_basic",
    version: "1.0.0",
    status: "active",
    source: "concept_engine_pricing",
    name: "Interior Reno AI Concept",
    category: "design_interior",
    description: "AI-powered interior renovation concept package: kitchen, bath, room additions, ADU concepts. 3 layout options, design direction, and consultation included.",
    basePrice: 395,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_INTERIOR_BASIC",
    stripePriceKey: "STRIPE_PRICE_INTERIOR_BASIC",
    includedOutputs: ["3_layout_options", "design_direction", "material_palette", "pdf_package", "consultation_call"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation"],
    qualificationRules: ["Not permit-ready drawings", "Escalate structural complexity"],
    upsellTargets: ["interior_reno_advanced", "permit_path_review"]
  },
  {
    code: "interior_reno_advanced",
    version: "1.0.0",
    status: "active",
    source: "concept_engine_pricing",
    name: "Advanced Interior Design",
    category: "design_interior",
    description: "Advanced interior design with detailed floor plans, material specs, and up to 3 revision rounds for kitchen, bath, additions, and ADU projects.",
    basePrice: 899,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_INTERIOR_ADVANCED",
    stripePriceKey: "STRIPE_PRICE_INTERIOR_ADVANCED",
    includedOutputs: ["detailed_floor_plans", "material_specs", "3d_renders", "3_revision_rounds"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation"],
    qualificationRules: ["Escalate structural/MEP complexity"],
    upsellTargets: ["interior_reno_full", "permit_prep"]
  },
  {
    code: "interior_reno_full",
    version: "1.0.0",
    status: "active",
    source: "concept_engine_pricing",
    name: "Full Interior Design Package",
    category: "design_interior",
    description: "Permit-ready interior design drawing set with up to 5 revision rounds. Complete package for permit submission including all interior and addition drawings.",
    basePrice: 4499,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_INTERIOR_FULL",
    stripePriceKey: "STRIPE_PRICE_INTERIOR_FULL",
    includedOutputs: ["permit_ready_drawing_set", "5_revision_rounds", "full_interior_documentation"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation", "new_build"],
    qualificationRules: ["Complex structural requires licensed architect"],
    upsellTargets: ["permit_prep", "full_permit_coordination"]
  },
  {
    code: "whole_home_basic",
    version: "1.0.0",
    status: "active",
    source: "concept_engine_pricing",
    name: "Whole Home Renovation Concept",
    category: "design_whole_home",
    description: "Full property transformation concept — floor plans, structural changes, systems, and every room. 3 concept options with 1 feedback round and consultation.",
    basePrice: 585,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_WHOLE_HOME_BASIC",
    stripePriceKey: "STRIPE_PRICE_WHOLE_HOME_BASIC",
    includedOutputs: ["3_whole_home_concepts", "floor_plan_overview", "systems_summary", "pdf_package", "consultation_call"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation", "new_build"],
    qualificationRules: ["Not permit-ready drawings", "Structural/MEP complexity escalated"],
    upsellTargets: ["whole_home_advanced", "permit_path_review"]
  },
  {
    code: "whole_home_advanced",
    version: "1.0.0",
    status: "active",
    source: "concept_engine_pricing",
    name: "Advanced Whole Home Design",
    category: "design_whole_home",
    description: "Detailed whole home redesign with floor plan options, 3D views, material palette, and up to 3 revision rounds.",
    basePrice: 899,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_WHOLE_HOME_ADVANCED",
    stripePriceKey: "STRIPE_PRICE_WHOLE_HOME_ADVANCED",
    includedOutputs: ["floor_plan_options", "3d_views", "material_palette", "3_revision_rounds"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation", "new_build"],
    qualificationRules: ["Structural/MEP escalated"],
    upsellTargets: ["whole_home_full", "permit_prep"]
  },
  {
    code: "whole_home_full",
    version: "1.0.0",
    status: "active",
    source: "concept_engine_pricing",
    name: "Full Whole Home Design Package",
    category: "design_whole_home",
    description: "Permit-ready full home redesign drawing set with up to 5 revision rounds. Complete documentation package for permit submission.",
    basePrice: 4499,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_WHOLE_HOME_FULL",
    stripePriceKey: "STRIPE_PRICE_WHOLE_HOME_FULL",
    includedOutputs: ["permit_ready_drawing_set", "5_revision_rounds", "full_home_documentation"],
    requiresApproval: true,
    availableForIntents: ["design_concept", "renovation", "new_build"],
    qualificationRules: ["Projects over $65k connected to licensed architect", "Structural requires PE stamp"],
    upsellTargets: ["full_permit_coordination", "pm_advisory"]
  },

  // ── Feasibility ──────────────────────────────────────────────────────────────

  {
    code: "feasibility_light_package",
    version: "1.0.0",
    status: "draft",
    notes: "No direct Stripe price found — may be bundled or custom quote. Add STRIPE_PRICE_FEASIBILITY_LIGHT when product is created.",
    name: "Feasibility Light",
    category: "feasibility",
    description: "Quick zoning-aware viability review with constraints, rough massing fit, and early risk notes.",
    basePrice: 295,
    currency: "USD",
    billingType: "one_time",
    includedOutputs: ["feasibility_summary", "risk_flags", "recommendation_path"],
    requiresApproval: true,
    availableForIntents: ["feasibility_light", "design_concept", "new_build", "developer_feasibility"],
    qualificationRules: ["Requires address or parcel", "Advisory only"],
    upsellTargets: ["permit_path_review", "developer_advisory"]
  },

  // ── Estimates ────────────────────────────────────────────────────────────────

  {
    code: "estimate_package",
    version: "1.1.0",
    status: "active",
    source: "homeowners_page_pricing",
    notes: "Detailed Estimate = STRIPE_PRICE_ESTIMATE_DETAILED ($595). Price corrected 2026-03-24 from $249 placeholder.",
    name: "Detailed Estimate",
    category: "estimate",
    description: "Professional cost analyst review with detailed estimate, scope assumptions, and confidence notes. Lender-supportable but not certified.",
    basePrice: 595,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_ESTIMATE_DETAILED",
    stripePriceKey: "STRIPE_PRICE_ESTIMATE_DETAILED",
    includedOutputs: ["detailed_estimate_range", "scope_assumptions", "confidence_notes", "analyst_review"],
    requiresApproval: true,
    availableForIntents: ["estimate_only", "renovation", "new_build"],
    qualificationRules: ["Confidence lower without plans", "Not a bid commitment"],
    upsellTargets: ["estimate_certified", "permit_path_review", "contractor_match_service"]
  },
  {
    code: "estimate_certified",
    version: "1.0.0",
    status: "active",
    source: "homeowners_page_pricing",
    name: "Certified Estimate",
    category: "estimate",
    description: "Lender-ready certified cost report with full scope assumptions, unit cost breakdown, and professional certification.",
    basePrice: 1850,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_ESTIMATE_CERTIFIED",
    stripePriceKey: "STRIPE_PRICE_ESTIMATE_CERTIFIED",
    includedOutputs: ["certified_cost_report", "unit_cost_breakdown", "lender_certification", "full_scope_assumptions"],
    requiresApproval: true,
    availableForIntents: ["estimate_only", "renovation", "new_build", "developer_feasibility"],
    qualificationRules: ["Requires plans or detailed scope", "Not a bid commitment"],
    upsellTargets: ["permit_path_review", "contractor_match_service"]
  },

  // ── Permits ──────────────────────────────────────────────────────────────────

  {
    code: "permit_path_review",
    version: "1.1.0",
    status: "active",
    source: "homeowners_page_pricing",
    notes: "STRIPE_PRICE_PERMIT_SIMPLE = Simple Permit Filing ($149 single-trade). Price corrected 2026-03-24 from $325 placeholder.",
    name: "Simple Permit Filing",
    category: "permits",
    description: "Single-trade permit filing service. Kealee handles the complete filing for simple, single-trade permits (electrical, plumbing, mechanical).",
    basePrice: 149,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_PERMIT_SIMPLE",
    stripePriceKey: "STRIPE_PRICE_PERMIT_SIMPLE",
    includedOutputs: ["permit_application_filed", "jurisdiction_coordination", "filing_confirmation"],
    requiresApproval: true,
    availableForIntents: ["permit_only", "renovation"],
    qualificationRules: ["Single-trade permits only", "Requires complete scope and address", "Complex multi-trade → upgrade to permit_prep"],
    upsellTargets: ["permit_prep", "full_permit_coordination"]
  },
  {
    code: "permit_prep",
    version: "1.1.0",
    status: "active",
    source: "homeowners_page_pricing",
    notes: "STRIPE_PRICE_PERMIT_PACKAGE = Permit Package ($950 full application prep + submission). Price corrected 2026-03-24 from $500 placeholder.",
    name: "Permit Package",
    category: "permits",
    description: "Full permit application preparation and submission. Includes application package, plan set review, checklist completion, and submission coordination.",
    basePrice: 950,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_PERMIT_PACKAGE",
    stripePriceKey: "STRIPE_PRICE_PERMIT_PACKAGE",
    includedOutputs: ["application_package", "plan_set_review", "submission_checklist", "submission_coordination"],
    requiresApproval: true,
    availableForIntents: ["permit_only", "renovation", "new_build"],
    qualificationRules: ["Best when plans exist", "Multi-trade or complex scope eligible"],
    upsellTargets: ["full_permit_coordination", "permit_expediting"]
  },
  {
    code: "full_permit_coordination",
    version: "1.1.0",
    status: "active",
    source: "homeowners_page_pricing",
    notes: "STRIPE_PRICE_PERMIT_COORDINATION = Permit Coordination ($2,750). Price corrected 2026-03-24 from $1,000 placeholder.",
    name: "Permit Coordination",
    category: "permits",
    description: "Hands-on permit coordination across submission, plan review comments, revisions, and ongoing status management until permit issuance.",
    basePrice: 2750,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_PERMIT_COORDINATION",
    stripePriceKey: "STRIPE_PRICE_PERMIT_COORDINATION",
    includedOutputs: ["permit_case_management", "comment_response_support", "revision_coordination", "status_updates"],
    requiresApproval: true,
    availableForIntents: ["permit_only", "renovation", "new_build", "developer_feasibility"],
    qualificationRules: ["Scope- and jurisdiction-dependent", "Operator assigned"],
    upsellTargets: ["permit_expediting", "contractor_match_service", "escrow_finance_trust"]
  },
  {
    code: "permit_expediting",
    version: "1.0.0",
    status: "active",
    source: "homeowners_page_pricing",
    name: "Permit Expediting",
    category: "permits",
    description: "Priority approval service with expedited processing, dedicated permit runner, and accelerated review coordination for time-sensitive projects.",
    basePrice: 5500,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_PERMIT_EXPEDITING",
    stripePriceKey: "STRIPE_PRICE_PERMIT_EXPEDITING",
    includedOutputs: ["priority_processing", "dedicated_permit_runner", "accelerated_review_coordination", "status_reporting"],
    requiresApproval: true,
    availableForIntents: ["permit_only", "renovation", "new_build", "developer_feasibility"],
    qualificationRules: ["Jurisdiction must support expedited review", "Operator pre-approval required", "Availability limited"],
    upsellTargets: ["contractor_match_service", "pm_advisory"]
  },

  // ── Project Management ────────────────────────────────────────────────────────

  {
    code: "pm_advisory",
    version: "1.0.0",
    status: "active",
    source: "homeowners_page_pricing",
    name: "PM Advisory",
    category: "project_management",
    description: "Milestone reviews and budget oversight by a dedicated PM advisor. Review at each milestone, budget variance alerts, and scope change guidance.",
    basePrice: 950,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_PM_ADVISORY",
    stripePriceKey: "STRIPE_PRICE_PM_ADVISORY",
    includedOutputs: ["milestone_reviews", "budget_oversight", "scope_change_guidance", "pm_advisor_access"],
    requiresApproval: true,
    availableForIntents: ["construction_execution", "renovation", "new_build"],
    qualificationRules: ["Project record required", "One-time per project — not a subscription"],
    upsellTargets: ["pm_oversight", "escrow_finance_trust"]
  },
  {
    code: "pm_oversight",
    version: "1.0.0",
    status: "active",
    source: "homeowners_page_pricing",
    name: "PM Oversight",
    category: "project_management",
    description: "Full project management from groundbreaking to closeout. Dedicated PM, daily progress tracking, RFI management, punch list coordination, and final inspection.",
    basePrice: 2950,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_PM_OVERSIGHT",
    stripePriceKey: "STRIPE_PRICE_PM_OVERSIGHT",
    includedOutputs: ["dedicated_pm", "daily_progress_tracking", "rfi_management", "punch_list_coordination", "final_inspection_support"],
    requiresApproval: true,
    availableForIntents: ["construction_execution", "renovation", "new_build"],
    qualificationRules: ["Project record required", "One-time per project — not a subscription"],
    upsellTargets: ["escrow_finance_trust"]
  },

  // ── Marketplace / Contractor ──────────────────────────────────────────────────

  {
    code: "contractor_match_service",
    version: "1.0.0",
    status: "active",
    source: "stripe_products_env",
    name: "Marketplace Match",
    category: "marketplace",
    description: "Readiness-based contractor matching and candidate routing. AI-powered match with verified, background-checked contractors for your scope and geography.",
    basePrice: 50,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_LISTING_BASIC",
    stripePriceKey: "STRIPE_PRICE_LISTING_BASIC",
    includedOutputs: ["contractor_shortlist", "match_notes", "next_steps"],
    requiresApproval: true,
    availableForIntents: ["contractor_match", "renovation", "new_build"],
    qualificationRules: ["Project must meet readiness threshold", "Final assignment approval required"],
    upsellTargets: ["escrow_finance_trust", "pm_advisory"]
  },
  {
    code: "contractor_growth_package",
    version: "1.0.0",
    status: "active",
    source: "stripe_products_env",
    notes: "STRIPE_PRICE_LISTING_PRO = Pro Listing subscription ($299/mo). Separate from GROWTH_* contractor growth tiers.",
    name: "Pro Listing",
    category: "marketplace",
    description: "Pro marketplace listing subscription for verified contractors. Includes premium listing placement, priority lead routing, and Kealee Verified badge.",
    basePrice: 299,
    currency: "USD",
    billingType: "subscription",
    stripeProductKey: "STRIPE_PRICE_LISTING_PRO",
    stripePriceKey: "STRIPE_PRICE_LISTING_PRO",
    includedOutputs: ["premium_listing", "priority_leads", "kealee_verified_badge"],
    requiresApproval: true,
    availableForIntents: ["contractor_match"],
    qualificationRules: ["Contractor must be verified and licensed"],
    upsellTargets: ["listing_premium"]
  },
  {
    code: "listing_premium",
    version: "1.0.0",
    status: "active",
    source: "stripe_products_env",
    notes: "STRIPE_PRICE_LISTING_PREMIUM — premium listing tier above LISTING_PRO. Price estimated at $499/mo; verify with marketplace team.",
    name: "Premium Listing",
    category: "marketplace",
    description: "Top-tier marketplace listing with maximum visibility, featured placement, and enterprise-level lead routing for high-volume verified contractors.",
    basePrice: 499,
    currency: "USD",
    billingType: "subscription",
    stripeProductKey: "STRIPE_PRICE_LISTING_PREMIUM",
    stripePriceKey: "STRIPE_PRICE_LISTING_PREMIUM",
    includedOutputs: ["featured_placement", "max_visibility", "enterprise_lead_routing", "dedicated_account_support"],
    requiresApproval: true,
    availableForIntents: ["contractor_match"],
    qualificationRules: ["Contractor must be verified, licensed, and meet volume requirements"],
    upsellTargets: []
  },

  // ── Contractor Growth Tiers (GROWTH_*) ────────────────────────────────────────

  {
    code: "growth_starter",
    version: "1.0.0",
    status: "active",
    source: "contractors_page_pricing",
    name: "Starter Growth Plan",
    category: "contractor_growth",
    description: "Starter tier for contractors joining the Kealee marketplace. Includes marketplace listing, matched leads (up to 10 bid responses/month), and platform access.",
    basePrice: 99,
    currency: "USD",
    billingType: "subscription",
    stripeProductKey: "STRIPE_PRICE_GROWTH_STARTER",
    stripePriceKey: "STRIPE_PRICE_GROWTH_STARTER",
    includedOutputs: ["marketplace_listing", "matched_leads_10", "platform_access"],
    requiresApproval: false,
    availableForIntents: ["contractor_match"],
    qualificationRules: ["Contractor must be verified"],
    upsellTargets: ["growth_pro"]
  },
  {
    code: "growth_pro",
    version: "1.0.0",
    status: "active",
    source: "contractors_page_pricing",
    name: "Growth Plan",
    category: "contractor_growth",
    description: "Growth tier for active contractors. Priority matching, unlimited bid responses, KeaBot GC AI assistant, and CRM tools included.",
    basePrice: 199,
    currency: "USD",
    billingType: "subscription",
    stripeProductKey: "STRIPE_PRICE_GROWTH_PRO",
    stripePriceKey: "STRIPE_PRICE_GROWTH_PRO",
    includedOutputs: ["priority_matching", "unlimited_bids", "keabot_gc", "crm_tools"],
    requiresApproval: false,
    availableForIntents: ["contractor_match"],
    qualificationRules: ["Contractor must be verified"],
    upsellTargets: ["growth_enterprise"]
  },
  {
    code: "growth_enterprise",
    version: "1.1.0",
    status: "active",
    source: "contractors_page_pricing",
    notes: "Price updated to $899/mo 2026-03-24 to include marketing services bundle (website, SEO, digital presence).",
    name: "Pro Growth Plan",
    category: "contractor_growth",
    description: "Top-tier contractor growth plan with full marketing services bundle. Includes Construction OS access, top-of-feed placement, enterprise integrations, dedicated account management, professional website, SEO, and digital marketing presence.",
    basePrice: 899,
    currency: "USD",
    billingType: "subscription",
    stripeProductKey: "STRIPE_PRICE_GROWTH_ENTERPRISE",
    stripePriceKey: "STRIPE_PRICE_GROWTH_ENTERPRISE",
    includedOutputs: ["construction_os_access", "top_feed_placement", "enterprise_integrations", "dedicated_account_mgmt", "professional_website", "seo_optimization", "digital_marketing_presence"],
    requiresApproval: false,
    availableForIntents: ["contractor_match"],
    qualificationRules: ["Contractor must be verified and meet volume thresholds"],
    upsellTargets: []
  },

  // ── Ops Services (Service Plans A–D) ─────────────────────────────────────────

  {
    code: "ops_services_a",
    version: "1.0.0",
    status: "active",
    source: "ops_services_service_plan_service",
    name: "Ops Package A — Basic PM",
    category: "ops_services",
    description: "Basic project management support tier. Weekly progress reports, email support, and standard PM coordination for smaller projects.",
    basePrice: 1750,
    currency: "USD",
    billingType: "subscription",
    stripeProductKey: "STRIPE_PRICE_OPS_A",
    stripePriceKey: "STRIPE_PRICE_OPS_A",
    includedOutputs: ["basic_pm_support", "weekly_reports", "email_support"],
    requiresApproval: true,
    availableForIntents: ["construction_execution"],
    qualificationRules: ["Active project record required", "Operator assignment required"],
    upsellTargets: ["ops_services_b"]
  },
  {
    code: "ops_services_b",
    version: "1.0.0",
    status: "active",
    source: "ops_services_service_plan_service",
    name: "Ops Package B — Enhanced PM",
    category: "ops_services",
    description: "Enhanced project management support with bi-weekly reporting, priority support channel, and enhanced PM coordination for mid-size projects.",
    basePrice: 3750,
    currency: "USD",
    billingType: "subscription",
    stripeProductKey: "STRIPE_PRICE_OPS_B",
    stripePriceKey: "STRIPE_PRICE_OPS_B",
    includedOutputs: ["enhanced_pm_support", "biweekly_reports", "priority_support"],
    requiresApproval: true,
    availableForIntents: ["construction_execution"],
    qualificationRules: ["Active project record required", "Operator assignment required"],
    upsellTargets: ["ops_services_c"]
  },
  {
    code: "ops_services_c",
    version: "1.0.0",
    status: "active",
    source: "ops_services_service_plan_service",
    name: "Ops Package C — Dedicated PM",
    category: "ops_services",
    description: "Dedicated project manager with weekly reporting, phone support, and project health monitoring. For larger residential and commercial projects.",
    basePrice: 9500,
    currency: "USD",
    billingType: "subscription",
    stripeProductKey: "STRIPE_PRICE_OPS_C",
    stripePriceKey: "STRIPE_PRICE_OPS_C",
    includedOutputs: ["dedicated_pm", "weekly_reports", "phone_support", "project_health_monitoring"],
    requiresApproval: true,
    availableForIntents: ["construction_execution"],
    qualificationRules: ["Active project record required", "PM assigned from ops team"],
    upsellTargets: ["ops_services_d"]
  },
  {
    code: "ops_services_d",
    version: "1.0.0",
    status: "active",
    source: "ops_services_service_plan_service",
    name: "Ops Package D — Enterprise PM",
    category: "ops_services",
    description: "Dedicated PM team with daily reporting, 24/7 support, and full project oversight. Enterprise-grade operations for large or complex construction projects.",
    basePrice: 16500,
    currency: "USD",
    billingType: "subscription",
    stripeProductKey: "STRIPE_PRICE_OPS_D",
    stripePriceKey: "STRIPE_PRICE_OPS_D",
    includedOutputs: ["dedicated_pm_team", "daily_reports", "24_7_support", "full_project_oversight"],
    requiresApproval: true,
    availableForIntents: ["construction_execution"],
    qualificationRules: ["Active project record required", "Enterprise account required"],
    upsellTargets: []
  },

  // ── Developer Services ────────────────────────────────────────────────────────

  {
    code: "developer_advisory",
    version: "1.0.0",
    status: "active",
    source: "developers_page_pricing",
    name: "Developer Feasibility Study",
    category: "developer",
    description: "Comprehensive developer feasibility study: pro forma modeling, IRR/cash-on-cash analysis, unit mix optimization, scenario modeling, and go/no-go recommendation.",
    basePrice: 4500,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_DEV_FEASIBILITY",
    stripePriceKey: "STRIPE_PRICE_DEV_FEASIBILITY",
    includedOutputs: ["pro_forma_model", "irr_analysis", "unit_mix_optimization", "scenario_modeling", "go_no_go_recommendation"],
    requiresApproval: true,
    availableForIntents: ["developer_feasibility"],
    qualificationRules: ["Address/parcel required", "Operator review recommended", "Pricing range $4,500–$12,000 based on complexity"],
    upsellTargets: ["dev_proforma", "dev_capital_stack", "dev_entitlements"]
  },
  {
    code: "dev_proforma",
    version: "1.0.0",
    status: "active",
    source: "developers_page_pricing",
    name: "Pro Forma Analysis",
    category: "developer",
    description: "Developer pro forma analysis: unit mix, cost and revenue assumptions, sensitivity analysis. Pricing range $2,500–$6,000 based on project complexity.",
    basePrice: 2500,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_DEV_PROFORMA",
    stripePriceKey: "STRIPE_PRICE_DEV_PROFORMA",
    includedOutputs: ["unit_mix_analysis", "cost_revenue_assumptions", "sensitivity_analysis", "pro_forma_model"],
    requiresApproval: true,
    availableForIntents: ["developer_feasibility"],
    qualificationRules: ["Project or parcel record required"],
    upsellTargets: ["dev_capital_stack", "dev_entitlements"]
  },
  {
    code: "dev_capital_stack",
    version: "1.0.0",
    status: "active",
    source: "developers_page_pricing",
    name: "Capital Stack Modeling",
    category: "developer",
    description: "Debt/equity structure modeling, draw schedule, waterfall projections, and investor reporting framework. Pricing range $3,500–$8,000.",
    basePrice: 3500,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_DEV_CAPITAL",
    stripePriceKey: "STRIPE_PRICE_DEV_CAPITAL",
    includedOutputs: ["debt_equity_structure", "draw_schedule", "waterfall_projections", "investor_reporting_framework"],
    requiresApproval: true,
    availableForIntents: ["developer_feasibility", "payment_disbursement"],
    qualificationRules: ["Pro forma or feasibility study required first", "Operator review required"],
    upsellTargets: ["dev_entitlements", "escrow_finance_trust"]
  },
  {
    code: "dev_entitlements",
    version: "1.0.0",
    status: "active",
    source: "developers_page_pricing",
    name: "Entitlement Support",
    category: "developer",
    description: "Zoning, variance, and regulatory filing coordination for development projects. Pricing range $7,500–$20,000 based on scope and jurisdiction.",
    basePrice: 7500,
    currency: "USD",
    billingType: "one_time",
    stripeProductKey: "STRIPE_PRICE_DEV_ENTITLEMENTS",
    stripePriceKey: "STRIPE_PRICE_DEV_ENTITLEMENTS",
    includedOutputs: ["zoning_analysis", "variance_support", "regulatory_filing_coordination", "entitlement_tracker"],
    requiresApproval: true,
    availableForIntents: ["developer_feasibility", "permit_only"],
    qualificationRules: ["Address/parcel required", "Operator and professional review required", "Timeline dependent on jurisdiction"],
    upsellTargets: ["full_permit_coordination", "pm_advisory"]
  },

  // ── Finance / Trust ───────────────────────────────────────────────────────────

  {
    code: "escrow_finance_trust",
    version: "1.0.0",
    status: "draft",
    notes: "No direct Stripe price — custom quote flow. Wire to finance-trust module when built.",
    name: "Escrow / Finance Trust Onboarding",
    category: "finance",
    description: "Setup package for milestone payment governance, escrow/trust flow, and lender/disbursement readiness.",
    basePrice: 0,
    currency: "USD",
    billingType: "custom_quote",
    includedOutputs: ["payment_governance_setup", "milestone_rules", "approval_matrix"],
    requiresApproval: true,
    availableForIntents: ["construction_execution", "payment_disbursement", "contractor_match"],
    qualificationRules: ["Project record required", "Financial controls required"],
    upsellTargets: []
  }
];
