/**
 * services/api/src/modules/integrations/zoho/zoho.crm.ts
 *
 * Zoho CRM operations for the contractor acquisition pipeline.
 *
 * Module mapping:
 *   Contractor Leads   → /Leads    (Contacted → Interested → Registration Started)
 *   Contractors        → /Contacts (Documents Uploaded → Verified → Active)
 *   Lead conversion    → /Leads/{id}/actions/convert
 *   Activity notes     → /Notes
 */

import {
  zohoGet,
  zohoPost,
  zohoPut,
  isZohoConfigured,
} from './zoho.client.js';
import {
  ZOHO_MODULES,
  CONTRACTOR_PIPELINE_STAGES,
  type ZohoLead,
  type ZohoContact,
  type ZohoApiResponse,
  type ZohoWriteResponse,
  type CreateLeadInput,
  type ContractorPipelineStage,
  type ContractorCampaign,
} from './zoho.types.js';

// ─── Guard ────────────────────────────────────────────────────────────────────

function assertConfigured(): void {
  if (!isZohoConfigured()) {
    throw new Error('Zoho CRM not configured — set ZOHO_CLIENT_ID, ZOHO_CLIENT_SECRET, ZOHO_REFRESH_TOKEN.');
  }
}

// ─── Leads ────────────────────────────────────────────────────────────────────

/**
 * Create a new contractor lead in Zoho CRM.
 * Called when GrowthBot detects a trade shortage and starts outreach.
 */
export async function createContractorLead(input: CreateLeadInput): Promise<string> {
  assertConfigured();

  const record: ZohoLead = {
    First_Name:        input.firstName,
    Last_Name:         input.lastName || input.company || 'Contractor',
    Email:             input.email,
    Phone:             input.phone,
    Company:           input.company,
    Lead_Source:       'GrowthBot',
    Description:       `Auto-generated by GrowthBot. Trade: ${input.trade ?? '—'}. Geo: ${input.geo ?? 'Platform-wide'}. Shortage score: ${input.shortageScore ?? 0}/100.`,
    Contractor_Stage:  CONTRACTOR_PIPELINE_STAGES.CONTACTED,
    Target_Trade:      input.trade,
    Target_Geo:        input.geo,
    Kealee_Profile_Id: input.kealeeProfileId,
    Kealee_User_Id:    input.kealeeUserId,
    Shortage_Score:    input.shortageScore,
    Campaign_Source:   input.campaignSource ?? 'shortage_auto',
    Registration_URL:  input.registrationUrl,
  };

  const res = await zohoPost<ZohoWriteResponse>(`/${ZOHO_MODULES.LEADS}`, {
    data: [record],
  });

  const result = res.data?.[0];
  if (!result || result.status !== 'success' || !result.details.id) {
    throw new Error(`Zoho createContractorLead failed: ${result?.message ?? 'unknown error'}`);
  }

  return result.details.id as string;
}

/**
 * Find a lead by email address.
 */
export async function findLeadByEmail(email: string): Promise<ZohoLead | null> {
  assertConfigured();

  const res = await zohoGet<ZohoApiResponse<ZohoLead>>(
    `/${ZOHO_MODULES.LEADS}/search`,
    { email },
  );

  return res.data?.[0] ?? null;
}

/**
 * Update the contractor pipeline stage on a lead.
 */
export async function updateLeadStage(
  leadId: string,
  stage:  ContractorPipelineStage,
  notes?: string,
): Promise<void> {
  assertConfigured();

  await zohoPut<ZohoWriteResponse>(`/${ZOHO_MODULES.LEADS}`, {
    data: [{
      id:                leadId,
      Contractor_Stage:  stage,
      ...(notes ? { Description: notes } : {}),
    }],
  });
}

/**
 * Bulk update leads from a campaign (e.g. mark all Contacted leads as Interested
 * after first email open — triggered via Zoho automation or webhook).
 */
export async function bulkUpdateLeadStage(
  leadIds: string[],
  stage:   ContractorPipelineStage,
): Promise<void> {
  assertConfigured();

  // Zoho supports up to 100 records per PUT
  const chunks: string[][] = [];
  for (let i = 0; i < leadIds.length; i += 100) {
    chunks.push(leadIds.slice(i, i + 100));
  }

  for (const chunk of chunks) {
    await zohoPut<ZohoWriteResponse>(`/${ZOHO_MODULES.LEADS}`, {
      data: chunk.map(id => ({ id, Contractor_Stage: stage })),
    });
  }
}

/**
 * Get all leads in a given pipeline stage.
 * Useful for reporting and follow-up campaigns.
 */
export async function getLeadsByStage(
  stage: ContractorPipelineStage,
  page  = 1,
  perPage = 200,
): Promise<ZohoLead[]> {
  assertConfigured();

  const res = await zohoGet<ZohoApiResponse<ZohoLead>>(
    `/${ZOHO_MODULES.LEADS}/search`,
    {
      criteria: `(Contractor_Stage:equals:${stage})`,
      page:     String(page),
      per_page: String(perPage),
    },
  );

  return res.data ?? [];
}

/**
 * Add a note to a lead record (activity log).
 */
export async function addLeadNote(
  leadId:  string,
  title:   string,
  content: string,
): Promise<void> {
  assertConfigured();

  await zohoPost<ZohoWriteResponse>(`/${ZOHO_MODULES.NOTES}`, {
    data: [{
      Note_Title:   title,
      Note_Content: content,
      Parent_Id:    leadId,
      $se_module:   ZOHO_MODULES.LEADS,
    }],
  });
}

// ─── Contacts (Verified Contractors) ─────────────────────────────────────────

/**
 * Upsert a contractor as a Zoho Contact.
 * Called when a contractor is verified or activates.
 */
export async function upsertContractorContact(params: {
  firstName?:         string;
  lastName:           string;
  email?:             string;
  phone?:             string;
  businessName?:      string;
  kealeeProfileId?:   string;
  kealeeUserId?:      string;
  verificationStatus?: string;
  trades?:            string[];
  serviceAreas?:      string[];
  stage:              ContractorPipelineStage;
}): Promise<string> {
  assertConfigured();

  // Check if contact already exists
  if (params.email) {
    const res = await zohoGet<ZohoApiResponse<ZohoContact>>(
      `/${ZOHO_MODULES.CONTACTS}/search`,
      { email: params.email },
    );

    const existing = res.data?.[0];
    if (existing?.id) {
      // Update existing
      await zohoPut<ZohoWriteResponse>(`/${ZOHO_MODULES.CONTACTS}`, {
        data: [{
          id:                  existing.id,
          Contractor_Stage:    params.stage,
          Verification_Status: params.verificationStatus,
          Trades:              params.trades?.join(', '),
          Service_Areas:       params.serviceAreas?.join(', '),
        }],
      });
      return existing.id;
    }
  }

  // Create new contact
  const record: ZohoContact = {
    First_Name:          params.firstName,
    Last_Name:           params.lastName,
    Email:               params.email,
    Phone:               params.phone,
    Account_Name:        params.businessName,
    Contractor_Stage:    params.stage,
    Kealee_Profile_Id:   params.kealeeProfileId,
    Kealee_User_Id:      params.kealeeUserId,
    Verification_Status: params.verificationStatus,
    Trades:              params.trades?.join(', '),
    Service_Areas:       params.serviceAreas?.join(', '),
  };

  const res = await zohoPost<ZohoWriteResponse>(`/${ZOHO_MODULES.CONTACTS}`, {
    data: [record],
  });

  const result = res.data?.[0];
  if (!result || result.status !== 'success' || !result.details.id) {
    throw new Error(`Zoho upsertContractorContact failed: ${result?.message ?? 'unknown'}`);
  }

  return result.details.id as string;
}

// ─── Campaign Creation ────────────────────────────────────────────────────────

/**
 * Create a campaign note in Zoho to track recruitment campaigns.
 * Used for audit trails and reporting on GrowthBot-initiated campaigns.
 *
 * Full Zoho Campaigns module integration can be added when
 * ZOHO_CAMPAIGNS plan is available.
 */
export async function recordCampaignActivity(
  campaign: ContractorCampaign,
  message:  string,
): Promise<void> {
  assertConfigured();

  // Record as a task in Zoho for ops team visibility
  await zohoPost<ZohoWriteResponse>(`/${ZOHO_MODULES.TASKS}`, {
    data: [{
      Subject:     `[GrowthBot] ${campaign.priority} Recruitment: ${campaign.trade}${campaign.geo ? ` — ${campaign.geo}` : ''}`,
      Description: message,
      Status:      'Not Started',
      Priority:    campaign.priority === 'CRITICAL' ? 'Highest' : campaign.priority === 'HIGH' ? 'High' : 'Normal',
      Due_Date:    new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    }],
  });
}

// ─── Upsert Lead (create or update) ──────────────────────────────────────────

/**
 * Create-or-update a contractor lead.
 * Returns lead ID and whether it was newly created.
 */
export async function upsertContractorLead(
  input: CreateLeadInput,
): Promise<{ id: string; created: boolean }> {
  assertConfigured();

  if (input.email) {
    const existing = await findLeadByEmail(input.email);
    if (existing?.id) {
      // Update stage and enrichment
      await updateLeadStage(
        existing.id,
        input.kealeeProfileId
          ? CONTRACTOR_PIPELINE_STAGES.INTERESTED
          : CONTRACTOR_PIPELINE_STAGES.CONTACTED,
      );
      return { id: existing.id, created: false };
    }
  }

  const id = await createContractorLead(input);
  return { id, created: true };
}
