import { ToolRegistrySeed } from "../types";

export const toolRegistrySeeds: ToolRegistrySeed[] = [
  { code: "create_project", version: "1.0.0", status: "active", name: "create_project", description: "Create a baseline project record from intake data.", category: "projects", requiresApproval: false, idempotent: false, inputSchemaRef: "CreateProjectInput", outputSchemaRef: "CreateProjectOutput", enabledEnvironments: ["dev", "staging", "prod"], tags: ["projects", "intake"] },
  { code: "update_project_context", version: "1.0.0", status: "active", name: "update_project_context", description: "Merge new facts or context into an existing project record.", category: "projects", requiresApproval: false, idempotent: true, inputSchemaRef: "UpdateProjectContextInput", outputSchemaRef: "UpdateProjectContextOutput", enabledEnvironments: ["dev", "staging", "prod"], tags: ["projects"] },
  { code: "check_zoning", version: "2.0.0", status: "active", name: "check_zoning", description: "Look up zoning, setbacks, ADU eligibility, and risk flags for an address.", category: "zoning", requiresApproval: false, idempotent: true, inputSchemaRef: "CheckZoningInput", outputSchemaRef: "ZoningResult", enabledEnvironments: ["dev", "staging", "prod"], tags: ["zoning", "permits", "intake"] },
  { code: "run_feasibility", version: "2.0.0", status: "active", name: "run_feasibility", description: "AI-powered feasibility assessment: cost range, timeline, risk flags, and next steps.", category: "feasibility", requiresApproval: false, idempotent: true, inputSchemaRef: "RunFeasibilityInput", outputSchemaRef: "FeasibilityResult", enabledEnvironments: ["dev", "staging", "prod"], tags: ["feasibility", "estimate"] },
  { code: "generate_concept_brief", version: "1.0.0", status: "active", name: "generate_concept_brief", description: "Generate design concept brief and recommend concept package.", category: "design", requiresApproval: false, idempotent: true, inputSchemaRef: "GenerateConceptBriefInput", outputSchemaRef: "ConceptBriefResult", enabledEnvironments: ["dev", "staging", "prod"], tags: ["design", "concept"] },
  { code: "create_estimate", version: "1.0.0", status: "active", name: "create_estimate", description: "Generate rough construction cost estimate with line items.", category: "estimate", requiresApproval: false, idempotent: true, inputSchemaRef: "CreateEstimateInput", outputSchemaRef: "EstimateResult", enabledEnvironments: ["dev", "staging", "prod"], tags: ["estimate", "intake"] },
  { code: "create_checkout", version: "1.0.0", status: "active", name: "create_checkout", description: "Create Stripe Checkout session for a service product.", category: "payments", requiresApproval: true, idempotent: false, inputSchemaRef: "CreateCheckoutInput", outputSchemaRef: "CheckoutResult", enabledEnvironments: ["dev", "staging", "prod"], tags: ["payments", "stripe"] },
  { code: "request_human_approval", version: "1.0.0", status: "active", name: "request_human_approval", description: "Halt plan execution and request user or operator approval.", category: "approvals", requiresApproval: true, idempotent: false, inputSchemaRef: "RequestApprovalInput", outputSchemaRef: "ApprovalRequestOutput", enabledEnvironments: ["dev", "staging", "prod"], tags: ["approval", "operator"] },
  { code: "assign_contractor", version: "1.0.0", status: "active", source: "TODO: services/api/modules/marketplace", name: "assign_contractor", description: "Match and assign a verified contractor to a project.", category: "marketplace", requiresApproval: true, idempotent: false, inputSchemaRef: "AssignContractorInput", outputSchemaRef: "AssignContractorOutput", enabledEnvironments: ["staging", "prod"], tags: ["marketplace", "contractor"] },
  { code: "create_milestone_schedule", version: "1.0.0", status: "active", source: "TODO: services/api/modules/projects", name: "create_milestone_schedule", description: "Create or update milestone schedule for a project.", category: "construction", requiresApproval: false, idempotent: true, inputSchemaRef: "CreateMilestoneScheduleInput", outputSchemaRef: "MilestoneScheduleOutput", enabledEnvironments: ["dev", "staging", "prod"], tags: ["construction", "milestones"] },
  { code: "send_email", version: "1.0.0", status: "active", source: "TODO: packages/communications", name: "send_email", description: "Send an email via Resend to a user or team member.", category: "communications", requiresApproval: true, idempotent: false, inputSchemaRef: "SendEmailInput", outputSchemaRef: "SendEmailOutput", enabledEnvironments: ["staging", "prod"], tags: ["email", "notifications"] },
  { code: "send_sms", version: "1.0.0", status: "active", source: "TODO: packages/communications", name: "send_sms", description: "Send an SMS via Twilio to a user or team member.", category: "communications", requiresApproval: true, idempotent: false, inputSchemaRef: "SendSmsInput", outputSchemaRef: "SendSmsOutput", enabledEnvironments: ["staging", "prod"], tags: ["sms", "notifications"] },
];
