import { ToolRegistrySeed } from "../types";

export const toolRegistrySeeds: ToolRegistrySeed[] = [
  { code: "tool_create_project", version: "1.0.0", status: "active", name: "create_project", description: "Create baseline project from intake.", category: "projects", ownerAgent: "keacore", requiresApproval: false, idempotent: false, sideEffectLevel: "write", inputSchemaRef: "CreateProjectInput", outputSchemaRef: "CreateProjectOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["intake","projects"] },
  { code: "tool_update_project_context", version: "1.0.0", status: "active", name: "update_project_context", description: "Normalize and enrich project context from intake, files, and previous outputs.", category: "projects", ownerAgent: "keacore", requiresApproval: false, idempotent: true, sideEffectLevel: "write", inputSchemaRef: "UpdateProjectContextInput", outputSchemaRef: "UpdateProjectContextOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["context","memory"] },
  { code: "tool_check_zoning", version: "2.0.0", status: "active", name: "check_zoning", description: "Resolve jurisdiction, zoning context, and zoning-aware constraints.", category: "zoning", ownerAgent: "permit", requiresApproval: false, idempotent: true, sideEffectLevel: "read", inputSchemaRef: "CheckZoningInput", outputSchemaRef: "CheckZoningOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["zoning","jurisdiction"] },
  { code: "tool_run_feasibility", version: "2.0.0", status: "active", name: "run_feasibility", description: "Generate early feasibility summary, key constraints, and viability flags.", category: "feasibility", ownerAgent: "feasibility", requiresApproval: false, idempotent: true, sideEffectLevel: "read", inputSchemaRef: "RunFeasibilityInput", outputSchemaRef: "RunFeasibilityOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["feasibility","analysis"] },
  { code: "tool_generate_concept_brief", version: "1.0.0", status: "active", name: "generate_concept_brief", description: "Create concept/design handoff brief.", category: "design", ownerAgent: "design", requiresApproval: false, idempotent: true, sideEffectLevel: "write", inputSchemaRef: "GenerateConceptBriefInput", outputSchemaRef: "GenerateConceptBriefOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["design","concept"] },
  { code: "tool_create_estimate", version: "1.0.0", status: "active", name: "create_estimate", description: "Create rough estimate or range using project assumptions.", category: "estimate", ownerAgent: "estimate", requiresApproval: false, idempotent: true, sideEffectLevel: "write", inputSchemaRef: "CreateEstimateInput", outputSchemaRef: "CreateEstimateOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["estimate","pricing"] },
  { code: "tool_create_checkout", version: "1.0.0", status: "active", name: "create_checkout", description: "Create Stripe checkout for an approved service offering.", category: "payments", ownerAgent: "payments", requiresApproval: true, idempotent: true, sideEffectLevel: "financial", inputSchemaRef: "CreateCheckoutInput", outputSchemaRef: "CreateCheckoutOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["stripe","checkout","payments"] },
  { code: "tool_request_human_approval", version: "1.0.0", status: "active", name: "request_human_approval", description: "Create approval request for user/operator review.", category: "governance", ownerAgent: "keacore", requiresApproval: false, idempotent: false, sideEffectLevel: "write", inputSchemaRef: "RequestHumanApprovalInput", outputSchemaRef: "RequestHumanApprovalOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["approval","governance"] },
  { code: "tool_assign_contractor", version: "1.0.0", status: "active", name: "assign_contractor", description: "Select and assign contractor candidates from verified pool.", category: "marketplace", ownerAgent: "marketplace", requiresApproval: true, idempotent: false, sideEffectLevel: "external_write", inputSchemaRef: "AssignContractorInput", outputSchemaRef: "AssignContractorOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["contractor","assignment"] },
  { code: "tool_create_milestone_schedule", version: "1.0.0", status: "active", name: "create_milestone_schedule", description: "Create project milestone schedule from template.", category: "construction", ownerAgent: "construction", requiresApproval: false, idempotent: false, sideEffectLevel: "write", inputSchemaRef: "CreateMilestoneScheduleInput", outputSchemaRef: "CreateMilestoneScheduleOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["milestones","schedule"] },
  { code: "tool_send_email", version: "1.0.0", status: "active", name: "send_email", description: "Send email through approved templates or operator-reviewed content.", category: "communications", ownerAgent: "operations", requiresApproval: true, idempotent: false, sideEffectLevel: "external_write", inputSchemaRef: "SendEmailInput", outputSchemaRef: "SendEmailOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["email","notifications"] },
  { code: "tool_send_sms", version: "1.0.0", status: "active", name: "send_sms", description: "Send SMS through approved workflows or templates.", category: "communications", ownerAgent: "operations", requiresApproval: true, idempotent: false, sideEffectLevel: "external_write", inputSchemaRef: "SendSmsInput", outputSchemaRef: "SendSmsOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["sms","twilio"] },
  { code: "tool_get_permit_status", version: "1.0.0", status: "active", name: "get_permit_status", description: "Retrieve permit status by jurisdiction and record number.", category: "permits", ownerAgent: "permit", requiresApproval: false, idempotent: true, sideEffectLevel: "read", inputSchemaRef: "GetPermitStatusInput", outputSchemaRef: "GetPermitStatusOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["permits","status"] },
  { code: "tool_create_permit_case", version: "1.0.0", status: "draft", name: "create_permit_case", description: "Create internal permit case and checklist package.", category: "permits", ownerAgent: "permit", requiresApproval: false, idempotent: false, sideEffectLevel: "write", inputSchemaRef: "CreatePermitCaseInput", outputSchemaRef: "CreatePermitCaseOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["permits","case"] },
  { code: "tool_create_engagement", version: "1.0.0", status: "draft", name: "create_engagement", description: "Create internal engagement/contracting package for matched project.", category: "engagements", ownerAgent: "marketplace", requiresApproval: true, idempotent: false, sideEffectLevel: "write", inputSchemaRef: "CreateEngagementInput", outputSchemaRef: "CreateEngagementOutput", enabledEnvironments: ["dev","staging","prod"], tags: ["engagement","contracts"] }
];
