[phases.install]
cmds = [
  "corepack enable && corepack prepare pnpm@8.15.9 --activate && pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm turbo build --filter=./apps/web-main"
]

[start]
cmd = "cd apps/web-main && npx next start -p $PORT"
