[phases.install]
cmds = [
  "corepack enable && corepack prepare pnpm@8.15.9 --activate && cd ../.. && pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "cd ../.. && pnpm turbo build --filter=./apps/web-main"
]

[start]
cmd = "npx next start -p $PORT"
