'use server'

/**
 * OS Architecture — an architect's review of a delivered DESIGN CONCEPT
 * (the concept-package products: kitchen, bathroom, addition, whole-home …).
 *
 * The concept is generated by DesignBot / the concept generator into
 * `form_data.conceptOutput` (or `v30ConceptOutput` for AI-automated orders).
 * The architect's decision is recorded on the order as
 * `form_data.architectReview` under their own identity; a withheld approval
 * moves the order to `revision_requested` with the direction for the
 * designer, and an approval appends the sign-off. Nothing here regenerates a
 * concept: that is the designer's act, on the staff desk.
 */
import { revalidatePath } from 'next/cache'
import { assertCurrentLicence, getProfessionalIdentity } from '@/lib/professional-review'
import { getSupabaseAdmin } from '@/lib/supabase-server'
import { orderStatusPatch } from '@/lib/order-status'

export interface ArchitectConceptReview {
  version: 1
  state: 'APPROVED' | 'CHANGES_REQUESTED'
  comment: string | null
  reviewer: { displayName: string; licenceNumber: string | null; licenceState: string | null }
  decidedAt: string
  /** Which generation of the concept was reviewed (bumped by a regeneration). */
  conceptGeneration: number
  history: { state: string; comment: string | null; decidedAt: string; reviewer: string; conceptGeneration: number }[]
}

export async function reviewDesignConcept(formData: FormData) {
  const intakeId = String(formData.get('intakeId') ?? '')
  const decision = String(formData.get('decision') ?? '')
  const comment = String(formData.get('comment') ?? '').trim()
  if (!['APPROVED', 'CHANGES_REQUESTED'].includes(decision)) throw new Error('Invalid decision.')
  if (decision === 'CHANGES_REQUESTED' && comment.length < 10) {
    throw new Error('Direction for the designer is required when approval is withheld.')
  }

  const identity = await getProfessionalIdentity()
  if (!identity?.profile || identity.discipline !== 'architect') throw new Error('An architect profile is required.')
  assertCurrentLicence(identity.profile)

  const supabase = getSupabaseAdmin()
  const { data: row, error } = await supabase
    .from('public_intake_leads')
    .select('id, project_path, form_data, status')
    .eq('id', intakeId)
    .maybeSingle()
  if (error || !row) throw new Error('Order not found.')
  const fd = (row.form_data ?? {}) as Record<string, unknown>
  if (!fd.conceptOutput && !fd.v30ConceptOutput) throw new Error('This order has no delivered design concept to review.')

  const prior = fd.architectReview as ArchitectConceptReview | undefined
  const generation = Number(fd.conceptGeneration ?? 0)
  const now = new Date().toISOString()
  const reviewer = {
    displayName: identity.profile.displayName,
    licenceNumber: identity.profile.licenseNumber ?? null,
    licenceState: identity.profile.licenseState ?? null,
  }
  const record: ArchitectConceptReview = {
    version: 1,
    state: decision as ArchitectConceptReview['state'],
    comment: comment || null,
    reviewer,
    decidedAt: now,
    conceptGeneration: generation,
    history: [
      ...(prior?.history ?? []),
      { state: decision, comment: comment || null, decidedAt: now, reviewer: reviewer.displayName, conceptGeneration: generation },
    ],
  }

  const statusPatch = decision === 'APPROVED'
    ? orderStatusPatch('delivered', { reason: `Design concept reviewed and approved by ${reviewer.displayName} (architect).`, actor: `architect:${identity.user.id}` })
    : orderStatusPatch('revision_requested', { reason: `Architect ${reviewer.displayName} requested changes to the design concept: ${comment}`, actor: `architect:${identity.user.id}` })

  const patch: Record<string, unknown> = {
    ...fd,
    architectReview: record,
    ...statusPatch,
    ...(decision === 'CHANGES_REQUESTED' ? { fulfillmentStatus: 'awaiting_designer', designerDirection: comment } : {}),
  }
  const { error: updateError } = await supabase
    .from('public_intake_leads')
    .update({ form_data: patch, status: decision === 'APPROVED' ? 'delivered' : 'revision_requested' })
    .eq('id', intakeId)
  if (updateError) throw new Error(`Could not record the review: ${updateError.message}`)

  revalidatePath('/architect/review')
}
