export interface Product {
  slug: string
  name: string
  tagline: string
  price: string
  priceNote: string
  label: string
  badge: string
  badgeColor: string
  imageUrl: string
  description: string
  includes: string[]
  steps: { n: string; title: string; body: string }[]
  forWho: string
  cta: string
  ctaHref: string
  stripeEnvVar?: string
  faq: { q: string; a: string }[]
}

export const PRODUCTS: Record<string, Product> = {
  'ai-design': {
    slug: 'ai-design',
    name: 'AI Design Report',
    tagline: 'Floor plan, zoning check, cost band, and permit scope — in 24 hours.',
    price: 'Starting at $395',
    priceNote: 'one-time · no subscription',
    label: 'AI design engine',
    badge: 'Start here',
    badgeColor: '#E8793A',
    imageUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=900&q=70&auto=format&fit=crop',
    description: 'Upload photos of your space or lot. Our AI generates a concept floor plan, a design brief, and a room-by-room scope outline. A staff architect checks zoning, structural risk, permit complexity, and cost band. The full report lands in your inbox within 24 hours — no architect fee, no phone calls.',
    includes: [
      'AI-generated concept floor plan sketch',
      'Design brief and room-by-room scope notes',
      'Zoning compliance check for your jurisdiction',
      'Structural risk rating (1–5 scale)',
      'Cost band estimate (low–high range)',
      'Permit risk rating and estimated timeline',
      'Contractor scope outline for bidding',
      'Staff review before every delivery',
    ],
    steps: [
      { n: '01', title: 'Upload your photos', body: 'Submit 3–10 photos of your space or lot through our intake form. Add a description of what you want to build.' },
      { n: '02', title: 'AI generates your concept', body: 'Our model produces a floor plan sketch, scope outline, and initial cost band within 2 hours of submission.' },
      { n: '03', title: 'Staff review', body: 'A licensed professional checks zoning data, structural risk, permit complexity, and cost band accuracy for your specific jurisdiction.' },
      { n: '04', title: 'Delivery in 24 hours', body: 'Your complete AI Design Report arrives by email with a PDF and dashboard link. You own the content outright.' },
    ],
    forWho: 'Homeowners, project owners, and developers in the DC/Maryland/Virginia metro area planning a remodel, addition, ADU, or new construction project who want to understand feasibility and cost before hiring an architect or contractor.',
    cta: 'Get your AI Design Report',
    ctaHref: '/concept',
    stripeEnvVar: 'STRIPE_PRICE_CONCEPT_VALIDATION',
    faq: [
      { q: 'Is this a real floor plan I can use for permits?', a: 'No. The AI Design Report is a concept-level sketch for planning and budgeting. Projects requiring permit-ready drawings (DCS 41+ or budget $65K+) are routed to a licensed architect — your report includes this assessment.' },
      { q: 'What if my project is complex?', a: 'We score every project with a Design Complexity Score (DCS). If yours is above the threshold, we tell you upfront and explain what full design services look like.' },
      { q: 'Can I use the cost band when getting contractor bids?', a: 'Yes. Many homeowners use the cost band to evaluate whether incoming bids are in range. The band is based on current DMV labor and material rates.' },
      { q: 'What happens after I get the report?', a: 'You can stop there, order permit services, get a detailed cost estimate, or request contractor matching — all separately and optionally.' },
    ],
  },
  'permit-package': {
    slug: 'permit-package',
    name: 'Permit Package',
    tagline: 'We file your permit, track it, and respond to comments. You get a link.',
    price: 'Starting at $149',
    priceNote: 'per permit scope · no subscription',
    label: 'Permit services',
    badge: 'DC · MD · VA',
    badgeColor: '#4A8FA8',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&q=70&auto=format&fit=crop',
    description: 'We know Montgomery DPS, Fairfax LDS, DC DOB, Prince William BOCS, and every other DMV jurisdiction. We fill out your application, prepare your drawings package, submit to the right agency, respond to comment letters, and notify you when it is approved. You do not call the permit office.',
    includes: [
      'Jurisdiction identification and fee schedule',
      'Application preparation (all forms, signatures)',
      'Drawings package preparation where required',
      'Electronic or in-person submission to the correct agency',
      'Comment letter response (first two rounds included)',
      'Status tracking with dashboard link and email notifications',
      'Permit card delivery upon approval',
      'Final permit package archival for your records',
    ],
    steps: [
      { n: '01', title: 'Submit your project details', body: 'Tell us your address, project type, and whether you have existing drawings. We identify the exact jurisdiction and fee schedule.' },
      { n: '02', title: 'We prepare your package', body: 'Our team prepares all application forms, drawings where required, and supporting documents for your specific jurisdiction.' },
      { n: '03', title: 'We submit and track', body: 'We submit electronically or in person, depending on the agency. You receive a tracking link and email updates at every status change.' },
      { n: '04', title: 'We handle comments', body: 'If the reviewer sends a comment letter, we prepare and submit the response. First two rounds included at no extra charge.' },
    ],
    forWho: 'Homeowners, investors, and developers in DC, Maryland, and Virginia who need a permit filed correctly the first time without navigating agency websites, phone trees, or comment letter processes.',
    cta: 'Start permit filing',
    ctaHref: '/permits',
    stripeEnvVar: 'STRIPE_PRICE_PERMIT_PACKAGE',
    faq: [
      { q: 'What permit tiers are available?', a: 'Simple Permit Filing ($149), Full Permit Package ($950, most common), Permit Coordination ($2,750), and Permit Expediting ($5,500). The right tier depends on your project type and jurisdiction.' },
      { q: 'Do I need drawings to get a permit?', a: 'It depends on the scope. Simple residential permits often need only forms and photos. Structural changes, additions, and ADUs require stamped drawings — we coordinate your design professional if needed.' },
      { q: 'How long does DMV permitting take?', a: 'Fairfax residential: 2–4 weeks. Montgomery DPS residential: 4–8 weeks. DC DOB with plan review: 2–5 months. We include current average timelines for your jurisdiction in every quote.' },
      { q: 'What if the permit is denied?', a: 'Denials are uncommon when packages are prepared correctly. If a denial occurs, we review and advise on next steps at no additional charge for the first cycle.' },
    ],
  },
  'cost-estimate': {
    slug: 'cost-estimate',
    name: 'Detailed Cost Estimate',
    tagline: 'Trade-by-trade breakdown, RSMeans data, and human review. Lender-ready.',
    price: 'Starting at $595',
    priceNote: 'one-time · no subscription',
    label: 'Cost estimation',
    badge: 'RSMeans data',
    badgeColor: '#4A8FA8',
    imageUrl: 'https://images.unsplash.com/photo-1551836022-4c4c79ecde51?w=900&q=70&auto=format&fit=crop',
    description: 'A human-reviewed, trade-by-trade cost breakdown validated against current RSMeans unit cost data for the DMV market. Includes labor, materials, equipment, overhead, and contractor markup. Formatted for lenders, investors, and contractor negotiations.',
    includes: [
      'Trade-by-trade line item breakdown (CSI MasterFormat)',
      'RSMeans unit cost validation for DMV market rates',
      'Labor and material separation per trade',
      'Overhead, profit, and contingency line items',
      'Three-tier summary: base / mid / high scenario',
      'Lender-ready PDF with licensed estimator sign-off',
      'Scope assumptions and exclusions clearly stated',
      'Digital file for contractor comparison',
    ],
    steps: [
      { n: '01', title: 'Submit your scope', body: 'Share your project scope, AI Design Report (if you have one), any existing drawings, and your property address.' },
      { n: '02', title: 'Estimator review', body: 'A licensed estimator reviews your scope against current DMV labor and material rates using RSMeans data.' },
      { n: '03', title: 'Draft and revisions', body: 'You receive a draft estimate within 3–5 business days. One round of scope revisions is included.' },
      { n: '04', title: 'Final delivery', body: 'Signed, lender-ready PDF delivered with a digital spreadsheet for contractor comparison.' },
    ],
    forWho: 'Homeowners evaluating contractor bids, investors preparing pro formas, project owners applying for construction loans, and developers needing bankable cost documentation.',
    cta: 'Order cost estimate',
    ctaHref: '/concept',
    stripeEnvVar: 'STRIPE_PRICE_COST_ESTIMATE',
    faq: [
      { q: 'Is this the same as the AI cost band in the Design Report?', a: 'No. The AI cost band is a planning range. The Detailed Cost Estimate is a line-item breakdown reviewed by a licensed estimator and signed for lender submission.' },
      { q: 'Do I need drawings first?', a: 'Not always. For scopes under $150K, a written scope description is often sufficient. For larger projects, we recommend at least schematic drawings.' },
      { q: 'Will contractors accept this estimate?', a: 'Contractors often use our estimates as a baseline when scoping their own bids. Significant deviations from your estimate are a signal to ask questions.' },
      { q: 'What is the Certified Cost Estimate vs this one?', a: 'The Certified Cost Estimate ($1,850) adds full notarized sign-off and is accepted by virtually all DMV lenders. The Detailed Estimate ($595) covers most residential and small commercial needs.' },
    ],
  },
  'adu-bundle': {
    slug: 'adu-bundle',
    name: 'ADU Concept + Permit Package',
    tagline: 'Floor plan, zoning check, cost band, and full permit preparation — bundled for ADU projects.',
    price: '$1,345',
    priceNote: 'bundle · save $395 vs. individual',
    label: 'Project bundle',
    badge: 'Bundle savings',
    badgeColor: '#E8793A',
    imageUrl: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=900&q=70&auto=format&fit=crop',
    description: 'ADUs require both a concept design and a permit — this bundle delivers both at a reduced price. We start with an AI Design Report to validate your lot\'s ADU eligibility, setback compliance, and design options. Then we file the permit package.',
    includes: [
      'Everything in AI Design Report ($395 value)',
      'ADU lot eligibility and setback check',
      'Concept floor plan with ADU-specific zoning overlay',
      'Permit path identification (administrative vs. full review)',
      'Everything in Full Permit Package ($950 value)',
      'ADU-specific application forms for your jurisdiction',
      'Separate utility connection documentation where required',
      'Priority processing (ADUs are high-demand in DMV)',
    ],
    steps: [
      { n: '01', title: 'Lot eligibility check', body: 'We verify your parcel\'s setbacks, lot coverage, FAR, and jurisdiction-specific ADU rules before anything else.' },
      { n: '02', title: 'AI Design Report', body: 'Concept floor plan, cost band, and permit risk delivered within 24 hours of lot eligibility confirmation.' },
      { n: '03', title: 'Permit preparation', body: 'We prepare the full ADU permit package including all required forms, plans, and supporting documentation.' },
      { n: '04', title: 'Submission and tracking', body: 'We submit and track your ADU permit to approval, handling all comment responses.' },
    ],
    forWho: 'Homeowners planning a detached ADU, attached ADU, garage conversion, or in-law suite in the DC/Maryland/Virginia metro area who want concept validation and permit filing in one package.',
    cta: 'Start your ADU project',
    ctaHref: '/concept?q=ADU',
    stripeEnvVar: 'STRIPE_PRICE_ADU_BUNDLE',
    faq: [
      { q: 'Does my jurisdiction allow ADUs?', a: 'All DMV jurisdictions allow some form of ADU, but rules vary significantly by county. The eligibility check in your report will confirm exactly what is permitted on your parcel.' },
      { q: 'Do I need an architect for an ADU?', a: 'Detached ADUs under 750 sq ft often do not require a licensed architect for the permit. Larger ADUs and those requiring structural modifications do. Your report will tell you.' },
      { q: 'Can I get contractor matching after this?', a: 'Yes. After your permit is filed, we can match you with verified contractors who have completed ADU projects in your county.' },
      { q: 'What is the total cost to build an ADU?', a: 'Detached ADUs in the DMV typically run $150K–$350K depending on size, finishes, and site conditions. Your AI Design Report cost band will give you a project-specific range.' },
    ],
  },
  'landscape': {
    slug: 'landscape',
    name: 'Landscape Design & Install',
    tagline: 'Beds, hardscape, drainage, and planting — designed and installed by verified landscape contractors.',
    price: 'Custom quote',
    priceNote: 'per project · no upfront fee',
    label: 'Outdoor services',
    badge: 'Design + Install',
    badgeColor: '#3A7D52',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=900&q=70&auto=format&fit=crop',
    description: 'From a simple bed refresh to a full outdoor living transformation — we design the space, scope the work, match you with a verified landscape contractor, and hold payments in escrow until you approve each milestone.',
    includes: [
      'Site assessment and design consultation',
      'Landscape design plan with plant selection',
      'Hardscape layout (patios, walkways, retaining walls)',
      'Drainage and grading assessment',
      'Irrigation system design (if applicable)',
      'Verified contractor matching and bid comparison',
      'Milestone-based payment escrow',
      'Installation oversight and sign-off',
    ],
    steps: [
      { n: '01', title: 'Describe your vision', body: 'Tell us what you want to achieve — privacy screening, outdoor living, curb appeal, or garden beds. Photos of your space help.' },
      { n: '02', title: 'Design plan', body: 'We produce a design plan with plant palette, hardscape layout, and installation scope.' },
      { n: '03', title: 'Contractor matching', body: 'We match you with 2–3 verified landscape contractors who bid on your specific scope.' },
      { n: '04', title: 'Build and sign-off', body: 'Your contractor installs the work. Payments release from escrow only after you approve each milestone.' },
    ],
    forWho: 'Homeowners who want a professionally designed and installed outdoor space without the effort of sourcing contractors, managing bids, or worrying about payment disputes.',
    cta: 'Get a landscape quote',
    ctaHref: '/homeowners/garden-farming',
    faq: [
      { q: 'Do I need a permit for landscaping?', a: 'Most planting and bed work does not require a permit. Retaining walls over 4 feet, significant grading, and some structures do. We identify permit requirements as part of scope development.' },
      { q: 'How are landscape contractors verified?', a: 'State license check, liability insurance verification, bond verification, identity check, and credentials review. Every contractor in our network is screened for licensing, insurance, and project fit.' },
      { q: 'How does milestone payment work?', a: 'Your project funds are held in escrow. They release to the contractor only after you approve a completed milestone. Final retainage releases after punch-list sign-off.' },
      { q: 'What areas do you cover?', a: 'DC, Maryland (Montgomery, Prince George\'s, Howard, Anne Arundel), and Northern Virginia (Fairfax, Arlington, Alexandria, Prince William, Loudoun).' },
    ],
  },
  'pm-advisory': {
    slug: 'pm-advisory',
    name: 'PM Advisory',
    tagline: 'Monthly site inspection, photo report, milestone sign-off, and issue log for your active build.',
    price: 'Starting at $950',
    priceNote: 'per project · billed at milestones',
    label: 'Construction management',
    badge: 'Most common',
    badgeColor: '#4A8FA8',
    imageUrl: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=900&q=70&auto=format&fit=crop',
    description: 'A professional construction manager assigned to your project monitors progress, documents conditions, reviews pay applications, and flags issues before they become expensive problems. You focus on the outcome — we track the details.',
    includes: [
      'Monthly site visit with photographic documentation',
      'Milestone verification before payment release',
      'Pay application review and approval recommendation',
      'Issue log and punch list management',
      'RFI (Request for Information) routing and tracking',
      'Contractor communication on your behalf',
      'Progress report emailed after every site visit',
      'Final punch-list walk and sign-off',
    ],
    steps: [
      { n: '01', title: 'Project onboarding', body: 'We review your contract, schedule, and approved plans. Your PM is assigned and introduced to your contractor.' },
      { n: '02', title: 'Monthly site visits', body: 'Your PM visits the site at every major milestone. Photos, conditions, and progress are documented in your dashboard.' },
      { n: '03', title: 'Milestone approvals', body: 'Before any payment releases from escrow, your PM verifies the work is complete and matches the approved scope.' },
      { n: '04', title: 'Closeout', body: 'Final punch-list walk, sign-off, and project documentation package delivered to you.' },
    ],
    forWho: 'Homeowners and project owners running an active construction project who want professional oversight without hiring a full-time owner\'s representative.',
    cta: 'Add PM Advisory to your project',
    ctaHref: '/developers',
    stripeEnvVar: 'STRIPE_PRICE_PM_ADVISORY',
    faq: [
      { q: 'What is the difference between PM Advisory and PM Oversight?', a: 'PM Advisory ($950) includes monthly visits and milestone approvals. PM Oversight ($2,950) includes weekly visits, full schedule management, and proactive issue escalation.' },
      { q: 'Do I need PM Advisory if I have a good contractor?', a: 'Even with a trusted contractor, an independent PM protects your interests. Pay application review alone often saves more than the fee.' },
      { q: 'Can PM Advisory be added after construction starts?', a: 'Yes. We can onboard mid-project. We conduct a condition assessment at onboarding to establish a baseline.' },
      { q: 'What happens when my PM finds a problem?', a: 'Your PM documents the issue, notifies the contractor, and escalates to you with a recommended resolution. Payment is held at that milestone until resolution.' },
    ],
  },
  'garden': {
    slug: 'garden',
    name: 'Garden Design & Install',
    tagline: 'Raised beds, composting systems, herb gardens, and edible landscapes — designed and planted.',
    price: 'Custom quote',
    priceNote: 'per project · no upfront fee',
    label: 'Outdoor services',
    badge: 'Design + Install',
    badgeColor: '#3A7D52',
    imageUrl: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=900&q=70&auto=format&fit=crop',
    description: 'From a simple raised bed to a full edible landscape transformation — we design your garden system, source verified landscape contractors, and manage installation through milestone escrow.',
    includes: [
      'Garden design plan with bed layout and plant selection',
      'Soil amendment and composting system recommendations',
      'Raised bed construction design and material spec',
      'Drip irrigation layout (if applicable)',
      'Seasonal planting schedule',
      'Verified contractor matching and bid comparison',
      'Milestone-based payment escrow',
      'First-season maintenance guide',
    ],
    steps: [
      { n: '01', title: 'Garden goals assessment', body: 'Tell us what you want to grow, how much space you have, and your maintenance commitment. Photos help.' },
      { n: '02', title: 'Design plan', body: 'We produce a garden layout with bed placement, plant selection, and irrigation design.' },
      { n: '03', title: 'Contractor matching', body: 'Verified landscape contractors bid on your scope. We help you evaluate bids.' },
      { n: '04', title: 'Installation', body: 'Your contractor installs the beds and plants. Payments hold in escrow until you approve each phase.' },
    ],
    forWho: 'Homeowners who want a productive, well-designed outdoor food or ornamental garden space installed by a verified professional.',
    cta: 'Get a garden design quote',
    ctaHref: '/concept-engine/garden',
    faq: [
      { q: 'Do I need a permit for garden beds?', a: 'Raised beds and ground-level planting rarely require permits. Structures over a certain height or attached to the house may. We confirm permit needs for every scope.' },
      { q: 'What plants work well in the DMV?', a: 'The DMV sits in USDA zones 6b–7b. Our garden plans are designed specifically for your zone, sun exposure, and soil type.' },
      { q: 'Can you do just the design without installation?', a: 'Yes. A design-only garden plan is available at a reduced fee. You can use it to get contractor bids or DIY.' },
      { q: 'How much does a basic raised bed garden cost?', a: 'A 3-bed starter system typically runs $2,500–$6,000 installed, depending on size, materials, and soil. Full edible landscape transformations run $8,000–$25,000+.' },
    ],
  },
  'exterior': {
    slug: 'exterior',
    name: 'Exterior Renovation',
    tagline: 'Deck, siding, roofing, windows — permit filing from $149 included in most scopes.',
    price: 'Starting at $149',
    priceNote: 'permit filing · project cost varies',
    label: 'Exterior services',
    badge: 'Permit included',
    badgeColor: '#4A8FA8',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=70&auto=format&fit=crop',
    description: 'Exterior renovation projects — decks, siding, roofing, window replacements, and façade upgrades — almost always require a permit in the DMV. We identify the exact permit path, file the application, and match you with verified exterior contractors.',
    includes: [
      'Permit path identification for your jurisdiction',
      'Application preparation and submission',
      'Material specification review',
      'Verified contractor matching for your trade scope',
      'Bid comparison and selection support',
      'Milestone-based payment escrow',
      'Inspection scheduling and tracking',
      'Final permit card and sign-off documentation',
    ],
    steps: [
      { n: '01', title: 'Describe your exterior project', body: 'Tell us what you are replacing or adding — deck, siding, roofing, windows. We identify the permit path and costs.' },
      { n: '02', title: 'Permit filing', body: 'We file your permit with the correct jurisdiction. Permit filing starts at $149 for simple scopes.' },
      { n: '03', title: 'Contractor matching', body: 'Verified exterior contractors bid on your scope. We provide comparison support.' },
      { n: '04', title: 'Build and sign-off', body: 'Your contractor completes the work. Inspections are scheduled and tracked. Final documents delivered.' },
    ],
    forWho: 'Homeowners replacing siding, roofing, or windows, adding a deck or porch, or upgrading their home\'s exterior in the DC/Maryland/Virginia metro area.',
    cta: 'Start your exterior project',
    ctaHref: '/concept-engine/exterior',
    faq: [
      { q: 'Does a deck always need a permit?', a: 'In the DMV, decks over a certain height (usually 30 inches from grade) require a permit in virtually all jurisdictions. Ground-level patios typically do not.' },
      { q: 'Does roofing require a permit?', a: 'Replacement roofing (same material, same slope) often qualifies for a simple residential permit or none at all. Structural roof changes require full permits.' },
      { q: 'How long does an exterior permit take?', a: 'Simple residential exterior permits in most DMV jurisdictions take 1–3 weeks. We include current timelines for your specific county in every quote.' },
      { q: 'Can I DIY exterior work without a permit?', a: 'You can, but unpermitted work creates liability at sale time and may not pass a home inspection. Kealee always recommends filing.' },
    ],
  },
  'basement': {
    slug: 'basement',
    name: 'Basement Finish Concept',
    tagline: 'Floor plan options, egress check, structural flag, and permit scope. Staff reviewed in 24 hours.',
    price: 'Starting at $395',
    priceNote: 'one-time · no subscription',
    label: 'AI design engine',
    badge: 'AI design ready',
    badgeColor: '#E8793A',
    imageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=70&auto=format&fit=crop',
    description: 'Basement finishing projects are among the most permit-sensitive in the DMV. Egress window requirements, ceiling height minimums, electrical panel access, and HVAC zoning all affect what you can build. Our AI Design Report checks all of these and delivers a concept plan in 24 hours.',
    includes: [
      'AI-generated basement floor plan (2–3 layout options)',
      'Egress window compliance check for your jurisdiction',
      'Ceiling height assessment and recommendations',
      'Structural column and beam layout noting',
      'Electrical panel access compliance check',
      'HVAC zoning and ventilation assessment',
      'Permit path and estimated timeline for your county',
      'Staff review before delivery',
    ],
    steps: [
      { n: '01', title: 'Submit photos and dimensions', body: 'Upload photos of your unfinished basement including the electrical panel, HVAC system, and all walls. Include current dimensions if available.' },
      { n: '02', title: 'AI generates layout options', body: 'Our model produces 2–3 floor plan options that respect egress, structural, and mechanical constraints.' },
      { n: '03', title: 'Staff compliance review', body: 'A licensed professional checks egress window requirements, ceiling height minimums, and permit complexity for your jurisdiction.' },
      { n: '04', title: 'Delivery in 24 hours', body: 'Your complete basement concept report arrives with floor plan options, compliance notes, and next steps.' },
    ],
    forWho: 'Homeowners in the DC/Maryland/Virginia metro area who want to finish their basement and need to understand what is feasible before hiring a contractor.',
    cta: 'Get your basement concept',
    ctaHref: '/concept?q=Basement+finish',
    stripeEnvVar: 'STRIPE_PRICE_BASEMENT_CONCEPT',
    faq: [
      { q: 'Does finishing a basement always require a permit?', a: 'Yes, in virtually all DMV jurisdictions. Framing, electrical, plumbing, and HVAC work in a basement requires permits and inspections.' },
      { q: 'What is an egress window and do I need one?', a: 'An egress window is a minimum-size window that allows emergency exit. If your basement will have a bedroom, virtually all DMV jurisdictions require one.' },
      { q: 'My basement has low ceilings. Can it still be finished?', a: 'Minimum ceiling height requirements vary by jurisdiction (typically 7\'0" finished). Your report will check your specific measurements against your county\'s requirements.' },
      { q: 'How much does basement finishing cost in the DMV?', a: 'Typical range is $35–$65 per square foot depending on scope and finishes. A 1,000 sq ft basement typically runs $35,000–$65,000 fully finished.' },
    ],
  },
  'certified-estimate': {
    slug: 'certified-estimate',
    name: 'Certified Cost Estimate',
    tagline: 'Licensed estimator sign-off, RSMeans citations, investor-ready format. Accepted by most DMV lenders.',
    price: '$1,850',
    priceNote: 'one-time · no subscription',
    label: 'Cost estimation',
    badge: 'Lender ready',
    badgeColor: '#4A8FA8',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=900&q=70&auto=format&fit=crop',
    description: 'The Certified Cost Estimate is the highest-tier cost documentation Kealee produces. It includes a full trade-by-trade breakdown, notarized licensed estimator sign-off, RSMeans unit cost citations, and an investor-grade format accepted by virtually all DMV construction lenders and equity investors.',
    includes: [
      'Full trade-by-trade line item breakdown (CSI MasterFormat)',
      'RSMeans unit cost citations with source documentation',
      'Notarized licensed estimator signature page',
      'Three-scenario analysis (base / mid / high)',
      'Direct material and labor separation per trade',
      'General conditions, overhead, and profit schedule',
      'Contingency analysis by risk category',
      'Investor-grade executive summary (2 pages)',
      'Digital file in Excel and PDF format',
    ],
    steps: [
      { n: '01', title: 'Submit scope documentation', body: 'Share your drawings, project scope, property address, and any prior estimates. Schematic or design-development drawings preferred.' },
      { n: '02', title: 'Estimator assignment', body: 'A licensed estimator with DMV market experience is assigned. Typical turnaround is 5–7 business days.' },
      { n: '03', title: 'Draft review', body: 'You receive a draft for review. One revision round included. Major scope changes may require a scope change order.' },
      { n: '04', title: 'Certified delivery', body: 'Notarized signed estimate delivered in PDF and Excel. Accepted by most DMV lenders for construction loan draw schedules.' },
    ],
    forWho: 'Real estate investors, developers, and project owners applying for construction financing, raising investor capital, or establishing a definitive cost baseline for a complex project.',
    cta: 'Order certified estimate',
    ctaHref: '/concept?q=Certified+estimate',
    stripeEnvVar: 'STRIPE_PRICE_CERTIFIED_ESTIMATE',
    faq: [
      { q: 'Which lenders accept this estimate?', a: 'Most DMV community banks, credit unions, and private construction lenders accept our Certified Cost Estimate. We recommend confirming with your specific lender before ordering.' },
      { q: 'Do I need drawings first?', a: 'For the Certified Estimate, yes — at least schematic-level drawings are required for a reliable line-item breakdown. We can coordinate a design professional if needed.' },
      { q: 'How is this different from the Detailed Estimate ($595)?', a: 'The Certified Estimate adds notarized sign-off, full RSMeans source documentation, and investor-grade formatting. Most individual homeowners do not need certification — the Detailed Estimate covers their needs.' },
      { q: 'Can this be used in a dispute or litigation?', a: 'Yes. The licensed estimator signature and documented methodology make this suitable for use in construction disputes, insurance claims, and legal proceedings.' },
    ],
  },
  'historic-renovation': {
    slug: 'historic-renovation',
    name: 'Historic Renovation',
    tagline: 'Preservation-compliant design, historic review board submissions, and verified specialty contractors.',
    price: 'Starting at $395',
    priceNote: 'per service · custom scope',
    label: 'Specialty renovation',
    badge: 'Preservation-compliant',
    badgeColor: '#3A7D52',
    imageUrl: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=900&q=70&auto=format&fit=crop',
    description: 'Historic properties in DC, Maryland, and Virginia are subject to additional review processes — Historic Preservation Review Boards (HPRB), local historic district regulations, and Secretary of the Interior standards. We navigate these for you while matching you with contractors experienced in preservation-compliant work.',
    includes: [
      'Historic district and overlay identification',
      'Certificate of Appropriateness (COA) guidance',
      'Review board submission preparation',
      'Secretary of the Interior standards compliance check',
      'Matching with preservation-experienced contractors',
      'Material specification guidance for historic compliance',
      'Permit path identification (historic + building permit)',
      'Staff review by preservation-experienced professional',
    ],
    steps: [
      { n: '01', title: 'Property research', body: 'We confirm your property\'s historic designation, overlay zone, and applicable review board jurisdiction.' },
      { n: '02', title: 'Compliance assessment', body: 'Your proposed work is assessed against Secretary of the Interior standards and local historic district guidelines.' },
      { n: '03', title: 'COA submission', body: 'We prepare and submit the Certificate of Appropriateness application with the required documentation.' },
      { n: '04', title: 'Build with verified contractors', body: 'We match you with contractors experienced in historic preservation work in your jurisdiction.' },
    ],
    forWho: 'Owners of historic properties in DC (HPRB), Maryland (MHT), or Virginia (VDHR) historic districts who need expert guidance on what changes are permitted and how to get them approved.',
    cta: 'Start your historic renovation',
    ctaHref: '/concept?q=Historic+renovation',
    stripeEnvVar: 'STRIPE_PRICE_HISTORIC_RENOVATION',
    faq: [
      { q: 'How do I know if my property is in a historic district?', a: 'We check this as the first step. Many properties in DC, Annapolis, Alexandria, Frederick, and other DMV communities are in local or national historic districts without the owner\'s knowledge.' },
      { q: 'Can I still renovate a historic property?', a: 'Yes — you just need approval for changes that are visible from public rights-of-way, and must use compatible materials. Interior changes typically do not require historic review.' },
      { q: 'How long does historic review take?', a: 'DC HPRB: 4–8 weeks. Most Maryland local review boards: 4–6 weeks. Virginia DHR: varies. We include current timelines in every assessment.' },
      { q: 'What if my renovation is denied?', a: 'Denials are uncommon when scopes are designed for compliance from the start. We design your submission to meet standards before it goes to the board.' },
    ],
  },
  'water-mitigation': {
    slug: 'water-mitigation',
    name: 'Water Mitigation & Drainage',
    tagline: 'Grading, French drains, waterproofing, and sump systems — scoped, permitted, and installed.',
    price: 'Starting at $395',
    priceNote: 'assessment · project cost varies',
    label: 'Specialty services',
    badge: 'Site assessment',
    badgeColor: '#4A8FA8',
    imageUrl: 'https://images.unsplash.com/photo-1558478551-1a378f63328e?w=900&q=70&auto=format&fit=crop',
    description: 'Water intrusion is the leading cause of structural damage in DMV homes. Whether you have basement water infiltration, yard drainage issues, or foundation seepage, we assess the source, scope the solution, file permits where required, and match you with verified waterproofing and drainage contractors.',
    includes: [
      'Site drainage assessment and water source identification',
      'Grading plan recommendation',
      'French drain and surface drain system design',
      'Basement waterproofing specification',
      'Sump pump system recommendation',
      'Permit path identification (grading permits where required)',
      'Verified contractor matching for drainage and waterproofing',
      'Milestone-based payment escrow',
    ],
    steps: [
      { n: '01', title: 'Water issue assessment', body: 'Describe your water problem — basement seepage, yard flooding, standing water, or foundation cracks. Photos of affected areas help.' },
      { n: '02', title: 'Site analysis', body: 'We analyze your property\'s grading, soil type, and proximity to water table to identify the source and best mitigation approach.' },
      { n: '03', title: 'Scope and permit', body: 'We scope the recommended solution and file any required grading or construction permits.' },
      { n: '04', title: 'Contractor installation', body: 'Verified drainage and waterproofing contractors bid on your scope. Payments hold in escrow until you approve each phase.' },
    ],
    forWho: 'Homeowners experiencing basement water infiltration, yard drainage problems, foundation seepage, or surface water flooding in the DC/Maryland/Virginia metro area.',
    cta: 'Get a drainage assessment',
    ctaHref: '/concept?q=Water+mitigation',
    stripeEnvVar: 'STRIPE_PRICE_WATER_MITIGATION',
    faq: [
      { q: 'Does water mitigation work require a permit?', a: 'Exterior grading changes and some structural waterproofing systems require permits. Interior sump systems and French drains often do not, but requirements vary by jurisdiction.' },
      { q: 'What is the difference between waterproofing and drainage?', a: 'Drainage manages surface and subsurface water movement away from your property. Waterproofing prevents water from penetrating your foundation or basement walls. Many projects require both.' },
      { q: 'How do I know if my issue is drainage or foundation?', a: 'Our site assessment distinguishes between surface drainage, subsurface water table, and structural foundation issues. Each has a different solution path.' },
      { q: 'How much does water mitigation typically cost?', a: 'French drain systems run $3,000–$8,000. Full basement waterproofing with interior drainage and sump runs $8,000–$20,000. Exterior excavation waterproofing runs $15,000–$40,000+.' },
    ],
  },
  'kitchen-remodel': {
    slug: 'kitchen-remodel',
    name: 'Kitchen Remodel',
    tagline: 'Floor plan, layout options, permit scope, and cost band — in 24 hours.',
    price: 'Starting at $395',
    priceNote: 'one-time · no subscription',
    label: 'AI design engine',
    badge: 'Most common project',
    badgeColor: '#E8793A',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=70&auto=format&fit=crop',
    description: 'Kitchen remodels are the most common project in the DMV — and the most likely to encounter permit surprises. We identify electrical, plumbing, and structural permit requirements for your specific kitchen scope and deliver a concept floor plan with layout options.',
    includes: [
      'AI-generated kitchen floor plan (multiple layout options)',
      'Cabinet and appliance placement recommendations',
      'Electrical and plumbing permit scope identification',
      'Structural wall assessment (load-bearing flag)',
      'Cost band estimate for your scope level',
      'Material tier recommendations (good/better/best)',
      'Contractor scope outline for bidding',
      'Staff review before delivery',
    ],
    steps: [
      { n: '01', title: 'Submit kitchen photos', body: 'Upload 5–10 photos including all four walls, the ceiling, electrical panel location, and existing layout. Describe your goals.' },
      { n: '02', title: 'AI generates layouts', body: 'Multiple layout options are generated with appliance placement, cabinet layout, and island options where applicable.' },
      { n: '03', title: 'Staff review', body: 'A professional checks permit requirements, structural flags, and cost band accuracy for your specific scope.' },
      { n: '04', title: 'Report delivery', body: 'Your complete kitchen remodel concept report arrives within 24 hours with floor plans, scope notes, and cost band.' },
    ],
    forWho: 'Homeowners planning a kitchen update, gut renovation, or layout change in the DC/Maryland/Virginia metro area who want to understand scope, permits, and cost before hiring a contractor.',
    cta: 'Start your kitchen concept',
    ctaHref: '/concept?q=Kitchen+remodel',
    faq: [
      { q: 'Does a kitchen remodel require a permit?', a: 'Cosmetic work (paint, hardware, appliance swap) typically does not. Moving walls, adding circuits, relocating plumbing, or structural changes all require permits in every DMV jurisdiction.' },
      { q: 'How much does a kitchen remodel cost in the DMV?', a: 'Minor updates: $15,000–$30,000. Mid-range gut renovation: $45,000–$85,000. Full high-end remodel: $100,000–$200,000+. Your concept report cost band is based on current DMV rates.' },
      { q: 'Do I need an architect for a kitchen remodel?', a: 'Not for most kitchen remodels. Projects involving structural wall removal or significant layout changes may need structural engineering review, which we coordinate.' },
      { q: 'Can I stay in the house during a kitchen remodel?', a: 'Most homeowners stay in the house. We flag potential issues (plumbing shut-off duration, dust containment) in your concept report.' },
    ],
  },
  'adu': {
    slug: 'adu',
    name: 'ADU & In-Law Suite',
    tagline: 'Zoning check, concept plan, permit filing, and contractor matching — all for your ADU.',
    price: 'Starting at $395',
    priceNote: 'one-time · bundle available',
    label: 'AI design engine',
    badge: 'High demand — DMV',
    badgeColor: '#E8793A',
    imageUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=900&q=70&auto=format&fit=crop',
    description: 'ADUs are one of the highest-value additions in the DMV. Before you invest in designs or hire a contractor, we check your lot\'s eligibility, generate a concept layout, and identify your exact permit path. Then we file the permit and match you with ADU-experienced contractors.',
    includes: [
      'Lot setback and ADU eligibility check',
      'AI-generated ADU concept floor plan',
      'Zoning overlay and FAR analysis',
      'Permit path identification (by-right vs. variance)',
      'Utility connection requirements',
      'Cost band estimate for your ADU scope',
      'ADU-specific permit preparation (bundle option)',
      'Contractor matching with ADU track record',
    ],
    steps: [
      { n: '01', title: 'Lot eligibility check', body: 'We verify setbacks, lot coverage, FAR limits, and jurisdiction-specific ADU allowances for your specific parcel.' },
      { n: '02', title: 'Concept floor plan', body: 'AI generates 2–3 ADU layout options sized for your lot constraints.' },
      { n: '03', title: 'Permit filing (optional)', body: 'Add the ADU bundle to get full permit preparation and filing included.' },
      { n: '04', title: 'Contractor matching', body: 'Verified contractors with ADU experience bid on your scope. Payments in escrow.' },
    ],
    forWho: 'Homeowners planning a detached ADU, garage conversion, basement apartment, or in-law suite in the DC/Maryland/Virginia metro area.',
    cta: 'Start your ADU project',
    ctaHref: '/concept?q=ADU',
    faq: [
      { q: 'Is my lot eligible for an ADU?', a: 'Most residential lots in DMV jurisdictions allow at least one ADU type. Eligibility depends on lot size, setbacks, existing coverage, and water/sewer availability.' },
      { q: 'Do ADUs increase property value?', a: 'Yes. DMV appraisers typically add $100K–$250K+ to property value for a finished, permitted ADU, depending on size and finish level.' },
      { q: 'Can I rent my ADU?', a: 'Yes, in all DMV jurisdictions. Some require owner-occupancy of the primary residence. We include this information in your concept report.' },
      { q: 'How long does an ADU permit take?', a: 'By-right ADU permits: 4–8 weeks in most DMV jurisdictions. Projects requiring a variance: 3–6 months. Your report includes current timelines.' },
    ],
  },
  'whole-home': {
    slug: 'whole-home',
    name: 'Whole Home Renovation',
    tagline: 'End-to-end project management for full home renovations from concept through closeout.',
    price: 'Starting at $395',
    priceNote: 'concept report · full-service available',
    label: 'Full service',
    badge: 'Full service available',
    badgeColor: '#E8793A',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=70&auto=format&fit=crop',
    description: 'Whole home renovations are the most complex residential projects — touching every trade, requiring multiple permits, and demanding coordinated project management. We handle the full journey: concept design, permits, contractor selection, escrow payments, and construction oversight.',
    includes: [
      'Whole-home concept design and scope development',
      'Multi-permit coordination (building, electrical, plumbing, HVAC)',
      'Trade-by-trade cost estimate',
      'Verified general contractor selection and bid management',
      'Milestone escrow payments',
      'Construction oversight and site visits',
      'Change order review and approval',
      'Closeout documentation and warranty tracking',
    ],
    steps: [
      { n: '01', title: 'Concept and scoping', body: 'We develop a room-by-room scope with your input, identifying which trades are involved and what permits are required.' },
      { n: '02', title: 'Permits and estimates', body: 'We file all required permits and produce a certified cost estimate for contractor bidding.' },
      { n: '03', title: 'Contractor selection', body: 'Verified general contractors bid on your full scope. We manage the bid process and help you select.' },
      { n: '04', title: 'Construction through closeout', body: 'We oversee construction, manage milestone payments from escrow, and document closeout.' },
    ],
    forWho: 'Homeowners undertaking a major whole-home or significant multi-room renovation in the DMV who want professional oversight from start to finish.',
    cta: 'Start your whole-home project',
    ctaHref: '/concept-engine/whole-home',
    faq: [
      { q: 'How is whole-home renovation priced?', a: 'Start with a $395 concept report. PM Advisory ($950) and PM Oversight ($2,950) add construction oversight. Permit filing is per-permit. Total platform cost typically runs $2,000–$5,000 on a $100K+ project.' },
      { q: 'Do I need a general contractor or individual trades?', a: 'Projects touching 3+ trades are best run by a general contractor. We help you evaluate GC vs. trade-direct approaches in your concept report.' },
      { q: 'How long does a whole-home renovation take?', a: '1,500–2,500 sq ft whole-home: 6–12 months from permit to closeout. Larger homes with structural changes: 12–18 months.' },
      { q: 'Can I live in the house during renovation?', a: 'Usually possible for phased renovations. Full gut renovations often require temporary relocation for 3–6 months. We flag this in your concept report.' },
    ],
  },
  'new-build': {
    slug: 'new-build',
    name: 'New Build / Custom Home',
    tagline: 'Feasibility, architect coordination, permits, and construction management for new construction.',
    price: 'Architect required',
    priceNote: 'projects over $65K require licensed architect',
    label: 'New construction',
    badge: 'Projects over $65K',
    badgeColor: '#1A2B4A',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=70&auto=format&fit=crop',
    description: 'New construction projects require a licensed architect, structural engineer, and civil engineer in most DMV jurisdictions. We coordinate your design team, manage permit submissions, and provide construction oversight — you do not need to manage multiple professionals independently.',
    includes: [
      'Feasibility and zoning analysis',
      'Licensed architect coordination and procurement',
      'Structural and civil engineering coordination',
      'Full permit set preparation and submission',
      'Builder selection and bid management',
      'Construction administration oversight',
      'Draw schedule management with lender',
      'Certificate of occupancy coordination',
    ],
    steps: [
      { n: '01', title: 'Feasibility assessment', body: 'We assess your lot\'s zoning, utility access, setbacks, and buildable envelope before any design investment.' },
      { n: '02', title: 'Design team coordination', body: 'We coordinate architect, structural engineer, and civil engineer procurement and manage the design process.' },
      { n: '03', title: 'Permits and approvals', body: 'We manage all permit submissions, plan review responses, and agency approvals.' },
      { n: '04', title: 'Construction oversight', body: 'Full construction administration, draw management, and certificate of occupancy coordination.' },
    ],
    forWho: 'Landowners, developers, and homeowners planning a custom new home or replacement structure on an existing lot in the DMV metro area.',
    cta: 'Start new build feasibility',
    ctaHref: '/concept?q=New+build',
    faq: [
      { q: 'Why does new construction require an architect?', a: 'All DMV jurisdictions require licensed architect-stamped drawings for new residential construction. There are no exceptions for projects above de minimis size.' },
      { q: 'How long does it take to build a custom home?', a: 'Design and permitting: 6–18 months. Construction: 12–24 months. Total project: 18–36 months from lot purchase to occupancy is typical in the DMV.' },
      { q: 'What does a new build cost in the DMV?', a: 'Costs range from $350–$600+ per square foot for custom construction, depending on finishes, site conditions, and complexity. A 3,000 sq ft custom home typically runs $1.1M–$2.0M+.' },
      { q: 'Do you work with spec builders?', a: 'Yes. We work with both custom builds (owner-directed) and spec projects (builder-directed). Developer services include feasibility, entitlement, and construction oversight.' },
    ],
  },
  'tiny-home': {
    slug: 'tiny-home',
    name: 'Tiny Home',
    tagline: 'Concept, zoning check, and permit path for tiny homes, container homes, and micro-dwellings.',
    price: 'Starting at $395',
    priceNote: 'one-time · concept report',
    label: 'AI design engine',
    badge: 'AI design ready',
    badgeColor: '#E8793A',
    imageUrl: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=900&q=70&auto=format&fit=crop',
    description: 'Tiny homes, container homes, and micro-dwellings occupy a unique regulatory space in the DMV. We identify whether your proposed structure is treated as permanent construction, an ADU, or a temporary structure — and what permits and utility connections are required.',
    includes: [
      'Tiny home classification assessment (permanent vs. temporary)',
      'Lot eligibility and zoning check',
      'Utility connection requirements analysis',
      'HCD (manufactured home) vs. site-built classification',
      'Permit path identification for your jurisdiction',
      'Cost band estimate for foundation and utility work',
      'Contractor matching (tiny home and ADU specialists)',
      'Staff review before delivery',
    ],
    steps: [
      { n: '01', title: 'Describe your tiny home', body: 'Tell us the type (site-built, prefab, container, manufactured), intended use (primary, ADU, vacation), and your lot location.' },
      { n: '02', title: 'Classification and eligibility', body: 'We determine regulatory classification and lot eligibility for your specific tiny home type and jurisdiction.' },
      { n: '03', title: 'Permit path', body: 'We identify the exact permit path, fees, and timeline for your jurisdiction.' },
      { n: '04', title: 'Concept and contractor matching', body: 'AI-generated concept layout and matching with tiny home and ADU-experienced contractors.' },
    ],
    forWho: 'Homeowners and landowners planning a tiny home, container home, or micro-dwelling on a lot in the DC/Maryland/Virginia metro area.',
    cta: 'Start your tiny home concept',
    ctaHref: '/concept?q=Tiny+home',
    faq: [
      { q: 'Are tiny homes legal in the DMV?', a: 'It depends on classification and jurisdiction. Site-built micro-dwellings that meet minimum size codes are permitted in all DMV jurisdictions. Pre-built THOW (tiny homes on wheels) have more restrictions.' },
      { q: 'What is the minimum size for a legal home in the DMV?', a: 'Minimum habitable square footage varies by jurisdiction — typically 120–400 sq ft for a studio. Your concept report will confirm your jurisdiction\'s minimums.' },
      { q: 'Can a tiny home be an ADU on my existing property?', a: 'Yes, if it meets your jurisdiction\'s ADU size and setback requirements. This is one of the most common tiny home configurations in the DMV.' },
      { q: 'Do tiny homes hold their value?', a: 'Site-built tiny homes on permanent foundations typically appreciate. Manufactured homes on leased land do not. Your concept report addresses the resale implications.' },
    ],
  },
}

export function getProduct(slug: string): Product | null {
  return PRODUCTS[slug] ?? null
}

export function getAllProductSlugs(): string[] {
  return Object.keys(PRODUCTS)
}
