import { CONCEPT_PACKAGE_RULES } from '@kealee/core-rules'

export type ServiceCategory = 'design' | 'development' | 'permit' | 'estimate' | 'match'
export type AgentType = 'design' | 'land' | 'permit' | 'contractor'

/** Tier 2+; Basic is renders + PDF only. */
const VIDEO_PREMIUM_TIERS =
  'AI transformation video (Premium or Premium+): 60s narrated flythrough synced to your renders — Premium+ adds 30s, 15s, and 10s cuts for HOA, lenders, and social.'
/**
 * Included in every concept tier — full lists: @kealee/core-rules concept-package-deliverables.
 * @see docs/system/concept-package-deliverables.md
 */
const PERMIT_ROADMAP_IN_DESIGN_BUNDLE =
  'Permit + zoning in every package: scope brief, buildability snapshot, AHJ checklist, and fee/timeline ranges (depth increases by tier; not agency filing).'
const CREDIT_TOWARD_PERMIT_DRAWINGS = CONCEPT_PACKAGE_RULES.creditTowardDrawings
/**
 * Required on every permit-category deliverable. Kealee prepares, coordinates,
 * and assists with filing; only the jurisdiction approves a permit.
 */
const PERMIT_APPROVAL_DISCLAIMER =
  'Kealee prepares, coordinates, and assists with permit filing. Kealee does not issue permits and cannot guarantee approval — permit approval, fees, and timelines are set by the jurisdiction.'
const ESTIMATE_SCOPE_DISCLAIMER =
  'An estimate is a priced opinion based on the stated scope and assumptions. It is not a bid, a contract price, or a guarantee of construction cost.'
const SITE_PLAN_PRELIMINARY_DISCLAIMER =
  'Preliminary and not for construction unless professionally reviewed. Not a boundary survey. Source coverage and accuracy vary by jurisdiction.'

export interface ServiceDeliverable {
  label: string
  category: ServiceCategory
  agentType: AgentType
  generatesConcept: boolean
  /** Mirrors products.ts permitRequired. Used by concept generator + webhook. */
  permitRequired?: 'always' | 'sometimes' | 'rarely'
  /**
   * Number of AI renders to generate for this service.
   * Defaults to 3 if not set. Used by /api/concept/generate.
   */
  renderCount?: number
  includes: string[]
  deliveryDays: string
  nextStep: { label: string; href: string }
}

export const SERVICE_DELIVERABLES: Record<string, ServiceDeliverable> = {
  kitchen_remodel: {
    label: 'Kitchen Design Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'sometimes',
    renderCount: 5,
    includes: [
      'Floor plan / layout direction',
      '5 photorealistic AI renderings (multiple angles and lighting)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Bill of Materials (BOM) with line-item costs',
      'MEP specification (electrical, plumbing, HVAC, lighting)',
      'Detailed cost estimate',
      'Design brief with style direction',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  bathroom_remodel: {
    label: 'Bathroom Design Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'sometimes',
    renderCount: 5,
    includes: [
      'Floor plan / layout direction',
      '5 photorealistic AI renderings (multiple angles and lighting)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Bill of Materials (BOM) with line-item costs',
      'MEP specification (electrical, plumbing, HVAC, lighting)',
      'Detailed cost estimate',
      'Design brief with style direction',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '2-4 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  exterior_concept: {
    label: 'Exterior Concept Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'sometimes',
    renderCount: 5,
    includes: [
      'Floor plan / layout direction',
      '5 exterior renderings (front, side, rear, and detail views)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Material palette with finish selections',
      'Landscape overview sketch',
      'MEP specification (exterior systems)',
      'Bill of Materials (BOM)',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  interior_reno_concept: {
    label: 'Interior Reno Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    renderCount: 5,
    includes: [
      'Floor plan / layout direction',
      '5 photorealistic AI renderings',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Layout recommendations with flow analysis',
      'MEP specification (electrical, plumbing, lighting)',
      'Bill of Materials (BOM) with cost breakdown',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Get Detailed Cost Estimate', href: '/intake/cost_estimate' },
  },
  interior_renovation: {
    label: 'Interior Renovation',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    renderCount: 5,
    includes: [
      'Floor plan / layout direction',
      '5 photorealistic AI renderings',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Layout recommendations with flow analysis',
      'MEP specification (electrical, plumbing, lighting)',
      'Bill of Materials (BOM) with cost breakdown',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Get Detailed Cost Estimate', href: '/intake/cost_estimate' },
  },
  whole_home_concept: {
    label: 'Whole Home Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    renderCount: 7,
    includes: [
      'Floor plan / layout direction',
      '7 photorealistic AI renderings across living, dining, kitchen, and primary spaces',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'MEP specification for all systems',
      'Bill of Materials (BOM)',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '4-6 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  whole_home_remodel: {
    label: 'Whole-Home Remodel',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    renderCount: 7,
    includes: [
      'Floor plan / layout direction',
      '7 photorealistic AI renderings across living, dining, kitchen, and primary spaces',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'MEP specification for all systems',
      'Bill of Materials (BOM)',
      'Remodel phase plan',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '4-6 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  addition_expansion: {
    label: 'Addition / Expansion',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    renderCount: 5,
    includes: [
      'Floor plan / layout direction',
      '5 AI renderings (interior and exterior views of the addition)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Structural considerations brief',
      'MEP specification for new addition',
      'Bill of Materials (BOM)',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  garden_concept: {
    label: 'Garden Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'rarely',
    includes: [
      'Floor plan / layout direction',
      'Garden layout concept rendering',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Irrigation design with smart controller spec',
      'Plant list with seasonal selection',
      'Seasonal maintenance calendar',
      'Bill of Materials (BOM)',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '2-4 days',
    nextStep: { label: 'Find a Landscaping Contractor', href: '/intake/contractor_match' },
  },
  capture_site_concept: {
    label: 'Site Capture + Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'sometimes',
    includes: [
      'Floor plan / layout direction',
      'Site capture documentation',
      'Concept render based on site conditions',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Property analysis report',
      'Initial scope recommendations',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
    ],
    deliveryDays: '1-2 days',
    nextStep: { label: 'Get Full Design Package', href: '/intake/kitchen_remodel' },
  },
  design_build: {
    label: 'Design + Build Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Floor plan / layout direction',
      'Full concept design package',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Build-ready scope document',
      'MEP specification for all systems',
      'Bill of Materials (BOM)',
      VIDEO_PREMIUM_TIERS,
      'Contractor match recommendation',
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Match with a Contractor', href: '/intake/contractor_match' },
  },
  developer_concept: {
    label: 'Developer Concept',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      '3 development concept options',
      'Entitlement brief (zoning + use analysis)',
      'Pro forma direction (revenue + cost model)',
      'Capital stack overview',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  single_lot_development: {
    label: 'Single-Lot Development',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Single-lot development concept',
      'Zoning analysis & setback review',
      'Development cost estimate',
      'Permitting path summary',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '4-6 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  single_family_subdivision: {
    label: 'Single-Family Subdivision',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Subdivision concept layout',
      'Lot yield analysis',
      'Phase development plan',
      'Infrastructure cost estimate',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '6-8 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  townhome_subdivision: {
    label: 'Townhome Subdivision',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Townhome layout concept',
      'HOA structure considerations',
      'Pro forma direction',
      'Entitlement & zoning brief',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '7-10 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  development_feasibility: {
    label: 'Feasibility Study',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Full feasibility analysis report',
      'ROI projections (3 scenarios)',
      'Regulatory path & entitlement timeline',
      'Market comparables analysis',
      'Capital stack recommendations',
      '30-min strategy call',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Match with a Developer Partner', href: '/intake/contractor_match' },
  },
  mixed_use: {
    label: 'Mixed-Use Concept',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Mixed-use concept renderings',
      'Use matrix (residential + commercial split)',
      'Entitlement brief',
      'Pro forma direction',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '6-8 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  commercial_office: {
    label: 'Commercial Office Concept',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Commercial office concept renderings',
      'Code compliance brief (ADA, egress, occupancy)',
      'MEP specification overview',
      'Cost estimate framework',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  multi_unit_residential: {
    label: 'Multi-Unit Residential',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Multi-unit concept renderings',
      'Unit mix analysis (studio / 1BR / 2BR)',
      'Pro forma direction',
      'Entitlement & zoning brief',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  permit_path_only: {
    label: 'Permit Readiness Package',
    category: 'permit',
    agentType: 'permit',
    generatesConcept: false,
    includes: [
      'Jurisdiction identification from your property address (nationwide)',
      'Likely permit types and submission requirements for your scope',
      'Document checklist — what the agency will require from you',
      'Permit application preparation and package assembly',
      'Filing assistance and agency coordination where Kealee is authorized to act for you',
      'Corrections and resubmission tracking',
      PERMIT_APPROVAL_DISCLAIMER,
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Get a Cost Estimate', href: '/intake/cost_estimate' },
  },
  certified_estimate: {
    label: 'Certified Cost Estimate',
    category: 'estimate',
    agentType: 'design',
    generatesConcept: false,
    includes: [
      'Everything in the Detailed Cost Estimate',
      'Labor, material, equipment, subcontractor, general conditions, overhead, profit, and contingency lines',
      'Geographic pricing adjustment for the project location',
      'Written exclusions and allowances schedule',
      'Estimate confidence level and the assumptions each number rests on',
      'Professional review by a Kealee estimator before release',
      'Notarized lender-ready PDF plus the web deliverable',
      ESTIMATE_SCOPE_DISCLAIMER,
    ],
    deliveryDays: '5–7 days',
    nextStep: { label: 'Plan Your Permit Path', href: '/intake/permit_path_only' },
  },

  // ── Site Plan suite ───────────────────────────────────────────────────────
  // These three SKUs are sold on /site-plans and priced in INTAKE_PRICE_CENTS.
  // Without entries here a paid Site Plan order reached the Stripe webhook with
  // no deliverable definition and no automation route, so nothing was queued.
  preliminary_site_plan: {
    label: 'Preliminary Site Plan',
    category: 'development',
    agentType: 'land',
    generatesConcept: false,
    includes: [
      'Property and parcel intake with jurisdiction identification (nationwide)',
      'Available parcel and zoning source summary, each labelled with its source and date',
      'Preliminary setbacks, lot coverage, and overlay findings where published data exists',
      'Access, parking, grading/drainage, utility, stormwater, and flood or environmental flags where data is available',
      'Preliminary buildable-area diagram and one proposed footprint',
      'Coverage level, confidence, and the list of items still requiring confirmation',
      SITE_PLAN_PRELIMINARY_DISCLAIMER,
    ],
    deliveryDays: 'First-hour summary; full site plan in 2–5 days',
    nextStep: { label: 'Upgrade to Verified Feasibility', href: '/intake/verified_site_feasibility' },
  },
  verified_site_feasibility: {
    label: 'Verified Site Feasibility Plan',
    category: 'development',
    agentType: 'land',
    generatesConcept: false,
    includes: [
      'Everything in the Preliminary Site Plan',
      'Verified zoning and overlay source record with effective dates',
      'Constraint and buildable-envelope review against the verified inputs',
      'Proposed footprint validation',
      'Assumptions, exceptions, and confidence register',
      'Professional-review checklist and reviewer sign-off status',
      SITE_PLAN_PRELIMINARY_DISCLAIMER,
    ],
    deliveryDays: 'First-hour source summary; verified feasibility plan in 3–7 days',
    nextStep: { label: 'Plan Your Permit Path', href: '/intake/permit_path_only' },
  },
  permit_site_plan: {
    label: 'Survey-Based Permit Site Plan Coordination',
    category: 'development',
    agentType: 'land',
    generatesConcept: false,
    permitRequired: 'always',
    includes: [
      'Survey validation for permit filing',
      'Jurisdiction-specific site plan drafted from your survey',
      'Setbacks, lot coverage, structures, and required agency notes',
      'Coordination of the professional review and sealing your jurisdiction requires',
      'Revisions for agency comments and inclusion in the submission set',
      'Required source documents identified up front',
      PERMIT_APPROVAL_DISCLAIMER,
    ],
    deliveryDays: 'First-hour permit-requirements summary; drawing coordination scoped after survey review',
    nextStep: { label: 'Prepare Your Permit Package', href: '/intake/permit_path_only' },
  },
  cost_estimate: {
    label: 'Detailed Cost Estimate',
    category: 'estimate',
    agentType: 'design',
    generatesConcept: false,
    includes: [
      'Scope extraction from your description, plans, and uploads',
      'Quantity and cost assumptions stated line by line',
      'Labor, material, equipment, subcontractor, general conditions, overhead, profit, and contingency where applicable',
      'Geographic pricing adjustment for the project location',
      'Written exclusions and allowances',
      'Estimate confidence level and professional review status',
      'PDF and web deliverable',
      ESTIMATE_SCOPE_DISCLAIMER,
    ],
    deliveryDays: '2-3 days',
    nextStep: { label: 'Plan Your Permit Path', href: '/intake/permit_path_only' },
  },
  contractor_match: {
    label: 'Contractor Match',
    category: 'match',
    agentType: 'contractor',
    generatesConcept: false,
    includes: [
      '3 vetted contractor matches',
      'License & insurance verification',
      'Contractor contact information',
      'Match score sheet with project fit rating',
      'Intro coordination support',
    ],
    deliveryDays: '1 day',
    nextStep: { label: 'Browse the Marketplace', href: '/marketplace' },
  },
  professional_drawings: {
    label: 'Professional Design Drawings',
    category: 'permit',
    agentType: 'permit',
    generatesConcept: false,
    permitRequired: 'always',
    includes: [
      'Licensed architect / PE assigned to your project',
      'design concept review and integration into drawing set',
      'Permit-ready drawing set (floor plan, elevations, site plan)',
      'PE stamp where required by jurisdiction',
      'Jurisdiction cover sheet and code compliance notes',
      'Building department coordination',
      'Permit filing fee included — all-in pricing',
    ],
    deliveryDays: '7–14 days',
    nextStep: { label: 'File Your Permit', href: '/intake/permit_path_only' },
  },

  // All-in-one bundle — design concept + cost estimate + permit scope
  design_estimate_permit_bundle: {
    label: 'Design + Estimate + Permit Bundle',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Floor plan / layout direction',
      'design concept renderings (3–5 views)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Zoning and setback analysis tied to your concept massing',
      'Bill of Materials with line-item costs',
      'MEP specification (electrical, plumbing, HVAC, lighting)',
      'RSMeans-validated cost estimate (trade-by-trade)',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      '15-min expert consultation call (booked after delivery) — ideal to align estimate, video cuts, and permit filing sequence',
    ],
    deliveryDays: '3–5 days',
    nextStep: { label: 'Match with a Contractor', href: '/intake/contractor_match' },
  },
  estimate_permit_bundle: {
    label: 'Estimate + Permit Package',
    category: 'estimate',
    agentType: 'design',
    generatesConcept: false,
    permitRequired: 'always',
    includes: [
      'RSMeans-validated cost estimate aligned to your concept',
      'Permit package — application prep and agency filing',
      'Jurisdiction-specific checklist for your property address (nationwide)',
      'Single checkout — one project team',
    ],
    deliveryDays: '5–10 days',
    nextStep: { label: 'Match with a Contractor', href: '/intake/contractor_match' },
  },
}
