export type ServiceCategory = 'design' | 'development' | 'permit' | 'estimate' | 'match'
export type AgentType = 'design' | 'land' | 'permit' | 'contractor'

export interface ServiceDeliverable {
  label: string
  category: ServiceCategory
  agentType: AgentType
  generatesConcept: boolean
  includes: string[]
  deliveryDays: string
  nextStep: { label: string; href: string }
}

export const SERVICE_DELIVERABLES: Record<string, ServiceDeliverable> = {
  kitchen_remodel: {
    label: 'Kitchen Design Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    includes: [
      '3 concept visuals (before/after renders)',
      'Bill of Materials (BOM) with line-item costs',
      'MEP specification (electrical, plumbing, HVAC, lighting)',
      'Detailed cost estimate',
      'Design brief with style direction',
      'Zoning & permit scope brief',
      'Path-to-approval summary',
      '30-min consultation call',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  bathroom_remodel: {
    label: 'Bathroom Design Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    includes: [
      '3 concept visuals (before/after renders)',
      'Bill of Materials (BOM) with line-item costs',
      'MEP specification (electrical, plumbing, HVAC, lighting)',
      'Detailed cost estimate',
      'Design brief with style direction',
      'Zoning & permit scope brief',
      'Path-to-approval summary',
      '30-min consultation call',
    ],
    deliveryDays: '2-4 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  exterior_concept: {
    label: 'Exterior Concept Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    includes: [
      '3 exterior renderings (front, side, rear views)',
      'Material palette with finish selections',
      'Landscape overview sketch',
      'MEP specification (exterior systems)',
      'Bill of Materials (BOM)',
      '30-min consultation call',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  interior_reno_concept: {
    label: 'Interior Reno Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    includes: [
      'Interior concept visuals (3 renders)',
      'Layout recommendations with flow analysis',
      'MEP specification (electrical, plumbing, lighting)',
      'Bill of Materials (BOM) with cost breakdown',
      '30-min consultation call',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Get Detailed Cost Estimate', href: '/intake/cost_estimate' },
  },
  interior_renovation: {
    label: 'Interior Renovation',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    includes: [
      'Interior concept visuals (3 renders)',
      'Layout recommendations with flow analysis',
      'MEP specification (electrical, plumbing, lighting)',
      'Bill of Materials (BOM) with cost breakdown',
      '30-min consultation call',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Get Detailed Cost Estimate', href: '/intake/cost_estimate' },
  },
  whole_home_concept: {
    label: 'Whole Home Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    includes: [
      'Full-home concept renderings',
      'Floor plan direction with room-by-room scope',
      'MEP specification for all systems',
      'Bill of Materials (BOM)',
      '30-min consultation call',
    ],
    deliveryDays: '4-6 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  whole_home_remodel: {
    label: 'Whole-Home Remodel',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    includes: [
      'Full-home concept renderings',
      'Floor plan direction with remodel scope',
      'MEP specification for all systems',
      'Bill of Materials (BOM)',
      'Remodel phase plan',
      '30-min consultation call',
    ],
    deliveryDays: '4-6 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  addition_expansion: {
    label: 'Addition / Expansion',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    includes: [
      'Addition concept renderings (interior + exterior)',
      'Structural considerations brief',
      'Permit & zoning scope brief',
      'MEP specification for new addition',
      'Bill of Materials (BOM)',
      '30-min consultation call',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  garden_concept: {
    label: 'Garden Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    includes: [
      'Garden layout concept rendering',
      'Irrigation design with smart controller spec',
      'Plant list with seasonal selection',
      'Seasonal maintenance calendar',
      'Bill of Materials (BOM)',
      '30-min consultation call',
    ],
    deliveryDays: '2-4 days',
    nextStep: { label: 'Find a Landscaping Contractor', href: '/intake/contractor_match' },
  },
  capture_site_concept: {
    label: 'Site Capture + Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    includes: [
      'Site capture documentation',
      'Concept render based on site conditions',
      'Property analysis report',
      'Initial scope recommendations',
    ],
    deliveryDays: '1-2 days',
    nextStep: { label: 'Get Full Design Package', href: '/intake/kitchen_remodel' },
  },
  design_build: {
    label: 'Design + Build Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    includes: [
      'Full concept design package',
      'Build-ready scope document',
      'MEP specification for all systems',
      'Bill of Materials (BOM)',
      'Permit scope brief',
      'Contractor match recommendation',
      '30-min consultation call',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Match with a Contractor', href: '/intake/contractor_match' },
  },
  developer_concept: {
    label: 'Developer Concept',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    includes: [
      '3 development concept options',
      'Entitlement brief (zoning + use analysis)',
      'Pro forma direction (revenue + cost model)',
      'Capital stack overview',
      '30-min consultation call',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  single_lot_development: {
    label: 'Single-Lot Development',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    includes: [
      'Single-lot development concept',
      'Zoning analysis & setback review',
      'Development cost estimate',
      'Permitting path summary',
      '30-min consultation call',
    ],
    deliveryDays: '4-6 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  single_family_subdivision: {
    label: 'Single-Family Subdivision',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    includes: [
      'Subdivision concept layout',
      'Lot yield analysis',
      'Phase development plan',
      'Infrastructure cost estimate',
      '30-min consultation call',
    ],
    deliveryDays: '6-8 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  townhome_subdivision: {
    label: 'Townhome Subdivision',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    includes: [
      'Townhome layout concept',
      'HOA structure considerations',
      'Pro forma direction',
      'Entitlement & zoning brief',
      '30-min consultation call',
    ],
    deliveryDays: '7-10 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  development_feasibility: {
    label: 'Feasibility Study',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    includes: [
      'Full feasibility analysis report',
      'ROI projections (3 scenarios)',
      'Regulatory path & entitlement timeline',
      'Market comparables analysis',
      'Capital stack recommendations',
      '60-min strategy call',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Match with a Developer Partner', href: '/intake/contractor_match' },
  },
  mixed_use: {
    label: 'Mixed-Use Concept',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    includes: [
      'Mixed-use concept renderings',
      'Use matrix (residential + commercial split)',
      'Entitlement brief',
      'Pro forma direction',
      '30-min consultation call',
    ],
    deliveryDays: '6-8 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  commercial_office: {
    label: 'Commercial Office Concept',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    includes: [
      'Commercial office concept renderings',
      'Code compliance brief (ADA, egress, occupancy)',
      'MEP specification overview',
      'Cost estimate framework',
      '30-min consultation call',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  multi_unit_residential: {
    label: 'Multi-Unit Residential',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    includes: [
      'Multi-unit concept renderings',
      'Unit mix analysis (studio / 1BR / 2BR)',
      'Pro forma direction',
      'Entitlement & zoning brief',
      '30-min consultation call',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  permit_path_only: {
    label: 'Permit Package',
    category: 'permit',
    agentType: 'permit',
    generatesConcept: false,
    includes: [
      'Permit application preparation',
      'Jurisdiction-specific checklist',
      'Submission to applicable agency (DC DOB, Montgomery DPS, Fairfax LDS, etc.)',
      'Status tracking through approval',
      'Comment response coordination',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Find a Contractor', href: '/intake/contractor_match' },
  },
  cost_estimate: {
    label: 'Cost Estimate Package',
    category: 'estimate',
    agentType: 'design',
    generatesConcept: false,
    includes: [
      'RSMeans-validated cost estimate',
      'Trade-by-trade breakdown (GC, electrical, plumbing, HVAC, finishes)',
      'Lender-ready PDF report',
      'Contingency analysis',
      'Value engineering notes',
    ],
    deliveryDays: '2-3 days',
    nextStep: { label: 'Find a Contractor', href: '/intake/contractor_match' },
  },
  contractor_match: {
    label: 'Contractor Match',
    category: 'match',
    agentType: 'contractor',
    generatesConcept: false,
    includes: [
      '3 vetted contractor matches',
      'License & insurance verification',
      'Contractor contact information',
      'Match score sheet with project fit rating',
      'Intro coordination support',
    ],
    deliveryDays: '1 day',
    nextStep: { label: 'Browse the Marketplace', href: '/marketplace' },
  },
}
