export type ServiceCategory = 'design' | 'development' | 'permit' | 'estimate' | 'match'
export type AgentType = 'design' | 'land' | 'permit' | 'contractor'

/** Tier 2+; Basic is renders + PDF only. */
const VIDEO_PREMIUM_TIERS =
  'AI transformation video (Premium or Premium+): 60s narrated flythrough synced to your renders — Premium+ adds 30s, 15s, and 10s cuts for HOA, lenders, and social.'
/** Scope inside design concept; not agency filing. */
const PERMIT_ROADMAP_IN_DESIGN_BUNDLE =
  'Permit roadmap in your design bundle — disciplines flagged, AHJ checklist, submittal order, typical fees and review windows (pairs with permit-ready drawings or filing add-ons).'
const CREDIT_TOWARD_PERMIT_DRAWINGS =
  'Design concept fee credited toward permit-ready drawings when you continue with Kealee filing or architect handoff.'

export interface ServiceDeliverable {
  label: string
  category: ServiceCategory
  agentType: AgentType
  generatesConcept: boolean
  /** Mirrors products.ts permitRequired. Used by concept generator + webhook. */
  permitRequired?: 'always' | 'sometimes' | 'rarely'
  includes: string[]
  deliveryDays: string
  nextStep: { label: string; href: string }
}

export const SERVICE_DELIVERABLES: Record<string, ServiceDeliverable> = {
  kitchen_remodel: {
    label: 'Kitchen Design Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'sometimes',
    includes: [
      'Floor plan / layout direction',
      '3–5 concept renderings (before/after views)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Bill of Materials (BOM) with line-item costs',
      'MEP specification (electrical, plumbing, HVAC, lighting)',
      'Detailed cost estimate',
      'Design brief with style direction',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  bathroom_remodel: {
    label: 'Bathroom Design Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'sometimes',
    includes: [
      'Floor plan / layout direction',
      '3–5 concept renderings (before/after views)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Bill of Materials (BOM) with line-item costs',
      'MEP specification (electrical, plumbing, HVAC, lighting)',
      'Detailed cost estimate',
      'Design brief with style direction',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '2-4 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  exterior_concept: {
    label: 'Exterior Concept Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'sometimes',
    includes: [
      'Floor plan / layout direction',
      '3–5 exterior renderings (front, side, rear views)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Material palette with finish selections',
      'Landscape overview sketch',
      'MEP specification (exterior systems)',
      'Bill of Materials (BOM)',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  interior_reno_concept: {
    label: 'Interior Reno Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Floor plan / layout direction',
      'Interior concept visuals (3–5 renders)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Layout recommendations with flow analysis',
      'MEP specification (electrical, plumbing, lighting)',
      'Bill of Materials (BOM) with cost breakdown',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Get Detailed Cost Estimate', href: '/intake/cost_estimate' },
  },
  interior_renovation: {
    label: 'Interior Renovation',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Floor plan / layout direction',
      'Interior concept visuals (3–5 renders)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Layout recommendations with flow analysis',
      'MEP specification (electrical, plumbing, lighting)',
      'Bill of Materials (BOM) with cost breakdown',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Get Detailed Cost Estimate', href: '/intake/cost_estimate' },
  },
  whole_home_concept: {
    label: 'Whole Home Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Floor plan / layout direction',
      'Full-home concept renderings',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'MEP specification for all systems',
      'Bill of Materials (BOM)',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '4-6 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  whole_home_remodel: {
    label: 'Whole-Home Remodel',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Floor plan / layout direction',
      'Full-home concept renderings',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'MEP specification for all systems',
      'Bill of Materials (BOM)',
      'Remodel phase plan',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '4-6 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  addition_expansion: {
    label: 'Addition / Expansion',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Floor plan / layout direction',
      'Addition concept renderings (interior + exterior)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Structural considerations brief',
      'MEP specification for new addition',
      'Bill of Materials (BOM)',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  garden_concept: {
    label: 'Garden Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'rarely',
    includes: [
      'Floor plan / layout direction',
      'Garden layout concept rendering',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Irrigation design with smart controller spec',
      'Plant list with seasonal selection',
      'Seasonal maintenance calendar',
      'Bill of Materials (BOM)',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '2-4 days',
    nextStep: { label: 'Find a Landscaping Contractor', href: '/intake/contractor_match' },
  },
  capture_site_concept: {
    label: 'Site Capture + Concept',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'sometimes',
    includes: [
      'Floor plan / layout direction',
      'Site capture documentation',
      'Concept render based on site conditions',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Property analysis report',
      'Initial scope recommendations',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
    ],
    deliveryDays: '1-2 days',
    nextStep: { label: 'Get Full Design Package', href: '/intake/kitchen_remodel' },
  },
  design_build: {
    label: 'Design + Build Package',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Floor plan / layout direction',
      'Full concept design package',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Build-ready scope document',
      'MEP specification for all systems',
      'Bill of Materials (BOM)',
      VIDEO_PREMIUM_TIERS,
      'Contractor match recommendation',
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      'Direct support via portal ask bar',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Match with a Contractor', href: '/intake/contractor_match' },
  },
  developer_concept: {
    label: 'Developer Concept',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      '3 development concept options',
      'Entitlement brief (zoning + use analysis)',
      'Pro forma direction (revenue + cost model)',
      'Capital stack overview',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  single_lot_development: {
    label: 'Single-Lot Development',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Single-lot development concept',
      'Zoning analysis & setback review',
      'Development cost estimate',
      'Permitting path summary',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '4-6 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  single_family_subdivision: {
    label: 'Single-Family Subdivision',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Subdivision concept layout',
      'Lot yield analysis',
      'Phase development plan',
      'Infrastructure cost estimate',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '6-8 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  townhome_subdivision: {
    label: 'Townhome Subdivision',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Townhome layout concept',
      'HOA structure considerations',
      'Pro forma direction',
      'Entitlement & zoning brief',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '7-10 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  development_feasibility: {
    label: 'Feasibility Study',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Full feasibility analysis report',
      'ROI projections (3 scenarios)',
      'Regulatory path & entitlement timeline',
      'Market comparables analysis',
      'Capital stack recommendations',
      '30-min strategy call',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Match with a Developer Partner', href: '/intake/contractor_match' },
  },
  mixed_use: {
    label: 'Mixed-Use Concept',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Mixed-use concept renderings',
      'Use matrix (residential + commercial split)',
      'Entitlement brief',
      'Pro forma direction',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '6-8 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  commercial_office: {
    label: 'Commercial Office Concept',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Commercial office concept renderings',
      'Code compliance brief (ADA, egress, occupancy)',
      'MEP specification overview',
      'Cost estimate framework',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Continue to Permit Planning', href: '/intake/permit_path_only' },
  },
  multi_unit_residential: {
    label: 'Multi-Unit Residential',
    category: 'development',
    agentType: 'land',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Multi-unit concept renderings',
      'Unit mix analysis (studio / 1BR / 2BR)',
      'Pro forma direction',
      'Entitlement & zoning brief',
      'Direct support via portal ask bar',
    ],
    deliveryDays: '5-7 days',
    nextStep: { label: 'Get Feasibility Study', href: '/intake/development_feasibility' },
  },
  permit_path_only: {
    label: 'Permit Package',
    category: 'permit',
    agentType: 'permit',
    generatesConcept: false,
    includes: [
      'Permit application preparation',
      'Jurisdiction-specific checklist',
      'Submission to applicable agency (DC DOB, Montgomery DPS, Fairfax LDS, etc.)',
      'Status tracking through approval',
      'Comment response coordination',
    ],
    deliveryDays: '3-5 days',
    nextStep: { label: 'Find a Contractor', href: '/intake/contractor_match' },
  },
  cost_estimate: {
    label: 'Cost Estimate Package',
    category: 'estimate',
    agentType: 'design',
    generatesConcept: false,
    includes: [
      'RSMeans-validated cost estimate',
      'Trade-by-trade breakdown (GC, electrical, plumbing, HVAC, finishes)',
      'Lender-ready PDF report',
      'Contingency analysis',
      'Value engineering notes',
    ],
    deliveryDays: '2-3 days',
    nextStep: { label: 'Find a Contractor', href: '/intake/contractor_match' },
  },
  contractor_match: {
    label: 'Contractor Match',
    category: 'match',
    agentType: 'contractor',
    generatesConcept: false,
    includes: [
      '3 vetted contractor matches',
      'License & insurance verification',
      'Contractor contact information',
      'Match score sheet with project fit rating',
      'Intro coordination support',
    ],
    deliveryDays: '1 day',
    nextStep: { label: 'Browse the Marketplace', href: '/marketplace' },
  },
  professional_drawings: {
    label: 'Professional Design Drawings',
    category: 'permit',
    agentType: 'permit',
    generatesConcept: false,
    permitRequired: 'always',
    includes: [
      'Licensed architect / PE assigned to your project',
      'AI concept review and integration into drawing set',
      'Permit-ready drawing set (floor plan, elevations, site plan)',
      'PE stamp where required by jurisdiction',
      'Jurisdiction cover sheet and code compliance notes',
      'Building department coordination',
      'Permit filing fee included — all-in pricing',
    ],
    deliveryDays: '7–14 days',
    nextStep: { label: 'File Your Permit', href: '/intake/permit_path_only' },
  },

  // All-in-one bundle — design concept + cost estimate + permit scope
  design_estimate_permit_bundle: {
    label: 'Design + Estimate + Permit Bundle',
    category: 'design',
    agentType: 'design',
    generatesConcept: true,
    permitRequired: 'always',
    includes: [
      'Floor plan / layout direction',
      'AI concept renderings (3–5 views)',
      PERMIT_ROADMAP_IN_DESIGN_BUNDLE,
      'Zoning and setback analysis tied to your concept massing',
      'Bill of Materials with line-item costs',
      'MEP specification (electrical, plumbing, HVAC, lighting)',
      'RSMeans-validated cost estimate (trade-by-trade)',
      VIDEO_PREMIUM_TIERS,
      CREDIT_TOWARD_PERMIT_DRAWINGS,
      '15-min expert consultation call (booked after delivery) — ideal to align estimate, video cuts, and permit filing sequence',
    ],
    deliveryDays: '3–5 days',
    nextStep: { label: 'Match with a Contractor', href: '/intake/contractor_match' },
  },
}
