[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.portal-developer"
watchPatterns = ["apps/portal-developer/**", "packages/**"]

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
