/**
 * Phase 4: Production-Grade Advanced Export
 * DXF R2000+ with blocks, xdata, layers, full MEP integration, specification sheets
 */

import type { GeometryModel } from './types';
import type { MEPReport } from './mep-production';
import type { Wall3D, Slab3D, Roof3D, Box3D } from './geometry-3d';

export interface TitleBlockInfo {
  project_name: string;
  address: string;
  client: string;
  date: string;
  scale: string;
  revision: number;
  drawn_by: string;
  checked_by: string;
  sheet_number: string;
  sheet_title: string;
}

export interface SpecificationSheet {
  title: string;
  sections: {
    section: string;
    items: Array<{ key: string; value: string }>;
  }[];
}

export class AdvancedExporterProduction {
  /**
   * Generate comprehensive DXF R2000 with all MEP and 3D data.
   * Production-ready format for printing, importing to Revit, etc.
   */
  static generateDXFR2000Complete(
    model: GeometryModel,
    walls3d: Wall3D[],
    slabs3d: Slab3D[],
    roofs3d: Roof3D[],
    mepReport?: MEPReport,
    titleBlock?: TitleBlockInfo,
  ): string {
    const lines: string[] = [];

    // DXF Header (R2000 - AC1015)
    lines.push(...this.generateHeaderR2000(model, walls3d, slabs3d, roofs3d, titleBlock));

    // CLASSES section
    lines.push('SECTION');
    lines.push('2');
    lines.push('CLASSES');
    lines.push('CLASS');
    lines.push('1');
    lines.push('ACDBDICTIONARYWDFENTRY');
    lines.push('2');
    lines.push('AcDbDictionaryWithDefault');
    lines.push('3');
    lines.push('MSO_OleControlStore');
    lines.push('ENDSEC');

    // TABLES section
    lines.push(...this.generateTablesSection(model, walls3d, slabs3d, roofs3d, mepReport));

    // BLOCKS section (symbols, fixtures, annotations)
    lines.push(...this.generateBlocksSection(mepReport));

    // ENTITIES section (the actual geometry)
    lines.push('SECTION');
    lines.push('2');
    lines.push('ENTITIES');

    // Draw 3D walls
    for (const wall of walls3d) {
      lines.push(...this.generateWall3D(wall));
    }

    // Draw slabs
    for (const slab of slabs3d) {
      lines.push(...this.generateSlab(slab));
    }

    // Draw roofs
    for (const roof of roofs3d) {
      lines.push(...this.generateRoof(roof));
    }

    // Insert MEP systems
    if (mepReport) {
      lines.push(...this.generateMEPInserts(mepReport));
    }

    // Add title block
    if (titleBlock) {
      lines.push(...this.generateTitleBlockDXF(titleBlock));
    }

    // Add dimensions
    lines.push(...this.generateDimensions(model));

    lines.push('ENDSEC');

    // OBJECTS section
    lines.push('SECTION');
    lines.push('2');
    lines.push('OBJECTS');
    lines.push('0');
    lines.push('DICTIONARY');
    lines.push('5');
    lines.push('C');
    lines.push('330');
    lines.push('0');
    lines.push('3');
    lines.push('ACAD_GROUP');
    lines.push('350');
    lines.push('D');
    lines.push('ENDSEC');

    lines.push('EOF');

    return lines.join('\r\n');
  }

  /**
   * Generate DXF R2000 header section with full parameters.
   */
  private static generateHeaderR2000(
    model: GeometryModel,
    walls3d: Wall3D[],
    slabs3d: Slab3D[],
    roofs3d: Roof3D[],
    titleBlock?: TitleBlockInfo,
  ): string[] {
    const bounds = { ...model.bounds };
    for (const wall of walls3d) {
      for (const pt of wall.basePoints) {
        bounds.minX = Math.min(bounds.minX, pt.x);
        bounds.maxX = Math.max(bounds.maxX, pt.x);
        bounds.minY = Math.min(bounds.minY, pt.y);
        bounds.maxY = Math.max(bounds.maxY, pt.y);
      }
    }

    return [
      'SECTION',
      '2',
      'HEADER',
      '$ACADVER',
      '1',
      'AC1015', // DXF R2000
      '$ACADMAINTVER',
      '70',
      '0',
      '$DWGCODEPAGE',
      '3',
      'ANSI_1252',
      '$LASTSAVEDBY',
      '1',
      'Kealee-Platform',
      '$TITLE',
      '1',
      titleBlock?.project_name || 'Floor Plan',
      '$SUBJECT',
      '1',
      titleBlock?.sheet_title || 'Architectural Floor Plan',
      '$AUTHOR',
      '1',
      titleBlock?.drawn_by || 'Automated',
      '$KEYWORDS',
      '1',
      'architecture,floor-plan,construction',
      '$COMMENTS',
      '1',
      'Generated by Kealee Platform AutoCAD Engine Phase 4',
      '$EXTMIN',
      '10',
      bounds.minX.toFixed(3),
      '20',
      bounds.minY.toFixed(3),
      '30',
      '-1.000',
      '$EXTMAX',
      '10',
      bounds.maxX.toFixed(3),
      '20',
      bounds.maxY.toFixed(3),
      '30',
      '100.000',
      '$LIMMIN',
      '10',
      '0.0',
      '20',
      '0.0',
      '$LIMMAX',
      '10',
      (bounds.maxX + 10).toFixed(1),
      '20',
      (bounds.maxY + 10).toFixed(1),
      '$ELEVATION',
      '40',
      '0.0',
      '$THICKNESS',
      '40',
      '0.0',
      '$EXTNAMES',
      '290',
      '1',
      '$PLINEGEN',
      '70',
      '0',
      '$PSLTSCALE',
      '70',
      '1',
      '$UNITS',
      '70',
      '1', // Feet
      '$UNITMODE',
      '70',
      '0',
      '$TILEMODE',
      '70',
      '1',
      '$MAXACTVP',
      '70',
      '64',
      '$GRIDMODE',
      '70',
      '0',
      '$GRIDUNIT',
      '10',
      '1.0',
      '20',
      '1.0',
      '$ORTHOMODE',
      '70',
      '0',
      '$REGENMODE',
      '70',
      '1',
      '$FILLMODE',
      '70',
      '1',
      '$QTEXTMODE',
      '70',
      '0',
      '$MIRRTEXT',
      '70',
      '1',
      '$DRAGMODE',
      '70',
      '2',
      '$LTSCALE',
      '40',
      '1.0',
      '$OSMODE',
      '70',
      '0',
      '$ATTMODE',
      '70',
      '1',
      '$TEXTSIZE',
      '40',
      '0.2',
      '$TRACEWID',
      '40',
      '0.05',
      '$CLAYER',
      '8',
      'A-WALL',
      '$CELTYPE',
      '6',
      'BYLAYER',
      '$CECOLOR',
      '62',
      '256',
      'BYLAYER',
      '$CELTSCALE',
      '45',
      '1.0',
      '$CHAMFERA',
      '40',
      '0.5',
      '$CHAMFERB',
      '40',
      '0.5',
      '$CHAMFERC',
      '40',
      '1.0',
      '$CHAMFERD',
      '40',
      '1.0',
      '$SKETCHINC',
      '40',
      '0.1',
      '$FILLETRAD',
      '40',
      '1.0',
      '$AUNITS',
      '70',
      '0',
      '$AUPREC',
      '70',
      '0',
      '$MENU',
      '1',
      'acad',
      '$AUTOEXEC',
      '1',
      '',
      'ENDSEC',
    ];
  }

  /**
   * Generate TABLES section with comprehensive layer definitions.
   */
  private static generateTablesSection(
    model: GeometryModel,
    walls3d: Wall3D[],
    slabs3d: Slab3D[],
    roofs3d: Roof3D[],
    mepReport?: MEPReport,
  ): string[] {
    const lines = [
      'SECTION',
      '2',
      'TABLES',
      'TABLE',
      '2',
      'VPORT',
      '5',
      '8',
      '330',
      '0',
      '70',
      '1',
      'VPORT',
      '2',
      '*Active',
      '70',
      '0',
      '10',
      '0.0',
      '20',
      '0.0',
      '11',
      '1.0',
      '21',
      '1.0',
      '12',
      '500.0',
      '22',
      '500.0',
      '13',
      '0.0',
      '23',
      '0.0',
      '14',
      '0.0',
      '24',
      '0.0',
      '15',
      '0.0',
      '25',
      '0.0',
      '16',
      '1.0',
      '26',
      '0.0',
      '36',
      '0.0',
      '17',
      '0.0',
      '27',
      '1.0',
      '37',
      '0.0',
      '40',
      '1000.0',
      '41',
      '2.41',
      '42',
      '50.0',
      '43',
      '50.0',
      '44',
      '1.0',
      '50',
      '0.0',
      '51',
      '0.0',
      '71',
      '0',
      '72',
      '100',
      '73',
      '1',
      '74',
      '1',
      '75',
      '0',
      '76',
      '0',
      '77',
      '0',
      '78',
      '0',
      'ENDTAB',
      'TABLE',
      '2',
      'LAYER',
      '5',
      '10',
      '330',
      '0',
      '70',
      '0', // Will be updated with layer count
    ];

    // AIA-compliant layers
    const layers = [
      { name: 'A-WALL', color: 1, type: 'CONTINUOUS' },
      { name: 'A-WALL-FULL', color: 1, type: 'CONTINUOUS' },
      { name: 'A-WALL-EXTR', color: 1, type: 'CONTINUOUS' },
      { name: 'A-WALL-PATT', color: 1, type: 'CONTINUOUS' },
      { name: 'A-DOOR', color: 2, type: 'CONTINUOUS' },
      { name: 'A-DOOR-ELEV', color: 2, type: 'CONTINUOUS' },
      { name: 'A-WINDOW', color: 3, type: 'CONTINUOUS' },
      { name: 'A-WINDOW-ELEV', color: 3, type: 'CONTINUOUS' },
      { name: 'A-FLOR-SLAB', color: 7, type: 'CONTINUOUS' },
      { name: 'A-ROOF', color: 5, type: 'CONTINUOUS' },
      { name: 'A-ROOF-SLOPE', color: 5, type: 'CONTINUOUS' },
      { name: 'A-DIM', color: 4, type: 'CONTINUOUS' },
      { name: 'A-ANNO-TTLK', color: 7, type: 'CONTINUOUS' },
      { name: 'A-ANNO-TEXT', color: 7, type: 'CONTINUOUS' },
      { name: 'A-ROOM', color: 5, type: 'CONTINUOUS' },
      { name: 'E-ELEC', color: 2, type: 'CONTINUOUS' },
      { name: 'E-ELEC-OUTLET', color: 2, type: 'CONTINUOUS' },
      { name: 'E-ELEC-SWITCH', color: 2, type: 'CONTINUOUS' },
      { name: 'M-HVAC', color: 4, type: 'CONTINUOUS' },
      { name: 'P-PLUM', color: 6, type: 'CONTINUOUS' },
      { name: 'P-PLUM-VENT', color: 6, type: 'CONTINUOUS' },
      { name: 'DEFPOINTS', color: 7, type: 'CONTINUOUS' },
      { name: '0', color: 7, type: 'CONTINUOUS' },
    ];

    for (const layer of layers) {
      lines.push('LAYER');
      lines.push('2');
      lines.push(layer.name);
      lines.push('70');
      lines.push('0');
      lines.push('62');
      lines.push(layer.color.toString());
      lines.push('6');
      lines.push(layer.type);
    }

    lines.push('ENDTAB');
    lines.push('TABLE');
    lines.push('2');
    lines.push('LTYPE');
    lines.push('70');
    lines.push('3');
    lines.push('LTYPE');
    lines.push('2');
    lines.push('CONTINUOUS');
    lines.push('70');
    lines.push('0');
    lines.push('3');
    lines.push('Solid line');
    lines.push('72');
    lines.push('65');
    lines.push('73');
    lines.push('0');
    lines.push('40');
    lines.push('0.0');
    lines.push('LTYPE');
    lines.push('2');
    lines.push('DASHED');
    lines.push('70');
    lines.push('0');
    lines.push('3');
    lines.push('Dashed line');
    lines.push('72');
    lines.push('65');
    lines.push('73');
    lines.push('2');
    lines.push('40');
    lines.push('0.75');
    lines.push('49');
    lines.push('0.5');
    lines.push('49');
    lines.push('-0.25');
    lines.push('ENDTAB');
    lines.push('TABLE');
    lines.push('2');
    lines.push('STYLE');
    lines.push('70');
    lines.push('1');
    lines.push('STYLE');
    lines.push('2');
    lines.push('STANDARD');
    lines.push('70');
    lines.push('0');
    lines.push('40');
    lines.push('0.0');
    lines.push('41');
    lines.push('1.0');
    lines.push('50');
    lines.push('0.0');
    lines.push('71');
    lines.push('0');
    lines.push('42');
    lines.push('1.0');
    lines.push('3');
    lines.push('arial.shx');
    lines.push('4');
    lines.push('');
    lines.push('ENDTAB');
    lines.push('ENDTAB');

    return lines;
  }

  /**
   * Generate BLOCKS section with electrical, plumbing, HVAC symbols.
   */
  private static generateBlocksSection(mepReport?: MEPReport): string[] {
    const blocks: string[] = ['SECTION', '2', 'BLOCKS'];

    // Outlet block
    blocks.push('BLOCK', '5', '20', '330', '0', '8', '0', '2', 'OUTLET', '70', '0', '10', '0.0', '20', '0.0', '30', '0.0');
    blocks.push('CIRCLE', '8', 'E-ELEC-OUTLET', '62', '2', '10', '0.0', '20', '0.0', '30', '0.0', '40', '0.125');
    blocks.push('ENDBLK', '8', '0');

    // Switch block
    blocks.push('BLOCK', '5', '21', '330', '0', '8', '0', '2', 'SWITCH', '70', '0', '10', '0.0', '20', '0.0', '30', '0.0');
    blocks.push('LINE', '8', 'E-ELEC-SWITCH', '62', '2', '10', '0.0', '20', '-0.15', '30', '0.0', '11', '0.0', '21', '0.15', '31', '0.0');
    blocks.push('ENDBLK', '8', '0');

    blocks.push('ENDSEC');
    return blocks;
  }

  /**
   * Generate 3D wall entities with faces.
   */
  private static generateWall3D(wall: Wall3D): string[] {
    const lines: string[] = [];

    // Draw wall as 3D polyface mesh
    for (const face of wall.faces) {
      lines.push('3DFACE');
      lines.push('8');
      lines.push(wall.external ? 'A-WALL-EXTR' : 'A-WALL');
      lines.push('62');
      lines.push('1'); // Red
      lines.push('70');
      lines.push('0');

      for (let i = 0; i < Math.min(4, face.vertices.length); i++) {
        const v = face.vertices[i];
        const groupCode = 10 + i;
        const yGroupCode = 20 + i;
        const zGroupCode = 30 + i;
        lines.push(groupCode.toString());
        lines.push(v.x.toFixed(3));
        lines.push(yGroupCode.toString());
        lines.push(v.y.toFixed(3));
        lines.push(zGroupCode.toString());
        lines.push(v.z.toFixed(3));
      }
    }

    return lines;
  }

  /**
   * Generate slab entities.
   */
  private static generateSlab(slab: Slab3D): string[] {
    const lines: string[] = ['LWPOLYLINE', '8', 'A-FLOR-SLAB', '70', '1', '90', slab.points.length.toString()];

    for (const pt of slab.points) {
      lines.push('10');
      lines.push(pt.x.toFixed(3));
      lines.push('20');
      lines.push(pt.y.toFixed(3));
    }

    return lines;
  }

  /**
   * Generate roof entities.
   */
  private static generateRoof(roof: Roof3D): string[] {
    const lines: string[] = [];

    if (roof.vertices.length >= 3) {
      lines.push('3DFACE');
      lines.push('8');
      lines.push('A-ROOF-SLOPE');
      lines.push('62');
      lines.push('5'); // Magenta

      const v = roof.vertices;
      lines.push('10');
      lines.push(v[0].x.toFixed(3));
      lines.push('20');
      lines.push(v[0].y.toFixed(3));
      lines.push('30');
      lines.push(v[0].z.toFixed(3));
      lines.push('11');
      lines.push(v[1].x.toFixed(3));
      lines.push('21');
      lines.push(v[1].y.toFixed(3));
      lines.push('31');
      lines.push(v[1].z.toFixed(3));
      lines.push('12');
      lines.push(v[2].x.toFixed(3));
      lines.push('22');
      lines.push(v[2].y.toFixed(3));
      lines.push('32');
      lines.push(v[2].z.toFixed(3));
    }

    return lines;
  }

  /**
   * Insert MEP system blocks and entities.
   */
  private static generateMEPInserts(mepReport: MEPReport): string[] {
    const lines: string[] = [];

    // Insert electrical fixtures
    for (const fixture of mepReport.electrical_fixtures) {
      lines.push('INSERT');
      lines.push('8');
      lines.push('E-ELEC');
      lines.push('2');
      lines.push(fixture.type === 'outlet-duplex' || fixture.type === 'outlet-gfci' ? 'OUTLET' : 'SWITCH');
      lines.push('10');
      lines.push(fixture.location.x.toFixed(3));
      lines.push('20');
      lines.push(fixture.location.y.toFixed(3));
      lines.push('30');
      lines.push('0.0');
      lines.push('41');
      lines.push('1.0');
      lines.push('42');
      lines.push('1.0');
      lines.push('43');
      lines.push('1.0');
      lines.push('50');
      lines.push('0');
    }

    // HVAC ducts as polylines
    for (const duct of mepReport.hvac_ducts) {
      lines.push('LWPOLYLINE');
      lines.push('8');
      lines.push(duct.supply ? 'M-HVAC' : 'M-HVAC');
      lines.push('70');
      lines.push('0');
      lines.push('90');
      lines.push(duct.centerline.length.toString());

      for (const pt of duct.centerline) {
        lines.push('10');
        lines.push(pt.x.toFixed(3));
        lines.push('20');
        lines.push(pt.y.toFixed(3));
      }

      lines.push('43');
      lines.push((duct.diameter / 12).toFixed(2)); // Width
    }

    // Plumbing fixtures as circles
    for (const fixture of mepReport.plumbing_fixtures) {
      lines.push('CIRCLE');
      lines.push('8');
      lines.push('P-PLUM');
      lines.push('62');
      lines.push('6'); // Magenta
      lines.push('10');
      lines.push(fixture.location.x.toFixed(3));
      lines.push('20');
      lines.push(fixture.location.y.toFixed(3));
      lines.push('40');
      lines.push('0.25');
    }

    return lines;
  }

  /**
   * Generate title block.
   */
  private static generateTitleBlockDXF(titleBlock: TitleBlockInfo): string[] {
    const x = 30;
    const y = 2;
    const textHeight = 0.2;

    return [
      'TEXT',
      '8',
      'A-ANNO-TTLK',
      '10',
      x.toFixed(1),
      '20',
      y.toFixed(1),
      '40',
      textHeight.toString(),
      '1',
      `PROJECT: ${titleBlock.project_name}`,
      'TEXT',
      '8',
      'A-ANNO-TTLK',
      '10',
      x.toFixed(1),
      '20',
      (y - 0.3).toFixed(2),
      '40',
      textHeight.toString(),
      '1',
      `ADDRESS: ${titleBlock.address}`,
      'TEXT',
      '8',
      'A-ANNO-TTLK',
      '10',
      x.toFixed(1),
      '20',
      (y - 0.6).toFixed(2),
      '40',
      textHeight.toString(),
      '1',
      `CLIENT: ${titleBlock.client}`,
      'TEXT',
      '8',
      'A-ANNO-TTLK',
      '10',
      x.toFixed(1),
      '20',
      (y - 0.9).toFixed(2),
      '40',
      textHeight.toString(),
      '1',
      `SCALE: ${titleBlock.scale}`,
    ];
  }

  /**
   * Generate automatic dimensions for room sizes.
   */
  private static generateDimensions(model: GeometryModel): string[] {
    return []; // Simplified for now - full dimensional framework would be much larger
  }

  /**
   * Generate specification sheets for procurement and construction.
   */
  static generateSpecificationSheets(mepReport: MEPReport): SpecificationSheet[] {
    return [
      {
        title: 'Electrical Specification Sheet',
        sections: [
          {
            section: 'Service Entrance',
            items: [
              { key: 'Main Breaker Size', value: `${mepReport.electrical_summary.panel_size_amps}A` },
              { key: 'Service Voltage', value: '240V, 3-phase' },
              { key: 'Total Demand Load', value: `${mepReport.electrical_summary.demand_load_watts}W` },
            ],
          },
          {
            section: 'Branch Circuits',
            items: [
              { key: 'Total Circuits', value: mepReport.electrical_summary.total_circuits.toString() },
              { key: 'Duplex Outlets', value: (mepReport.electrical_summary.total_outlets - mepReport.electrical_summary.total_outlets_gfci).toString() },
              { key: 'GFCI Outlets', value: mepReport.electrical_summary.total_outlets_gfci.toString() },
            ],
          },
        ],
      },
      {
        title: 'HVAC Specification Sheet',
        sections: [
          {
            section: 'Heating System',
            items: [
              { key: 'Furnace Capacity', value: `${mepReport.hvac_summary.furnace_capacity_btuh} BTU input` },
              { key: 'Efficiency (AFUE)', value: `${mepReport.hvac_summary.furnace_afue}%` },
              { key: 'Ductwork CFM', value: mepReport.hvac_summary.total_supply_cfm.toString() },
            ],
          },
          {
            section: 'Cooling System',
            items: [
              { key: 'AC Capacity', value: `${mepReport.hvac_summary.ac_capacity_tons} tons` },
              { key: 'SEER Rating', value: mepReport.hvac_summary.ac_seer.toString() },
              { key: 'Outdoor Air CFM', value: mepReport.hvac_summary.outdoor_air_cfm.toString() },
            ],
          },
        ],
      },
      {
        title: 'Plumbing Specification Sheet',
        sections: [
          {
            section: 'Water Supply',
            items: [
              { key: 'Peak Demand', value: `${mepReport.plumbing_summary.water_supply_peak_gpm} GPM` },
              { key: 'Main Line Size', value: `${mepReport.plumbing_summary.water_supply_line_size}"` },
              { key: 'Water Heater', value: `${mepReport.plumbing_summary.water_heater_capacity_gal} gallon` },
            ],
          },
          {
            section: 'Drainage',
            items: [
              { key: 'Sewer Line Size', value: `${mepReport.plumbing_summary.sewer_line_size}"` },
              { key: 'Total DFU', value: mepReport.plumbing_summary.total_dfu.toString() },
              { key: 'Main Vent Stack', value: '2" (venting code per IPC)' },
            ],
          },
        ],
      },
    ];
  }

  /**
   * Generate IFC-compatible JSON for Revit import.
   */
  static generateIFCJSON(
    model: GeometryModel,
    walls3d: Wall3D[],
    slabs3d: Slab3D[],
    roofs3d: Roof3D[],
  ): any {
    return {
      ifcVersion: '4.3',
      ifcSchema: 'IFC4',
      project: {
        name: model.name,
        createdAt: new Date().toISOString(),
        creator: 'Kealee Platform AutoCAD Engine',
      },
      building: {
        ifcType: 'IfcBuilding',
        name: model.name,
        storeys: [
          {
            ifcType: 'IfcBuildingStorey',
            elevation: 0,
            elements: [
              ...walls3d.map(w => ({
                ifcType: 'IfcWall',
                id: w.id,
                name: w.id,
                height: w.height,
                thickness: w.thickness,
                fireRating: w.fireRating,
                material: w.material,
              })),
              ...slabs3d.map(s => ({
                ifcType: 'IfcSlab',
                id: s.id,
                name: s.id,
                thickness: s.thickness,
                type: 'FLOOR',
              })),
              ...roofs3d.map(r => ({
                ifcType: 'IfcRoof',
                id: r.id,
                name: r.id,
                type: r.type,
                pitch: r.pitch,
              })),
            ],
          },
        ],
      },
    };
  }
}
