import Link from 'next/link'
import { ExternalLink, PenTool } from 'lucide-react'
import { getSupabaseAdmin } from '@/lib/supabase-server'
import { reviewDesignConcept } from '@/lib/concept-review-actions'
import { SERVICE_BY_INTAKE } from '@/lib/services-config'

/**
 * OS Architecture — design concepts awaiting an architect.
 *
 * A concept order is in this queue once the concept generator has written its
 * output and until an architect has APPROVED the current generation. A
 * concept the architect sent back and the designer has since regenerated
 * (`conceptGeneration` bumped) comes back to the queue on its own.
 */
export async function DesignConceptQueue() {
  const supabase = getSupabaseAdmin()
  const { data: rows } = await supabase
    .from('public_intake_leads')
    .select('id, project_path, client_name, project_address, status, created_at, updated_at, form_data')
    .like('project_path', '%concept%')
    .in('status', ['concept_ready', 'delivered', 'in_review', 'needs_professional_review', 'revision_requested', 'ready_for_delivery'])
    .order('updated_at', { ascending: false })
    .limit(60)

  const items = (rows ?? []).flatMap((row) => {
    const fd = (row.form_data ?? {}) as Record<string, unknown>
    if (!fd.conceptOutput && !fd.v30ConceptOutput) return []
    const review = fd.architectReview as { state?: string; conceptGeneration?: number; decidedAt?: string; reviewer?: { displayName?: string } } | undefined
    const generation = Number(fd.conceptGeneration ?? 0)
    const decidedOnThis = review && Number(review.conceptGeneration ?? 0) === generation
    const state = decidedOnThis ? review!.state : 'AWAITING_ARCHITECT'
    return [{
      id: row.id as string,
      service: SERVICE_BY_INTAKE[String(row.project_path)]?.label ?? String(row.project_path),
      client: (row.client_name as string | null) ?? '—',
      address: (row.project_address as string | null) ?? '—',
      status: String(row.status ?? ''),
      generation,
      automated: fd.v30 === true,
      state,
      lastReview: review ? `${review.state} by ${review.reviewer?.displayName ?? 'architect'} on generation ${review.conceptGeneration ?? 0}` : null,
      updatedAt: String(row.updated_at ?? row.created_at ?? ''),
    }]
  })
  const open = items.filter(i => i.state !== 'APPROVED')
  const done = items.filter(i => i.state === 'APPROVED')

  return (
    <section>
      <h2 className="mb-1 text-xl font-semibold">Design concepts awaiting architectural review</h2>
      <p className="mb-4 text-sm text-slate-600">Concept packages generated by the design engine. Approve the concept as a licensed architect, or send direction back to the designer; a regenerated concept returns here for the next decision.</p>
      <div className="space-y-3">
        {open.map(item => (
          <form key={item.id} action={reviewDesignConcept} className="rounded-xl border border-slate-200 bg-white p-5">
            <input type="hidden" name="intakeId" value={item.id} />
            <div className="flex flex-col justify-between gap-3 sm:flex-row">
              <div>
                <p className="font-semibold">{item.service} · {item.address}</p>
                <p className="mt-1 text-sm text-slate-500">{item.client} · order {item.id.slice(0, 8)} · {item.status.replaceAll('_', ' ')} · concept generation {item.generation}{item.automated ? ' · AI-automated' : ''}</p>
                {item.lastReview && <p className="mt-1 text-xs text-amber-800">Previous decision: {item.lastReview}</p>}
              </div>
              <div className="flex items-start gap-2">
                <Link href={`/workspace/${item.id}`} target="_blank" className="inline-flex items-center gap-1 rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium hover:border-slate-950"><ExternalLink className="h-4 w-4" /> Open concept</Link>
              </div>
            </div>
            <label className="mt-4 block text-sm font-medium text-slate-700">
              Review basis or direction for the designer
              <textarea name="comment" placeholder="What is acceptable, what must change (massing, plan, code, buildability), and why" className="mt-2 min-h-20 w-full rounded-lg border border-slate-300 p-3 text-sm outline-none focus:border-emerald-600" />
            </label>
            <div className="mt-3 flex flex-wrap gap-2">
              <button name="decision" value="APPROVED" className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-800">Approve concept</button>
              <button name="decision" value="CHANGES_REQUESTED" className="rounded-lg bg-amber-600 px-4 py-2 text-sm font-semibold text-white hover:bg-amber-700">Send back with direction</button>
            </div>
          </form>
        ))}
        {!open.length && (
          <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-500"><PenTool className="mx-auto mb-2 h-6 w-6" />No design concepts are waiting for an architect.</div>
        )}
        {done.length > 0 && <p className="text-xs text-slate-500">{done.length} concept{done.length === 1 ? '' : 's'} approved on their current generation.</p>}
      </div>
    </section>
  )
}
