/**
 * Creates 9 Stripe products (garden basic/advanced/full, interior basic/advanced/full,
 * whole-home basic/advanced/full) and outputs env vars ready to paste into Railway.
 *
 * Run: npx tsx scripts/create-concept-stripe-products.ts
 */
import Stripe from "stripe";

const STRIPE_KEY = process.env.STRIPE_SECRET_KEY ?? "";
if (!STRIPE_KEY) throw new Error("Set STRIPE_SECRET_KEY before running");

const stripe = new Stripe(STRIPE_KEY, { apiVersion: "2024-06-20" });

const PRODUCTS = [
  // Garden & Farming
  {
    envKey: "STRIPE_PRICE_GARDEN_BASIC",
    name: "AI Garden Concept",
    description: "3 garden layouts, raised bed plan, irrigation overview, planting guide. 1 revision.",
    amount: 39500, // $395
    category: "garden",
  },
  {
    envKey: "STRIPE_PRICE_GARDEN_ADVANCED",
    name: "Advanced Garden Design",
    description: "Detailed plant lists, irrigation specs, 3D garden views, seasonal calendar. Up to 3 revisions.",
    amount: 75000, // $750
    category: "garden",
  },
  {
    envKey: "STRIPE_PRICE_GARDEN_FULL",
    name: "Full Landscape Design",
    description: "Permit-ready landscape package, hardscape + softscape plans, full irrigation. Up to 5 revisions.",
    amount: 250000, // $2,500
    category: "garden",
  },
  // Interior Renovation
  {
    envKey: "STRIPE_PRICE_INTERIOR_BASIC",
    name: "AI Interior Concept",
    description: "3 layout options, finish direction board, rough cost range. 1 revision.",
    amount: 39500, // $395
    category: "interior",
  },
  {
    envKey: "STRIPE_PRICE_INTERIOR_ADVANCED",
    name: "Advanced Interior Design",
    description: "Detailed floor plans, material + fixture specs, 3D views. Up to 3 revisions.",
    amount: 75000, // $750
    category: "interior",
  },
  {
    envKey: "STRIPE_PRICE_INTERIOR_FULL",
    name: "Full Interior Package",
    description: "Permit-ready drawing set, full finish schedule, contractor-ready scope. Up to 5 revisions.",
    amount: 250000, // $2,500
    category: "interior",
  },
  // Whole Home
  {
    envKey: "STRIPE_PRICE_WHOLE_HOME_BASIC",
    name: "AI Whole Home Concept",
    description: "Floor plan direction, scope summary, material palette, rough cost range. 1 revision.",
    amount: 58500, // $585
    category: "whole_home",
  },
  {
    envKey: "STRIPE_PRICE_WHOLE_HOME_ADVANCED",
    name: "Advanced Whole Home Design",
    description: "3D views + detailed floor plans, contractor-ready scope, PM review. Up to 3 revisions.",
    amount: 120000, // $1,200
    category: "whole_home",
  },
  {
    envKey: "STRIPE_PRICE_WHOLE_HOME_FULL",
    name: "Full Whole Home Design Package",
    description: "Permit-ready drawing set, structural direction, full scope + trade assignments. Up to 5 revisions.",
    amount: 650000, // $6,500
    category: "whole_home",
  },
];

async function main() {
  console.log("Creating Stripe products...\n");
  const results: { envKey: string; priceId: string; productId: string; amount: number }[] = [];

  for (const p of PRODUCTS) {
    const product = await stripe.products.create({
      name: p.name,
      description: p.description,
      metadata: { category: p.category, source: "kealee_concept_engine" },
    });

    const price = await stripe.prices.create({
      product: product.id,
      unit_amount: p.amount,
      currency: "usd",
      metadata: { envKey: p.envKey },
    });

    results.push({ envKey: p.envKey, priceId: price.id, productId: product.id, amount: p.amount });
    console.log(`✅ ${p.name} → ${price.id}`);
  }

  console.log("\n\n# ── PASTE INTO Railway env vars ──────────────────────────────────────────\n");
  for (const r of results) {
    console.log(`${r.envKey}=${r.priceId}`);
  }

  console.log("\n# ── NEXT_PUBLIC versions (web-main) ──────────────────────────────────────\n");
  for (const r of results) {
    console.log(`NEXT_PUBLIC_${r.envKey}=${r.priceId}`);
  }

  // Also write to a file for safe keeping
  const { writeFileSync } = await import("fs");
  const lines = [
    "# Generated by scripts/create-concept-stripe-products.ts",
    "# Paste into Railway env vars for api + web-main services",
    "",
    ...results.map((r) => `${r.envKey}=${r.priceId}`),
    "",
    "# NEXT_PUBLIC versions for web-main",
    ...results.map((r) => `NEXT_PUBLIC_${r.envKey}=${r.priceId}`),
    "",
    "# Also needed on web-main (homeowner exterior — existing):",
    "NEXT_PUBLIC_STRIPE_PRICE_ESSENTIAL=price_1TCoMJIQghAs8OOIQofLrce5",
    "NEXT_PUBLIC_STRIPE_PRICE_PROFESSIONAL=price_1TCoMKIQghAs8OOIywkw884a",
    "NEXT_PUBLIC_STRIPE_PRICE_PREMIUM=price_1TCoMLIQghAs8OOI8pZ3PhKe",
  ];
  writeFileSync("stripe-concept-products-generated.env", lines.join("\n"));
  console.log("\n✅ Written to stripe-concept-products-generated.env");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
