#!/bin/bash
# scripts/setup-log-retention.sh
# Setup log retention policies

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() {
    echo -e "${BLUE}[LOGS]${NC} $1"
}

success() {
    echo -e "${GREEN}✅${NC} $1"
}

fail() {
    echo -e "${RED}❌${NC} $1"
}

warn() {
    echo -e "${YELLOW}⚠️${NC} $1"
}

echo "📋 Log Retention Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This script configures log retention policies."
echo ""

# Retention configuration
LOG_DIR=${LOG_DIR:-"logs"}
RETENTION_DAYS=${RETENTION_DAYS:-30}
RETENTION_DAYS_ERROR=${RETENTION_DAYS_ERROR:-90}  # Keep error logs longer
COMPRESS_AFTER_DAYS=${COMPRESS_AFTER_DAYS:-7}
DELETE_AFTER_DAYS=${DELETE_AFTER_DAYS:-$RETENTION_DAYS}

log "Log directory: $LOG_DIR"
log "Retention: $RETENTION_DAYS days (normal), $RETENTION_DAYS_ERROR days (errors)"
log "Compress after: $COMPRESS_AFTER_DAYS days"
echo ""

# Create log directory structure
log "Creating log directory structure..."
mkdir -p "$LOG_DIR"/{app,api,worker,nginx,access,error,audit}
success "Log directories created"

# Generate log retention script
RETENTION_SCRIPT="$LOG_DIR/retention.sh"
log "Generating log retention script: $RETENTION_SCRIPT"

cat > "$RETENTION_SCRIPT" << 'RETENTION_SCRIPT_EOF'
#!/bin/bash
# Log retention and cleanup script
# Generated by setup-log-retention.sh

set -e

LOG_DIR="${LOG_DIR:-logs}"
RETENTION_DAYS=${RETENTION_DAYS:-30}
RETENTION_DAYS_ERROR=${RETENTION_DAYS_ERROR:-90}
COMPRESS_AFTER_DAYS=${COMPRESS_AFTER_DAYS:-7}
DELETE_AFTER_DAYS=${DELETE_AFTER_DAYS:-$RETENTION_DAYS}

echo "🧹 Log Retention and Cleanup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Log directory: $LOG_DIR"
echo "   Retention: $RETENTION_DAYS days (normal), $RETENTION_DAYS_ERROR days (errors)"
echo "   Compress after: $COMPRESS_AFTER_DAYS days"
echo ""

# Compress logs older than COMPRESS_AFTER_DAYS
echo "📦 Compressing old logs..."
COMPRESSED=0
for logfile in $(find "$LOG_DIR" -type f -name "*.log" -mtime +$COMPRESS_AFTER_DAYS 2>/dev/null); do
    if [ ! -f "${logfile}.gz" ]; then
        gzip "$logfile"
        COMPRESSED=$((COMPRESSED + 1))
    fi
done
echo "   Compressed $COMPRESSED log file(s)"

# Delete old normal logs
echo "🗑️  Deleting old normal logs..."
DELETED=0
for logfile in $(find "$LOG_DIR" -type f \( -name "*.log.gz" -o -name "*.log" \) ! -path "*/error/*" ! -path "*/audit/*" -mtime +$DELETE_AFTER_DAYS 2>/dev/null); do
    rm -f "$logfile"
    DELETED=$((DELETED + 1))
done
echo "   Deleted $DELETED normal log file(s)"

# Delete old error logs (longer retention)
echo "🗑️  Deleting old error logs..."
ERROR_DELETED=0
for logfile in $(find "$LOG_DIR/error" -type f \( -name "*.log.gz" -o -name "*.log" \) -mtime +$RETENTION_DAYS_ERROR 2>/dev/null); do
    rm -f "$logfile"
    ERROR_DELETED=$((ERROR_DELETED + 1))
done
echo "   Deleted $ERROR_DELETED error log file(s)"

# Delete old audit logs (longer retention)
echo "🗑️  Deleting old audit logs..."
AUDIT_DELETED=0
for logfile in $(find "$LOG_DIR/audit" -type f \( -name "*.log.gz" -o -name "*.log" \) -mtime +$RETENTION_DAYS_ERROR 2>/dev/null); do
    rm -f "$logfile"
    AUDIT_DELETED=$((AUDIT_DELETED + 1))
done
echo "   Deleted $AUDIT_DELETED audit log file(s)"

# Log rotation summary
echo ""
echo "📊 Log Retention Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   Compressed: $COMPRESSED"
echo "   Deleted (normal): $DELETED"
echo "   Deleted (error): $ERROR_DELETED"
echo "   Deleted (audit): $AUDIT_DELETED"
echo ""
echo "✅ Log retention completed"
RETENTION_SCRIPT_EOF

chmod +x "$RETENTION_SCRIPT"
success "Log retention script created"

# Generate log rotation configuration
ROTATION_CONFIG="log-rotation.conf"
log "Generating log rotation configuration: $ROTATION_CONFIG"

cat > "$ROTATION_CONFIG" << ROTATION_EOF
# Log Rotation Configuration
# For use with logrotate (Linux) or similar tools

$LOG_DIR/*.log {
    daily
    rotate $RETENTION_DAYS
    compress
    delaycompress
    missingok
    notifempty
    create 0644 root root
    sharedscripts
    postrotate
        # Reload application if needed
        # systemctl reload your-app || true
    endscript
}

# Error logs - longer retention
$LOG_DIR/error/*.log {
    daily
    rotate $RETENTION_DAYS_ERROR
    compress
    delaycompress
    missingok
    notifempty
    create 0644 root root
}

# Audit logs - longer retention
$LOG_DIR/audit/*.log {
    daily
    rotate $RETENTION_DAYS_ERROR
    compress
    delaycompress
    missingok
    notifempty
    create 0644 root root
}

# Access logs
$LOG_DIR/access/*.log {
    daily
    rotate $RETENTION_DAYS
    compress
    delaycompress
    missingok
    notifempty
    create 0644 root root
}
ROTATION_EOF

success "Log rotation configuration created: $ROTATION_CONFIG"

# Generate cron configuration
CRON_FILE="log-retention-cron.txt"
log "Generating cron configuration: $CRON_FILE"

RETENTION_SCRIPT_ABS=$(realpath "$RETENTION_SCRIPT")

cat > "$CRON_FILE" << CRON_EOF
# Log Retention Cron Jobs
# Add these to your crontab: crontab -e

# Daily log retention at 3 AM
0 3 * * * cd $(pwd) && LOG_DIR=$LOG_DIR RETENTION_DAYS=$RETENTION_DAYS RETENTION_DAYS_ERROR=$RETENTION_DAYS_ERROR COMPRESS_AFTER_DAYS=$COMPRESS_AFTER_DAYS DELETE_AFTER_DAYS=$DELETE_AFTER_DAYS $RETENTION_SCRIPT_ABS >> $LOG_DIR/retention.log 2>&1

# Or use logrotate (recommended for Linux)
# 0 2 * * * /usr/sbin/logrotate -f $(realpath $ROTATION_CONFIG)
CRON_EOF

success "Cron configuration created: $CRON_FILE"

# Generate log retention configuration file
RETENTION_CONFIG_FILE="log-retention-config.txt"
log "Generating log retention configuration: $RETENTION_CONFIG_FILE"

cat > "$RETENTION_CONFIG_FILE" << CONFIG_EOF
# Log Retention Configuration
# Generated: $(date)

# Log Settings
LOG_DIR=$LOG_DIR

# Retention Policy
RETENTION_DAYS=$RETENTION_DAYS          # Normal logs
RETENTION_DAYS_ERROR=$RETENTION_DAYS_ERROR    # Error logs (longer)
RETENTION_DAYS_AUDIT=$RETENTION_DAYS_ERROR    # Audit logs (longer)
COMPRESS_AFTER_DAYS=$COMPRESS_AFTER_DAYS      # Compress logs after N days
DELETE_AFTER_DAYS=$DELETE_AFTER_DAYS          # Delete logs after N days

# Log Categories
# - Application logs: $RETENTION_DAYS days
# - API logs: $RETENTION_DAYS days
# - Worker logs: $RETENTION_DAYS days
# - Error logs: $RETENTION_DAYS_ERROR days
# - Audit logs: $RETENTION_DAYS_ERROR days
# - Access logs: $RETENTION_DAYS days

# Scripts
RETENTION_SCRIPT=$RETENTION_SCRIPT_ABS
ROTATION_CONFIG=$(realpath $ROTATION_CONFIG)

# Log Locations
# Application: $LOG_DIR/app/
# API: $LOG_DIR/api/
# Worker: $LOG_DIR/worker/
# Nginx: $LOG_DIR/nginx/
# Access: $LOG_DIR/access/
# Error: $LOG_DIR/error/
# Audit: $LOG_DIR/audit/

# Remote Log Storage (Optional)
# Consider archiving logs to S3, Google Cloud Storage, etc.
# Example: aws s3 sync $LOG_DIR s3://your-bucket/logs/
CONFIG_EOF

success "Log retention configuration saved: $RETENTION_CONFIG_FILE"

echo ""
echo "📋 Next Steps"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. ✅ Review log retention configuration: $RETENTION_CONFIG_FILE"
echo ""
echo "2. ✅ Test retention script:"
echo "   $RETENTION_SCRIPT_ABS"
echo ""
echo "3. ✅ Set up cron job or logrotate:"
echo "   # Option 1: Use cron"
echo "   crontab -e"
echo "   # Add contents from $CRON_FILE"
echo ""
echo "   # Option 2: Use logrotate (Linux, recommended)"
echo "   sudo cp $ROTATION_CONFIG /etc/logrotate.d/kealee"
echo ""
echo "4. ✅ (Optional) Set up remote log archiving:"
echo "   - AWS S3: aws s3 sync $LOG_DIR s3://your-bucket/logs/"
echo "   - Google Cloud: gsutil -m rsync -r $LOG_DIR gs://your-bucket/logs/"
echo "   - Cloudflare R2: rclone sync $LOG_DIR r2:your-bucket/logs/"
echo ""
echo "5. ✅ Monitor log retention:"
echo "   tail -f $LOG_DIR/retention.log"
echo ""
echo "6. ✅ Verify log sizes:"
echo "   du -sh $LOG_DIR/*"
