# OS-ADMIN Dependency Installation and Environment Setup Script
# This script installs dependencies and sets up environment variables for os-admin

param(
    [string]$Env = "development",
    [switch]$SkipInstall = $false
)

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "OS-ADMIN Setup Script" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

$ErrorActionPreference = "Stop"

# Get script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Split-Path -Parent $ScriptDir
$OsAdminDir = Join-Path $RootDir "apps\os-admin"

# Step 1: Install dependencies
if (-not $SkipInstall) {
    Write-Host "Step 1: Installing dependencies..." -ForegroundColor Yellow
    
    # Install from root to ensure workspace packages are linked
    Set-Location $RootDir
    
    Write-Host "  Running: pnpm install" -ForegroundColor Gray
    try {
        pnpm install
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  ⚠️  pnpm install had issues. Continuing anyway..." -ForegroundColor Yellow
        } else {
            Write-Host "  ✅ Dependencies installed successfully" -ForegroundColor Green
        }
    } catch {
        Write-Host "  ⚠️  Error installing dependencies: $_" -ForegroundColor Yellow
        Write-Host "  Continuing with environment setup..." -ForegroundColor Yellow
    }
    
    Write-Host ""
}

# Step 2: Create .env.local if it doesn't exist
Set-Location $OsAdminDir

$EnvFile = Join-Path $OsAdminDir ".env.local"
$EnvExample = Join-Path $OsAdminDir ".env.example"

Write-Host "Step 2: Setting up environment variables..." -ForegroundColor Yellow

if (-not (Test-Path $EnvFile)) {
    Write-Host "  Creating .env.local file..." -ForegroundColor Gray
    
    # Create .env.local with required variables
    $EnvContent = @"
# OS-ADMIN Environment Variables
# Generated by setup-os-admin.ps1

# Next.js
NODE_ENV=$Env
NEXT_PUBLIC_APP_NAME=os-admin
NEXT_PUBLIC_APP_ENV=$Env

# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:3001
# For production: https://api.kealee.com

# Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=

# Add your Supabase credentials above
# Get these from: https://app.supabase.com/project/_/settings/api
"@

    Set-Content -Path $EnvFile -Value $EnvContent
    Write-Host "  ✅ Created .env.local file" -ForegroundColor Green
    Write-Host "  ⚠️  Please add your Supabase credentials!" -ForegroundColor Yellow
} else {
    Write-Host "  ✅ .env.local already exists" -ForegroundColor Green
}

Write-Host ""

# Step 3: Verify required environment variables
Write-Host "Step 3: Verifying environment variables..." -ForegroundColor Yellow

$RequiredVars = @(
    "NEXT_PUBLIC_API_URL",
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY"
)

$MissingVars = @()

foreach ($var in $RequiredVars) {
    $value = [Environment]::GetEnvironmentVariable($var, "User")
    if ([string]::IsNullOrEmpty($value)) {
        # Check in .env.local file
        $fileContent = Get-Content $EnvFile -ErrorAction SilentlyContinue
        $found = $false
        foreach ($line in $fileContent) {
            if ($line -match "^$var=") {
                $found = $true
                $lineValue = $line -replace "^$var=", ""
                if (-not [string]::IsNullOrWhiteSpace($lineValue) -and $lineValue -ne '') {
                    break
                }
            }
        }
        if (-not $found) {
            $MissingVars += $var
        }
    }
}

if ($MissingVars.Count -gt 0) {
    Write-Host "  ⚠️  Missing environment variables:" -ForegroundColor Yellow
    foreach ($var in $MissingVars) {
        Write-Host "      - $var" -ForegroundColor Yellow
    }
    Write-Host ""
    Write-Host "  Please add these to .env.local:" -ForegroundColor White
    Write-Host "    $EnvFile" -ForegroundColor Gray
} else {
    Write-Host "  ✅ All required environment variables are set" -ForegroundColor Green
}

Write-Host ""

# Step 4: Verify build
Write-Host "Step 4: Verifying build setup..." -ForegroundColor Yellow

if (Test-Path (Join-Path $OsAdminDir "node_modules")) {
    Write-Host "  ✅ node_modules exists" -ForegroundColor Green
} else {
    Write-Host "  ⚠️  node_modules not found. Run 'pnpm install' from root" -ForegroundColor Yellow
}

if (Test-Path (Join-Path $OsAdminDir "next.config.ts")) {
    Write-Host "  ✅ Next.js config found" -ForegroundColor Green
} else {
    Write-Host "  ⚠️  Next.js config not found" -ForegroundColor Yellow
}

Write-Host ""

# Step 5: Summary
Write-Host "============================================================" -ForegroundColor Green
Write-Host "OS-ADMIN Setup Complete!" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Cyan
Write-Host "  1. Add Supabase credentials to .env.local" -ForegroundColor White
Write-Host "  2. Verify API_URL points to your backend" -ForegroundColor White
Write-Host "  3. Run: cd apps/os-admin && pnpm dev" -ForegroundColor White
Write-Host ""
Write-Host "Environment file: $EnvFile" -ForegroundColor Gray
Write-Host ""

# Return to original directory
Set-Location $RootDir




