# scripts/setup-backups.ps1
# Configure automated database backups (PowerShell version)

$ErrorActionPreference = "Continue"

param(
    [string]$BackupDir = "backups",
    [int]$RetentionDays = 7,
    [int]$RetentionWeeks = 4,
    [int]$RetentionMonths = 12
)

function Log-Backups {
    param([string]$Message)
    Write-Host "[BACKUPS] $Message" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "✅ $Message" -ForegroundColor Green
}

function Write-Fail {
    param([string]$Message)
    Write-Host "❌ $Message" -ForegroundColor Red
}

Write-Host "💾 Database Backup Configuration" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""

if (-not $env:DATABASE_URL) {
    Write-Fail "DATABASE_URL environment variable is not set"
    Write-Host "   Set it: `$env:DATABASE_URL = 'postgresql://...'"
    exit 1
}

$dbName = if ($env:DB_NAME) { $env:DB_NAME } else { "kealee_production" }

Log-Backups "Database: $dbName"
Log-Backups "Backup directory: $BackupDir"
Log-Backups "Retention: $RetentionDays days, $RetentionWeeks weeks, $RetentionMonths months"
Write-Host ""

# Create backup directory structure
Log-Backups "Creating backup directory structure..."
New-Item -ItemType Directory -Path "$BackupDir\daily" -Force | Out-Null
New-Item -ItemType Directory -Path "$BackupDir\weekly" -Force | Out-Null
New-Item -ItemType Directory -Path "$BackupDir\monthly" -Force | Out-Null
Write-Success "Backup directories created"

# Generate backup script
$backupScript = "$BackupDir\backup.ps1"
Log-Backups "Generating backup script: $backupScript"

$backupScriptContent = @"
# Automated database backup script
# Generated by setup-backups.ps1

`$ErrorActionPreference = "Stop"

`$backupDir = if (`$env:BACKUP_DIR) { `$env:BACKUP_DIR } else { "backups" }
`$dbName = if (`$env:DB_NAME) { `$env:DB_NAME } else { "kealee_production" }
`$databaseUrl = `$env:DATABASE_URL

if (-not `$databaseUrl) {
    Write-Error "DATABASE_URL not set"
    exit 1
}

`$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
`$dayOfWeek = (Get-Date).DayOfWeek.value__
`$dayOfMonth = (Get-Date).Day

# Daily backup
`$dailyBackup = Join-Path `$backupDir "daily\db_backup_${dbName}_`$timestamp.sql.gz"
Write-Host "Creating daily backup: `$dailyBackup"
try {
    & pg_dump `$databaseUrl | Out-File -FilePath `$dailyBackup -Encoding utf8
    # Note: PowerShell doesn't have built-in gzip, would need 7zip or similar
    Write-Host "✅ Daily backup created: `$dailyBackup"
} catch {
    Write-Error "Daily backup failed: `$(`$_.Exception.Message)"
    exit 1
}

# Weekly backup (on Sunday)
if (`$dayOfWeek -eq 0) {
    `$weeklyBackup = Join-Path `$backupDir "weekly\db_backup_${dbName}_week_`$(Get-Date -Format 'yyyyWW').sql.gz"
    Write-Host "Creating weekly backup: `$weeklyBackup"
    Copy-Item `$dailyBackup `$weeklyBackup
    Write-Host "✅ Weekly backup created: `$weeklyBackup"
}

# Monthly backup (on 1st of month)
if (`$dayOfMonth -eq 1) {
    `$monthlyBackup = Join-Path `$backupDir "monthly\db_backup_${dbName}_month_`$(Get-Date -Format 'yyyyMM').sql.gz"
    Write-Host "Creating monthly backup: `$monthlyBackup"
    Copy-Item `$dailyBackup `$monthlyBackup
    Write-Host "✅ Monthly backup created: `$monthlyBackup"
}

# Cleanup old backups
Write-Host "Cleaning up old backups..."

# Remove daily backups older than retention period
Get-ChildItem -Path "$BackupDir\daily" -Filter "*.sql.gz" | 
    Where-Object { `$_.LastWriteTime -lt (Get-Date).AddDays(-$RetentionDays) } | 
    Remove-Item -Force

# Remove weekly backups older than retention period
Get-ChildItem -Path "$BackupDir\weekly" -Filter "*.sql.gz" | 
    Where-Object { `$_.LastWriteTime -lt (Get-Date).AddDays(-($RetentionWeeks * 7)) } | 
    Remove-Item -Force

# Remove monthly backups older than retention period
Get-ChildItem -Path "$BackupDir\monthly" -Filter "*.sql.gz" | 
    Where-Object { `$_.LastWriteTime -lt (Get-Date).AddDays(-($RetentionMonths * 30)) } | 
    Remove-Item -Force

Write-Host "✅ Backup cleanup completed"
"@

$backupScriptContent | Out-File -FilePath $backupScript -Encoding utf8
Write-Success "Backup script created"

# Generate scheduled task configuration
$taskConfigFile = "backup-scheduled-task.txt"
Log-Backups "Generating scheduled task configuration: $taskConfigFile"

$taskConfig = @"
# Windows Scheduled Task Configuration
# Run in PowerShell as Administrator

# Create scheduled task for daily backup
`$action = New-ScheduledTaskAction -Execute "PowerShell.exe" -Argument "-File $((Get-Location).Path)\$backupScript"
`$trigger = New-ScheduledTaskTrigger -Daily -At 2am
`$principal = New-ScheduledTaskPrincipal -UserId "$env:USERNAME" -LogonType Interactive
Register-ScheduledTask -TaskName "Database Backup Daily" -Action `$action -Trigger `$trigger -Principal `$principal -Description "Daily database backup"

# Create scheduled task for weekly cleanup
`$cleanupAction = New-ScheduledTaskAction -Execute "PowerShell.exe" -Argument "-File $((Get-Location).Path)\$BackupDir\cleanup.ps1"
`$cleanupTrigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Sunday -At 3am
Register-ScheduledTask -TaskName "Database Backup Cleanup" -Action `$cleanupAction -Trigger `$cleanupTrigger -Principal `$principal -Description "Weekly backup cleanup"
"@

$taskConfig | Out-File -FilePath $taskConfigFile -Encoding utf8
Write-Success "Scheduled task configuration created: $taskConfigFile"

Write-Host ""
Write-Host "📋 Next Steps" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. ✅ Test backup script: .\$backupScript"
Write-Host "2. ✅ Set up scheduled task: .\$taskConfigFile"
Write-Host "3. ✅ (Optional) Set up remote backup to S3/R2"
Write-Host ""
