#!/bin/bash
# OS-ADMIN Dependency Installation and Environment Setup Script
# This script installs dependencies and sets up environment variables for os-admin

set -e

ENV=${1:-development}
SKIP_INSTALL=${2:-false}

echo ""
echo "============================================================"
echo "OS-ADMIN Setup Script"
echo "============================================================"
echo ""

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"
OS_ADMIN_DIR="$ROOT_DIR/apps/os-admin"

# Step 1: Install dependencies
if [ "$SKIP_INSTALL" != "true" ]; then
    echo "Step 1: Installing dependencies..."
    cd "$ROOT_DIR"
    
    echo "  Running: pnpm install"
    pnpm install || {
        echo "  ⚠️  pnpm install had issues. Continuing anyway..."
    }
    
    echo ""
fi

# Step 2: Create .env.local if it doesn't exist
cd "$OS_ADMIN_DIR"

ENV_FILE="$OS_ADMIN_DIR/.env.local"
ENV_EXAMPLE="$OS_ADMIN_DIR/.env.example"

echo "Step 2: Setting up environment variables..."

if [ ! -f "$ENV_FILE" ]; then
    echo "  Creating .env.local file..."
    
    cat > "$ENV_FILE" << EOF
# OS-ADMIN Environment Variables
# Generated by setup-os-admin.sh

# Next.js
NODE_ENV=$ENV
NEXT_PUBLIC_APP_NAME=os-admin
NEXT_PUBLIC_APP_ENV=$ENV

# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:3001
# For production: https://api.kealee.com

# Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=

# Add your Supabase credentials above
# Get these from: https://app.supabase.com/project/_/settings/api
EOF

    echo "  ✅ Created .env.local file"
    echo "  ⚠️  Please add your Supabase credentials!"
else
    echo "  ✅ .env.local already exists"
fi

echo ""

# Step 3: Verify required environment variables
echo "Step 3: Verifying environment variables..."

REQUIRED_VARS=(
    "NEXT_PUBLIC_API_URL"
    "NEXT_PUBLIC_SUPABASE_URL"
    "NEXT_PUBLIC_SUPABASE_ANON_KEY"
)

MISSING_VARS=()

for var in "${REQUIRED_VARS[@]}"; do
    if ! grep -q "^${var}=" "$ENV_FILE" 2>/dev/null || grep -q "^${var}=$" "$ENV_FILE" 2>/dev/null || grep -q "^${var}=\s*$" "$ENV_FILE" 2>/dev/null; then
        MISSING_VARS+=("$var")
    fi
done

if [ ${#MISSING_VARS[@]} -gt 0 ]; then
    echo "  ⚠️  Missing environment variables:"
    for var in "${MISSING_VARS[@]}"; do
        echo "      - $var"
    done
    echo ""
    echo "  Please add these to .env.local:"
    echo "    $ENV_FILE"
else
    echo "  ✅ All required environment variables are set"
fi

echo ""

# Step 4: Verify build
echo "Step 4: Verifying build setup..."

if [ -d "$OS_ADMIN_DIR/node_modules" ]; then
    echo "  ✅ node_modules exists"
else
    echo "  ⚠️  node_modules not found. Run 'pnpm install' from root"
fi

if [ -f "$OS_ADMIN_DIR/next.config.ts" ]; then
    echo "  ✅ Next.js config found"
else
    echo "  ⚠️  Next.js config not found"
fi

echo ""

# Step 5: Summary
echo "============================================================"
echo "OS-ADMIN Setup Complete!"
echo "============================================================"
echo ""
echo "Next Steps:"
echo "  1. Add Supabase credentials to .env.local"
echo "  2. Verify API_URL points to your backend"
echo "  3. Run: cd apps/os-admin && pnpm dev"
echo ""
echo "Environment file: $ENV_FILE"
echo ""

