#!/bin/bash
# scripts/setup-backups.sh
# Configure automated database backups

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() {
    echo -e "${BLUE}[BACKUPS]${NC} $1"
}

success() {
    echo -e "${GREEN}✅${NC} $1"
}

fail() {
    echo -e "${RED}❌${NC} $1"
}

warn() {
    echo -e "${YELLOW}⚠️${NC} $1"
}

echo "💾 Database Backup Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This script configures automated database backups."
echo ""

# Backup configuration
BACKUP_DIR=${BACKUP_DIR:-"backups"}
BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-7}
BACKUP_RETENTION_WEEKS=${BACKUP_RETENTION_WEEKS:-4}
BACKUP_RETENTION_MONTHS=${BACKUP_RETENTION_MONTHS:-12}

# Database configuration
DB_NAME=${DB_NAME:-"kealee_production"}
DB_USER=${DB_USER:-"kealee"}
DB_HOST=${DB_HOST:-""}
DB_PORT=${DB_PORT:-"5432"}

# Check if DATABASE_URL is set
if [ -z "$DATABASE_URL" ]; then
    if [ -z "$DB_HOST" ]; then
        fail "DATABASE_URL or DB_HOST is required"
        echo "   Set it: export DATABASE_URL='postgresql://...'"
        echo "   Or: export DB_HOST='your-db-host'"
        exit 1
    fi
    
    if [ -z "$DB_PASSWORD" ]; then
        fail "DB_PASSWORD is required"
        echo "   Set it: export DB_PASSWORD='your-password'"
        exit 1
    fi
    
    DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
fi

log "Database: $DB_NAME"
log "Backup directory: $BACKUP_DIR"
log "Retention: $BACKUP_RETENTION_DAYS days, $BACKUP_RETENTION_WEEKS weeks, $BACKUP_RETENTION_MONTHS months"
echo ""

# Create backup directory structure
log "Creating backup directory structure..."
mkdir -p "$BACKUP_DIR"/{daily,weekly,monthly}
success "Backup directories created"

# Generate backup script
BACKUP_SCRIPT="$BACKUP_DIR/backup.sh"
log "Generating backup script: $BACKUP_SCRIPT"

cat > "$BACKUP_SCRIPT" << 'BACKUP_SCRIPT_EOF'
#!/bin/bash
# Automated database backup script
# Generated by setup-backups.sh

set -e

BACKUP_DIR="${BACKUP_DIR:-backups}"
DB_NAME="${DB_NAME:-kealee_production}"
DATABASE_URL="${DATABASE_URL}"

if [ -z "$DATABASE_URL" ]; then
    echo "ERROR: DATABASE_URL not set"
    exit 1
fi

# Extract database name if not set
if [ -z "$DB_NAME" ]; then
    DB_NAME=$(echo $DATABASE_URL | sed -n 's/.*\/\([^?]*\).*/\1/p')
fi

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
DAY_OF_WEEK=$(date +%u)  # 1-7 (Monday-Sunday)
DAY_OF_MONTH=$(date +%d)  # 1-31

# Daily backup
DAILY_BACKUP="$BACKUP_DIR/daily/db_backup_${DB_NAME}_${TIMESTAMP}.sql.gz"
log "Creating daily backup: $DAILY_BACKUP"
if pg_dump "$DATABASE_URL" | gzip > "$DAILY_BACKUP"; then
    echo "✅ Daily backup created: $DAILY_BACKUP"
else
    echo "❌ Daily backup failed"
    exit 1
fi

# Weekly backup (on Sunday)
if [ "$DAY_OF_WEEK" -eq 7 ]; then
    WEEKLY_BACKUP="$BACKUP_DIR/weekly/db_backup_${DB_NAME}_week_$(date +%Y%W).sql.gz"
    log "Creating weekly backup: $WEEKLY_BACKUP"
    cp "$DAILY_BACKUP" "$WEEKLY_BACKUP"
    echo "✅ Weekly backup created: $WEEKLY_BACKUP"
fi

# Monthly backup (on 1st of month)
if [ "$DAY_OF_MONTH" -eq 1 ]; then
    MONTHLY_BACKUP="$BACKUP_DIR/monthly/db_backup_${DB_NAME}_month_$(date +%Y%m).sql.gz"
    log "Creating monthly backup: $MONTHLY_BACKUP"
    cp "$DAILY_BACKUP" "$MONTHLY_BACKUP"
    echo "✅ Monthly backup created: $MONTHLY_BACKUP"
fi

# Cleanup old backups
log "Cleaning up old backups..."

# Remove daily backups older than retention period
find "$BACKUP_DIR/daily" -name "*.sql.gz" -mtime +${BACKUP_RETENTION_DAYS:-7} -delete 2>/dev/null || true

# Remove weekly backups older than retention period
find "$BACKUP_DIR/weekly" -name "*.sql.gz" -mtime +$((BACKUP_RETENTION_WEEKS * 7)) -delete 2>/dev/null || true

# Remove monthly backups older than retention period
find "$BACKUP_DIR/monthly" -name "*.sql.gz" -mtime +$((BACKUP_RETENTION_MONTHS * 30)) -delete 2>/dev/null || true

echo "✅ Backup cleanup completed"
BACKUP_SCRIPT_EOF

chmod +x "$BACKUP_SCRIPT"
success "Backup script created"

# Generate cleanup script
CLEANUP_SCRIPT="$BACKUP_DIR/cleanup.sh"
log "Generating cleanup script: $CLEANUP_SCRIPT"

cat > "$CLEANUP_SCRIPT" << CLEANUP_SCRIPT_EOF
#!/bin/bash
# Backup cleanup script
# Removes old backups based on retention policy

set -e

BACKUP_DIR="${BACKUP_DIR:-backups}"
RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-7}
RETENTION_WEEKS=${BACKUP_RETENTION_WEEKS:-4}
RETENTION_MONTHS=${BACKUP_RETENTION_MONTHS:-12}

echo "🧹 Cleaning up old backups..."
echo "   Daily retention: $RETENTION_DAYS days"
echo "   Weekly retention: $RETENTION_WEEKS weeks"
echo "   Monthly retention: $RETENTION_MONTHS months"
echo ""

# Cleanup daily backups
DAILY_COUNT=$(find "$BACKUP_DIR/daily" -name "*.sql.gz" -mtime +$RETENTION_DAYS 2>/dev/null | wc -l)
if [ "$DAILY_COUNT" -gt 0 ]; then
    find "$BACKUP_DIR/daily" -name "*.sql.gz" -mtime +$RETENTION_DAYS -delete
    echo "✅ Removed $DAILY_COUNT daily backup(s)"
fi

# Cleanup weekly backups
WEEKLY_COUNT=$(find "$BACKUP_DIR/weekly" -name "*.sql.gz" -mtime +$((RETENTION_WEEKS * 7)) 2>/dev/null | wc -l)
if [ "$WEEKLY_COUNT" -gt 0 ]; then
    find "$BACKUP_DIR/weekly" -name "*.sql.gz" -mtime +$((RETENTION_WEEKS * 7)) -delete
    echo "✅ Removed $WEEKLY_COUNT weekly backup(s)"
fi

# Cleanup monthly backups
MONTHLY_COUNT=$(find "$BACKUP_DIR/monthly" -name "*.sql.gz" -mtime +$((RETENTION_MONTHS * 30)) 2>/dev/null | wc -l)
if [ "$MONTHLY_COUNT" -gt 0 ]; then
    find "$BACKUP_DIR/monthly" -name "*.sql.gz" -mtime +$((RETENTION_MONTHS * 30)) -delete
    echo "✅ Removed $MONTHLY_COUNT monthly backup(s)"
fi

echo ""
echo "✅ Cleanup completed"
CLEANUP_SCRIPT_EOF

chmod +x "$CLEANUP_SCRIPT"
success "Cleanup script created"

# Generate cron configuration
CRON_FILE="backup-cron.txt"
log "Generating cron configuration: $CRON_FILE"

BACKUP_SCRIPT_ABS=$(realpath "$BACKUP_SCRIPT")
CLEANUP_SCRIPT_ABS=$(realpath "$CLEANUP_SCRIPT")

cat > "$CRON_FILE" << CRON_EOF
# Database Backup Cron Jobs
# Add these to your crontab: crontab -e

# Daily backup at 2 AM
0 2 * * * cd $(pwd) && BACKUP_DIR=$BACKUP_DIR DATABASE_URL="$DATABASE_URL" DB_NAME=$DB_NAME $BACKUP_SCRIPT_ABS >> $BACKUP_DIR/backup.log 2>&1

# Weekly cleanup on Sunday at 3 AM
0 3 * * 0 cd $(pwd) && BACKUP_DIR=$BACKUP_DIR BACKUP_RETENTION_DAYS=$BACKUP_RETENTION_DAYS BACKUP_RETENTION_WEEKS=$BACKUP_RETENTION_WEEKS BACKUP_RETENTION_MONTHS=$BACKUP_RETENTION_MONTHS $CLEANUP_SCRIPT_ABS >> $BACKUP_DIR/cleanup.log 2>&1
CRON_EOF

success "Cron configuration created: $CRON_FILE"

# Generate backup configuration file
BACKUP_CONFIG_FILE="backup-config.txt"
log "Generating backup configuration: $BACKUP_CONFIG_FILE"

cat > "$BACKUP_CONFIG_FILE" << CONFIG_EOF
# Database Backup Configuration
# Generated: $(date)

# Backup Settings
BACKUP_DIR=$BACKUP_DIR
DATABASE_URL=$DATABASE_URL
DB_NAME=$DB_NAME

# Retention Policy
BACKUP_RETENTION_DAYS=$BACKUP_RETENTION_DAYS
BACKUP_RETENTION_WEEKS=$BACKUP_RETENTION_WEEKS
BACKUP_RETENTION_MONTHS=$BACKUP_RETENTION_MONTHS

# Backup Schedule
# - Daily: 2:00 AM
# - Weekly: Sunday 2:00 AM (keeps last 4 weeks)
# - Monthly: 1st of month 2:00 AM (keeps last 12 months)
# - Cleanup: Sunday 3:00 AM

# Scripts
BACKUP_SCRIPT=$BACKUP_SCRIPT_ABS
CLEANUP_SCRIPT=$CLEANUP_SCRIPT_ABS

# Remote Backup (Optional)
# Consider setting up remote backup to S3, Google Cloud Storage, etc.
# Example: aws s3 sync $BACKUP_DIR s3://your-bucket/backups/
CONFIG_EOF

success "Backup configuration saved: $BACKUP_CONFIG_FILE"

echo ""
echo "📋 Next Steps"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. ✅ Review backup configuration: $BACKUP_CONFIG_FILE"
echo ""
echo "2. ✅ Test backup script:"
echo "   $BACKUP_SCRIPT_ABS"
echo ""
echo "3. ✅ Set up cron job:"
echo "   crontab -e"
echo "   # Add contents from $CRON_FILE"
echo ""
echo "4. ✅ (Optional) Set up remote backup:"
echo "   - AWS S3: aws s3 sync $BACKUP_DIR s3://your-bucket/backups/"
echo "   - Google Cloud: gsutil -m rsync -r $BACKUP_DIR gs://your-bucket/backups/"
echo "   - Cloudflare R2: rclone sync $BACKUP_DIR r2:your-bucket/backups/"
echo ""
echo "5. ✅ Monitor backups:"
echo "   tail -f $BACKUP_DIR/backup.log"
echo ""
echo "6. ✅ Verify backup integrity periodically:"
echo "   gunzip -t $BACKUP_DIR/daily/db_backup_*.sql.gz"
