# scripts/setup-log-retention.ps1
# Setup log retention policies (PowerShell version)

$ErrorActionPreference = "Continue"

param(
    [string]$LogDir = "logs",
    [int]$RetentionDays = 30,
    [int]$RetentionDaysError = 90,
    [int]$CompressAfterDays = 7
)

function Log-Logs {
    param([string]$Message)
    Write-Host "[LOGS] $Message" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "✅ $Message" -ForegroundColor Green
}

Write-Host "📋 Log Retention Configuration" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""

Log-Logs "Log directory: $LogDir"
Log-Logs "Retention: $RetentionDays days (normal), $RetentionDaysError days (errors)"
Log-Logs "Compress after: $CompressAfterDays days"
Write-Host ""

# Create log directory structure
Log-Logs "Creating log directory structure..."
$logDirs = @("app", "api", "worker", "nginx", "access", "error", "audit")
foreach ($dir in $logDirs) {
    New-Item -ItemType Directory -Path "$LogDir\$dir" -Force | Out-Null
}
Write-Success "Log directories created"

# Generate log retention script
$retentionScript = "$LogDir\retention.ps1"
Log-Logs "Generating log retention script: $retentionScript"

$retentionScriptContent = @"
# Log retention and cleanup script
# Generated by setup-log-retention.ps1

`$ErrorActionPreference = "Continue"

`$logDir = if (`$env:LOG_DIR) { `$env:LOG_DIR } else { "logs" }
`$retentionDays = if (`$env:RETENTION_DAYS) { [int]`$env:RETENTION_DAYS } else { 30 }
`$retentionDaysError = if (`$env:RETENTION_DAYS_ERROR) { [int]`$env:RETENTION_DAYS_ERROR } else { 90 }
`$compressAfterDays = if (`$env:COMPRESS_AFTER_DAYS) { [int]`$env:COMPRESS_AFTER_DAYS } else { 7 }

Write-Host "🧹 Log Retention and Cleanup" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "   Log directory: `$logDir"
Write-Host "   Retention: `$retentionDays days (normal), `$retentionDaysError days (errors)"
Write-Host ""

# Compress logs older than compressAfterDays
Write-Host "📦 Compressing old logs..."
`$compressed = 0
Get-ChildItem -Path `$logDir -Recurse -Filter "*.log" | 
    Where-Object { `$_.LastWriteTime -lt (Get-Date).AddDays(-`$compressAfterDays) -and -not (Test-Path "`$(`$_.FullName).gz") } | 
    ForEach-Object {
        # Note: PowerShell doesn't have built-in gzip, would need 7zip or similar
        Write-Warn "Compression requires 7zip or similar tool"
        `$compressed++
    }
Write-Host "   Would compress `$compressed log file(s)"

# Delete old normal logs
Write-Host "🗑️  Deleting old normal logs..."
`$deleted = (Get-ChildItem -Path `$logDir -Recurse -Filter "*.log" | 
    Where-Object { 
        `$_.DirectoryName -notmatch "error|audit" -and 
        `$_.LastWriteTime -lt (Get-Date).AddDays(-`$retentionDays) 
    } | 
    Remove-Item -Force -PassThru).Count
Write-Host "   Deleted `$deleted normal log file(s)"

# Delete old error logs
Write-Host "🗑️  Deleting old error logs..."
`$errorDeleted = (Get-ChildItem -Path "$LogDir\error" -Filter "*.log" | 
    Where-Object { `$_.LastWriteTime -lt (Get-Date).AddDays(-`$retentionDaysError) } | 
    Remove-Item -Force -PassThru).Count
Write-Host "   Deleted `$errorDeleted error log file(s)"

# Delete old audit logs
Write-Host "🗑️  Deleting old audit logs..."
`$auditDeleted = (Get-ChildItem -Path "$LogDir\audit" -Filter "*.log" | 
    Where-Object { `$_.LastWriteTime -lt (Get-Date).AddDays(-`$retentionDaysError) } | 
    Remove-Item -Force -PassThru).Count
Write-Host "   Deleted `$auditDeleted audit log file(s)"

Write-Host ""
Write-Host "✅ Log retention completed" -ForegroundColor Green
"@

$retentionScriptContent | Out-File -FilePath $retentionScript -Encoding utf8
Write-Success "Log retention script created"

# Generate scheduled task configuration
$taskConfigFile = "log-retention-scheduled-task.txt"
Log-Logs "Generating scheduled task configuration: $taskConfigFile"

$taskConfig = @"
# Windows Scheduled Task Configuration
# Run in PowerShell as Administrator

`$action = New-ScheduledTaskAction -Execute "PowerShell.exe" -Argument "-File $((Get-Location).Path)\$retentionScript"
`$trigger = New-ScheduledTaskTrigger -Daily -At 3am
`$principal = New-ScheduledTaskPrincipal -UserId "$env:USERNAME" -LogonType Interactive
Register-ScheduledTask -TaskName "Log Retention" -Action `$action -Trigger `$trigger -Principal `$principal -Description "Daily log retention and cleanup"
"@

$taskConfig | Out-File -FilePath $taskConfigFile -Encoding utf8
Write-Success "Scheduled task configuration created: $taskConfigFile"

Write-Host ""
Write-Host "📋 Next Steps" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. ✅ Test retention script: .\$retentionScript"
Write-Host "2. ✅ Set up scheduled task: .\$taskConfigFile"
Write-Host "3. ✅ (Optional) Set up remote log archiving"
Write-Host ""
