import { JurisdictionSeed } from "../types";

// Source: official public portals — verified 2026-03-24
// Maintainer note: re-verify URLs annually as agencies rebrand portals

export const dmvJurisdictionSeeds: JurisdictionSeed[] = [
  {
    code: "dc",
    version: "1.0.0",
    status: "active",
    source: "official",
    lastVerifiedAt: "2026-03-24",
    notes: "DOB took over from DCRA in 2022. ProjectDox for plan review. Scout for permit tracking.",
    name: "District of Columbia",
    state: "DC",
    permitAuthority: "DC Department of Buildings (DOB)",
    zoningAuthority: "DC Office of Zoning (DCOZ)",
    permitPortalName: "DC DOB / ProjectDox / Scout",
    permitPortalUrl: "https://dob.dc.gov/service/building-permits",
    zoningMapUrl: "https://maps.dcoz.dc.gov",
    propertyLookupUrl: "https://scout.dc.gov",
    inspectionUrl: "https://dob.dc.gov/service/schedule-inspection",
    supportedProjectTypes: ["renovation", "addition", "new_build", "adu", "tenant_fit_out", "fence_deck", "interior_alteration"],
    requiredIntakeFields: ["address", "scopeSummary", "projectType"],
    riskFlags: ["historic_review_possible", "zoning_relief_possible", "occupancy_change_check", "public_space_permit_may_be_required", "hpab_review_if_historic_district"],
    reviewModel: "plan_review",
    onlineStatusLookup: true,
    onlineZoningLookup: true,
    requiredDocsByProjectType: {
      renovation: ["permit_application", "scope_of_work", "site_plan_if_exterior"],
      addition: ["permit_application", "architectural_drawings", "structural_calcs", "site_plan"],
      new_build: ["permit_application", "full_construction_documents", "soil_report", "survey"],
      adu: ["permit_application", "architectural_drawings", "zoning_compliance_letter"],
      tenant_fit_out: ["permit_application", "architectural_plans", "mep_drawings_if_applicable"],
    },
    commonApprovalBoundaries: ["historic_review_adds_60_to_120_days", "zoning_variance_adds_90_to_180_days", "public_space_permit_from_ddot"],
    typicalTimelineDays: { simple: 30, complex: 180 },
  },
  {
    code: "montgomery_md",
    version: "1.0.0",
    status: "active",
    source: "official",
    lastVerifiedAt: "2026-03-24",
    notes: "DPS handles building permits via eServices. Planning board separate for subdivision/zoning. Montgomery Planning handles zoning maps.",
    name: "Montgomery County, MD",
    state: "MD",
    permitAuthority: "Montgomery County Dept. of Permitting Services (DPS)",
    zoningAuthority: "Montgomery County Planning Dept. (M-NCPPC)",
    permitPortalName: "DPS eServices",
    permitPortalUrl: "https://permitting.montgomerycountymd.gov",
    zoningMapUrl: "https://montgomeryplanning.org/tools/gis-maps-and-data/",
    propertyLookupUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    inspectionUrl: "https://permitting.montgomerycountymd.gov/EnerGov_Prod/SelfService",
    supportedProjectTypes: ["renovation", "addition", "new_build", "adu", "fence_deck", "pool", "shed", "solar"],
    requiredIntakeFields: ["address", "projectType", "scopeSummary"],
    riskFlags: ["forest_conservation_check", "stream_buffer_check", "hoc_housing_check", "sediment_control_if_disturb_5k_sqft", "fire_marshal_review"],
    reviewModel: "plan_review",
    onlineStatusLookup: true,
    onlineZoningLookup: true,
    requiredDocsByProjectType: {
      renovation: ["permit_application", "contractor_license", "scope_of_work"],
      addition: ["permit_application", "site_plan", "architectural_drawings", "structural_calcs"],
      new_build: ["permit_application", "full_construction_documents", "grading_plan", "forest_conservation_plan"],
      adu: ["permit_application", "architectural_drawings", "zoning_eligibility_letter"],
    },
    commonApprovalBoundaries: ["hoa_approval_separate", "state_highway_permits_for_state_roads", "sediment_control_permit_separately"],
    typicalTimelineDays: { simple: 21, complex: 120 },
  },
  {
    code: "pg_md",
    version: "1.0.0",
    status: "active",
    source: "official",
    lastVerifiedAt: "2026-03-24",
    notes: "DPIE handles permits. Uses Momentum (ViewPoint Cloud) for online applications. Planning board handles zoning and subdivision.",
    name: "Prince George's County, MD",
    state: "MD",
    permitAuthority: "Prince George's County DPIE (Dept. of Permitting, Inspections and Enforcement)",
    zoningAuthority: "Prince George's County Planning Dept. (M-NCPPC)",
    permitPortalName: "DPIE / Momentum Online Permits",
    permitPortalUrl: "https://dpie.mypgc.us",
    zoningMapUrl: "https://pgplanning.org/resources/zoning/",
    propertyLookupUrl: "https://sdat.dat.maryland.gov/RealProperty/Pages/default.aspx",
    inspectionUrl: "https://dpie.mypgc.us",
    supportedProjectTypes: ["renovation", "addition", "new_build", "adu", "fence_deck", "pool", "shed", "commercial_ti"],
    requiredIntakeFields: ["address", "projectType", "scopeSummary"],
    riskFlags: ["chesapeake_bay_critical_area_check", "flood_zone_check", "forest_conservation_check", "dpie_code_enforcement_history_check"],
    reviewModel: "plan_review",
    onlineStatusLookup: true,
    onlineZoningLookup: true,
    requiredDocsByProjectType: {
      renovation: ["permit_application", "scope_of_work", "contractor_license"],
      addition: ["permit_application", "site_plan", "architectural_drawings"],
      new_build: ["permit_application", "full_construction_documents", "grading_plan", "forest_conservation_exemption_or_plan"],
      adu: ["permit_application", "architectural_drawings", "certificate_of_zoning_compliance"],
    },
    commonApprovalBoundaries: ["pgcps_school_excise_tax_for_new_units", "wssc_water_sewer_extension_permit", "state_highway_if_state_road"],
    typicalTimelineDays: { simple: 30, complex: 150 },
  },
  {
    code: "fairfax_va",
    version: "1.0.0",
    status: "active",
    source: "official",
    lastVerifiedAt: "2026-03-24",
    notes: "PLUS is the online portal for all permit applications. Fairfax has a formal ADU-by-right process (AHDU). PROFFERED zoning conditions common in older developments.",
    name: "Fairfax County, VA",
    state: "VA",
    permitAuthority: "Fairfax County Land Development Services (LDS)",
    zoningAuthority: "Fairfax County Planning Division",
    permitPortalName: "PLUS (Planning Land Use System)",
    permitPortalUrl: "https://plus.fairfaxcounty.gov",
    zoningMapUrl: "https://www.fairfaxcounty.gov/planning-zoning/",
    propertyLookupUrl: "https://icare.fairfaxcounty.gov/ffxapps/icare/",
    inspectionUrl: "https://www.fairfaxcounty.gov/lds/building-construction-inspections",
    supportedProjectTypes: ["renovation", "addition", "new_build", "adu", "fence_deck", "pool", "shed", "commercial_ti"],
    requiredIntakeFields: ["address", "projectType", "scopeSummary"],
    riskFlags: ["proffer_conditions_check", "rpa_resource_protection_area_check", "hoa_likely", "adu_ahdu_eligibility_check", "data_center_corridor"],
    reviewModel: "plan_review",
    onlineStatusLookup: true,
    onlineZoningLookup: true,
    requiredDocsByProjectType: {
      renovation: ["permit_application", "scope_of_work", "contractor_registration"],
      addition: ["permit_application", "site_plan", "architectural_drawings", "structural_calcs"],
      new_build: ["permit_application", "full_construction_documents", "site_plan", "rpa_analysis"],
      adu: ["permit_application", "architectural_drawings", "ahdu_checklist"],
    },
    commonApprovalBoundaries: ["vdot_entrance_permit_if_state_road", "nvta_transportation_impact_analysis", "fairfax_water_connection_permit"],
    typicalTimelineDays: { simple: 21, complex: 90 },
  },
  {
    code: "arlington_va",
    version: "1.0.0",
    status: "active",
    source: "official",
    lastVerifiedAt: "2026-03-24",
    notes: "Arlington has aggressive ADU and missing middle housing policies. Form-based code in certain corridors. Strong HOA presence in older neighborhoods.",
    name: "Arlington County, VA",
    state: "VA",
    permitAuthority: "Arlington County CPHD — Building Inspections",
    zoningAuthority: "Arlington County CPHD — Zoning",
    permitPortalName: "Arlington Online Permit Center",
    permitPortalUrl: "https://www.arlingtonva.us/Government/Departments/Community-Planning-Housing-Development/Permits",
    zoningMapUrl: "https://gis.arlingtonva.us/",
    propertyLookupUrl: "https://www.arlingtonva.us/Government/Departments/Real-Estate-Assessments/Real-Estate-Search",
    inspectionUrl: "https://www.arlingtonva.us/Government/Departments/Community-Planning-Housing-Development/Permits/Inspections",
    supportedProjectTypes: ["renovation", "addition", "new_build", "adu", "fence_deck", "pool", "missing_middle"],
    requiredIntakeFields: ["address", "projectType"],
    riskFlags: ["hoa_check", "form_based_code_corridor_check", "missing_middle_review", "rpa_check", "vdot_permit_if_state_road"],
    reviewModel: "hybrid",
    onlineStatusLookup: true,
    onlineZoningLookup: true,
    requiredDocsByProjectType: {
      renovation: ["permit_application", "scope_of_work"],
      addition: ["permit_application", "site_plan", "architectural_drawings"],
      new_build: ["permit_application", "full_construction_documents", "site_plan", "arlington_residential_design_guidelines_compliance"],
      adu: ["permit_application", "adu_checklist", "architectural_drawings"],
    },
    commonApprovalBoundaries: ["board_of_zoning_appeals_for_variances", "vdot_entrance_permit", "wmata_proximity_review_if_near_metro"],
    typicalTimelineDays: { simple: 14, complex: 90 },
  },
  {
    code: "alexandria_va",
    version: "1.0.0",
    status: "active",
    source: "official",
    lastVerifiedAt: "2026-03-24",
    notes: "City of Alexandria — independent city, not Fairfax. Large historic districts (Old Town, Parker-Gray). BAR (Board of Architectural Review) for historic properties.",
    name: "City of Alexandria, VA",
    state: "VA",
    permitAuthority: "Alexandria Building & Fire Codes (DCHS)",
    zoningAuthority: "Alexandria Dept. of Planning & Zoning",
    permitPortalName: "Alexandria Online Permit Center",
    permitPortalUrl: "https://www.alexandriava.gov/Building-permits",
    zoningMapUrl: "https://www.alexandriava.gov/ZoningInformation",
    propertyLookupUrl: "https://www.alexandriava.gov/RealEstate",
    inspectionUrl: "https://www.alexandriava.gov/Building-Inspections",
    supportedProjectTypes: ["renovation", "addition", "new_build", "adu", "fence_deck", "historic_alteration", "commercial_ti"],
    requiredIntakeFields: ["address", "projectType", "scopeSummary"],
    riskFlags: ["historic_district_bar_review", "old_town_design_review", "parker_gray_review", "flood_zone_check", "hoa_check"],
    reviewModel: "plan_review",
    onlineStatusLookup: true,
    onlineZoningLookup: true,
    requiredDocsByProjectType: {
      renovation: ["permit_application", "scope_of_work", "bar_application_if_historic"],
      addition: ["permit_application", "site_plan", "architectural_drawings", "bar_application_if_historic"],
      new_build: ["permit_application", "full_construction_documents", "site_plan", "design_review"],
      adu: ["permit_application", "architectural_drawings", "zoning_eligibility"],
    },
    commonApprovalBoundaries: ["bar_review_adds_30_to_90_days", "vdot_permit_if_state_road", "alexandria_sanitation_authority_connection"],
    typicalTimelineDays: { simple: 21, complex: 120 },
  },
  {
    code: "loudoun_va",
    version: "1.0.0",
    status: "active",
    source: "official",
    lastVerifiedAt: "2026-03-24",
    notes: "Fast-growing jurisdiction. Large data center presence in eastern corridor. ZOAM (zoning ordinance amendment) process for PDH/PD-TRC. Strong HOA presence in planned communities.",
    name: "Loudoun County, VA",
    state: "VA",
    permitAuthority: "Loudoun County Dept. of Building & Development",
    zoningAuthority: "Loudoun County Dept. of Planning & Zoning",
    permitPortalName: "Loudoun Online Permit Portal",
    permitPortalUrl: "https://www.loudoun.gov/permits",
    zoningMapUrl: "https://www.loudoun.gov/2248/Zoning-District-Maps",
    propertyLookupUrl: "https://web.loudoun.gov/landRecords/",
    inspectionUrl: "https://www.loudoun.gov/inspections",
    supportedProjectTypes: ["renovation", "addition", "new_build", "adu", "fence_deck", "agricultural_building", "pool", "commercial_ti"],
    requiredIntakeFields: ["address", "projectType"],
    riskFlags: ["hoa_likely", "rpa_check", "bmp_stormwater_check", "data_center_corridor_eastern_loudoun", "pdh_proffers_check"],
    reviewModel: "plan_review",
    onlineStatusLookup: true,
    onlineZoningLookup: true,
    requiredDocsByProjectType: {
      renovation: ["permit_application", "scope_of_work"],
      addition: ["permit_application", "site_plan", "architectural_drawings", "structural_calcs"],
      new_build: ["permit_application", "full_construction_documents", "stormwater_management_plan", "grading_plan"],
      adu: ["permit_application", "architectural_drawings", "zoning_compliance"],
    },
    commonApprovalBoundaries: ["vdot_land_use_permit_for_entrances", "lcsa_connection_permit", "bpw_stormwater_review"],
    typicalTimelineDays: { simple: 21, complex: 100 },
  },
];
