import { JurisdictionSeed } from "../types";

// Source: official public government portals — verified 2026-03-24
// Maintainer: re-verify URLs and portal names annually as agencies rebrand

export const jurisdictionSeeds: JurisdictionSeed[] = [
  {
    code: "dc",
    version: "1.0.0",
    status: "active",
    source: "official_dc_dob_dcoz",
    lastVerifiedAt: "2026-03-24",
    name: "District of Columbia",
    state: "DC",
    permitAuthority: "DC Department of Buildings",
    zoningAuthority: "DC Office of Zoning",
    permitPortalName: "DOB / ProjectDox / Scout",
    permitPortalUrl: "https://dob.dc.gov/page/get-permit",
    zoningMapUrl: "https://maps.dcoz.dc.gov/zr16/",
    propertyLookupUrl: "https://scout.dcra.dc.gov/",
    inspectionUrl: "https://dob.dc.gov/page/permit-resources",
    permitStatusUrl: "https://scout.dcra.dc.gov/",
    planUploadSystem: "ProjectDox",
    supportedProjectTypes: ["renovation", "addition", "new_build", "adu", "tenant_fit_out", "commercial_improvement"],
    commonPermitTypes: ["building", "trade", "demolition", "certificate_of_occupancy", "revision"],
    requiredIntakeFields: ["address", "scopeSummary"],
    commonRiskFlags: ["historic_review_possible", "zoning_relief_possible", "occupancy_change_check", "public_space_or_ddot_dependency"],
    reviewModel: "mixed",
    notesForKeaCore: [
      "Use Scout for permit/property context where record number exists.",
      "Use DCOZ map to resolve zone by address.",
      "ProjectDox likely involved for plan submissions requiring electronic review."
    ]
  },
  {
    code: "montgomery_md",
    version: "1.0.0",
    status: "active",
    source: "official_moco_dps",
    lastVerifiedAt: "2026-03-24",
    name: "Montgomery County",
    state: "MD",
    permitAuthority: "Montgomery County Department of Permitting Services",
    zoningAuthority: "Montgomery County DPS / M-NCPPC zoning framework",
    permitPortalName: "DPS eServices",
    permitPortalUrl: "https://www.montgomerycountymd.gov/DPS/Services/eServices.html",
    zoningMapUrl: "https://mcatlas.org/zoning/",
    propertyLookupUrl: "https://experience.arcgis.com/experience/70fde40e4c1d4af7a9a011abf29b697a",
    inspectionUrl: "https://www.montgomerycountymd.gov/DPS/Services/inspections.html",
    permitStatusUrl: "https://permittingservices.montgomerycountymd.gov/dps/online/esearch.aspx",
    planUploadSystem: "ePlans / DPS eServices",
    supportedProjectTypes: ["renovation", "addition", "new_build", "solar", "commercial_improvement", "trade_permit"],
    commonPermitTypes: ["residential_building", "commercial_building", "electrical", "mechanical", "plumbing", "fire"],
    requiredIntakeFields: ["address", "scopeSummary"],
    commonRiskFlags: ["zoning_compliance_check", "site_plan_dependency_possible", "inspector_assignment_dependency"],
    reviewModel: "mixed",
    notesForKeaCore: [
      "DPS provides online apply/pay/upload/schedule inspection/status tools.",
      "Digital zoning map can be used to anchor early zoning checks.",
      "My Inspector and Property Map is useful for property and inspection context."
    ]
  },
  {
    code: "prince_georges_md",
    version: "1.0.0",
    status: "active",
    source: "official_pgc_dpie_momentum",
    lastVerifiedAt: "2026-03-24",
    name: "Prince George's County",
    state: "MD",
    permitAuthority: "Department of Permitting, Inspections and Enforcement",
    zoningAuthority: "Prince George's County Planning / County zoning process",
    permitPortalName: "Momentum",
    permitPortalUrl: "https://www.princegeorgescountymd.gov/departments-offices/permitting-inspections-and-enforcement/permits/online-permit-services",
    zoningMapUrl: "https://pgplanning.org/data-tools/maps/",
    propertyLookupUrl: "https://momentumhome.princegeorgescountymd.gov/",
    inspectionUrl: "https://www.princegeorgescountymd.gov/departments-offices/permitting-inspections-and-enforcement/permits/permits-inspections-search-status-and-history",
    permitStatusUrl: "https://www.princegeorgescountymd.gov/departments-offices/permitting-inspections-and-enforcement/permits/permits-inspections-search-status-and-history",
    planUploadSystem: "Momentum / ePlan",
    supportedProjectTypes: ["renovation", "addition", "new_build", "site_road", "trade_permit", "commercial_improvement"],
    commonPermitTypes: ["building", "trade", "site_road", "grading", "commercial_improvement"],
    requiredIntakeFields: ["address", "scopeSummary"],
    commonRiskFlags: ["plan_review_tracker_dependency", "planning_department_dependency", "virtual_permit_center_eligibility_check"],
    reviewModel: "mixed",
    notesForKeaCore: [
      "Momentum is the county-wide permit/licenses system.",
      "Use permit/inspection status page plus LookSee/App Tracker where records exist.",
      "PGAtlas / planning GIS should feed zoning and parcel context."
    ]
  },
  {
    code: "fairfax_va",
    version: "1.0.0",
    status: "active",
    source: "official_fairfax_plus",
    lastVerifiedAt: "2026-03-24",
    name: "Fairfax County",
    state: "VA",
    permitAuthority: "Fairfax County Planning, Permitting and Construction / Land Development Services",
    zoningAuthority: "Fairfax County Department of Planning and Development",
    permitPortalName: "PLUS",
    permitPortalUrl: "https://plus.fairfaxcounty.gov/",
    zoningMapUrl: "https://www.fairfaxcounty.gov/planning-development/how-do-i-find-my-zoning-district",
    propertyLookupUrl: "https://www.fairfaxcounty.gov/maps/",
    inspectionUrl: "https://www.fairfaxcounty.gov/plan2build/scheduling-building-inspections-plus",
    permitStatusUrl: "https://plus.fairfaxcounty.gov/",
    planUploadSystem: "PLUS",
    supportedProjectTypes: ["renovation", "addition", "new_build", "land_development", "commercial_improvement", "trade_permit"],
    commonPermitTypes: ["building", "trade", "zoning", "land_development"],
    requiredIntakeFields: ["address", "scopeSummary"],
    commonRiskFlags: ["zoning_district_dependency", "plus_record_dependency", "virtual_or_in_person_inspection_branching"],
    reviewModel: "mixed",
    notesForKeaCore: [
      "PLUS is the central application/status/payment platform.",
      "Use zoning district analyzer and digital map viewer to anchor zoning/property context.",
      "Inspection scheduling is online through PLUS/FIDO pathways."
    ]
  },
  {
    code: "arlington_va",
    version: "1.0.0",
    status: "active",
    source: "official_arlington_permit_arlington",
    lastVerifiedAt: "2026-03-24",
    name: "Arlington County",
    state: "VA",
    permitAuthority: "Arlington County Building / Permit Arlington",
    zoningAuthority: "Arlington County Zoning",
    permitPortalName: "Permit Arlington",
    permitPortalUrl: "https://www.arlingtonva.us/Government/Programs/Building/Permits/Permit-Arlington",
    zoningMapUrl: "https://experience.arcgis.com/experience/40721a7da2d243dca52b67b5594868f6",
    propertyLookupUrl: "https://www.arlingtonva.us/Government/Programs/Maps",
    inspectionUrl: "https://www.arlingtonva.us/Government/Programs/Building/Inspections",
    permitStatusUrl: "https://aca-prod.accela.com/arlingtonco/Default.aspx",
    planUploadSystem: "Accela / Permit Arlington",
    supportedProjectTypes: ["renovation", "addition", "new_build", "right_of_way", "trade_permit"],
    commonPermitTypes: ["building", "zoning", "enforcement", "right_of_way", "trade"],
    requiredIntakeFields: ["address", "scopeSummary"],
    commonRiskFlags: ["zoning_boundary_dependency", "right_of_way_dependency", "inspection_holder_responsibility"],
    reviewModel: "mixed",
    notesForKeaCore: [
      "Permit Arlington is the online permitting initiative/system.",
      "Zoning lookup supports address-based zoning district checks.",
      "Inspection handling should assume permit-holder scheduling responsibility unless noted otherwise."
    ]
  },
  {
    code: "alexandria_va",
    version: "1.0.0",
    status: "active",
    source: "official_alexandria_apex",
    lastVerifiedAt: "2026-03-24",
    name: "City of Alexandria",
    state: "VA",
    permitAuthority: "City of Alexandria Permit Center",
    zoningAuthority: "City of Alexandria Planning & Zoning",
    permitPortalName: "APEX",
    permitPortalUrl: "https://www.alexandriava.gov/Permits",
    zoningMapUrl: "https://www.alexandriava.gov/Zoning",
    propertyLookupUrl: "https://www.alexandriava.gov/GIS",
    inspectionUrl: "https://www.alexandriava.gov/PermitCenter",
    permitStatusUrl: "https://www.alexandriava.gov/Permits",
    planUploadSystem: "APEX",
    supportedProjectTypes: ["renovation", "addition", "new_build", "land_use", "commercial_improvement"],
    commonPermitTypes: ["building", "land_use", "trade", "site_plan_related"],
    requiredIntakeFields: ["address", "scopeSummary"],
    commonRiskFlags: ["zoning_ordinance_lookup_required", "land_use_path_dependency", "gis_parcel_lookup_required"],
    reviewModel: "mixed",
    notesForKeaCore: [
      "APEX supports application, plan submission/review, payments, inspections, and status tracking.",
      "Use GIS parcel/zoning resources to resolve zoning context by address.",
      "Land use path may differ from pure building permit path."
    ]
  },
  {
    code: "loudoun_va",
    version: "1.0.0",
    status: "active",
    source: "official_loudoun_landmarc",
    lastVerifiedAt: "2026-03-24",
    name: "Loudoun County",
    state: "VA",
    permitAuthority: "Loudoun County Department of Building and Development",
    zoningAuthority: "Loudoun County Department of Planning and Zoning",
    permitPortalName: "LandMARC",
    permitPortalUrl: "https://www.loudoun.gov/5823/LandMARC-Land-Management-Applications-Re",
    zoningMapUrl: "https://www.loudoun.gov/2598/Zoning",
    propertyLookupUrl: "https://www.loudoun.gov/weblogis",
    inspectionUrl: "https://www.loudoun.gov/4264/Permitting",
    permitStatusUrl: "https://www.loudoun.gov/4264/Permitting",
    planUploadSystem: "LandMARC / CSS",
    supportedProjectTypes: ["renovation", "addition", "new_build", "grading", "zoning_permit", "land_development"],
    commonPermitTypes: ["building", "grading", "zoning", "land_development"],
    requiredIntakeFields: ["address", "scopeSummary"],
    commonRiskFlags: ["town_jurisdiction_overlap", "zoning_permit_branching", "land_development_dependency"],
    reviewModel: "mixed",
    notesForKeaCore: [
      "LandMARC handles online applications, plans, fees, inspections, and records.",
      "WebLogis is useful for address/parcel map lookup.",
      "County permits differ from incorporated-town permitting in some cases."
    ]
  }
];
