import type { BotId } from './bots.types'

export const BOT_IDS = [
  'lead-bot',
  'owner-bot',
  'gc-bot',
  'feasibility-bot',
  'command-bot',
  'design-bot',
  'estimate-bot',
  'permit-bot',
  'contractor-match-bot',
  'project-monitor-bot',
  'support-bot',
  'marketing-bot',
  'finance-bot',
  'developer-bot',
  'construction-bot',
  'land-bot',
  'payments-bot',
  'operations-bot',
  'pitch-bot',
  'email-subject-bot',
  'google-ad-bot',
  'meta-ad-bot',
  'day1-email-bot',
  'day8-email-bot',
] as const satisfies readonly BotId[]
