/**
 * Generation records (spec §13): every Kealee generation is a `GenerationRun`
 * with its inputs (source artifacts, retrieved context, rules, the request)
 * and its outputs (artifacts ingested with GENERATED_FROM lineage to every
 * source-artifact input). Outputs enter the registry as AI_GENERATED; they
 * become anything more only through `disposeGeneration` by a person.
 */
import { createHash } from 'node:crypto'
import type { KnowledgeDb } from '../db'
import type { EventSink } from '../events'
import { KNOWLEDGE_EVENTS, MemoryEventSink } from '../events'
import { redactJson } from '../policies'
import type { KnowledgeRegistry } from '../registry'
import type { GenerationRunRecord, KnowledgeArtifactRecord, RecordGenerationInput } from '../types'

export class GenerationRecorder {
  constructor(private readonly db: KnowledgeDb, private readonly registry: KnowledgeRegistry, private readonly events: EventSink = new MemoryEventSink()) {}

  async recordGeneration(input: RecordGenerationInput): Promise<{ run: GenerationRunRecord; outputs: KnowledgeArtifactRecord[] }> {
    const startedAt = input.startedAt ?? new Date()
    const completedAt = input.completedAt ?? (input.status && input.status !== 'STARTED' ? new Date() : null)
    const promptHash = input.promptText ? createHash('sha256').update(input.promptText).digest('hex') : null
    const request = redactJson(input.request ?? null).value
    const run: GenerationRunRecord = await this.db.generationRun.create({ data: {
      organizationId: input.organizationId ?? null, projectId: input.projectId ?? null, orderId: input.orderId ?? null,
      productType: input.productType, agent: input.agent, agentVersion: input.agentVersion ?? null,
      model: input.model ?? null, modelParameters: input.modelParameters ?? null,
      promptId: input.promptId ?? null, promptVersion: input.promptVersion ?? null, promptHash,
      requestSummary: input.requestSummary ?? null, request,
      rulesUsed: input.rulesUsed ?? null, toolsExecuted: redactJson(input.toolsExecuted ?? null).value,
      status: input.status ?? 'COMPLETED', confidence: input.confidence ?? null,
      startedAt, completedAt, durationMs: completedAt ? Math.max(0, completedAt.getTime() - startedAt.getTime()) : null,
      errorMessage: input.errorMessage ?? null, workflowId: input.workflowId ?? null, jobKey: input.jobKey ?? null,
      metadata: redactJson(input.metadata ?? null).value,
    } })
    const sourceArtifactIds: string[] = []
    for (const i of input.inputs ?? []) {
      await this.db.generationInput.create({ data: { runId: run.id, role: i.role, artifactId: i.artifactId ?? null, reference: i.reference ?? null, content: redactJson(i.content ?? null).value } })
      if (i.role === 'SOURCE_ARTIFACT' && i.artifactId) sourceArtifactIds.push(i.artifactId)
    }
    const outputs: KnowledgeArtifactRecord[] = []
    for (const o of input.outputs ?? []) {
      const { role, ...art } = o
      const { artifact } = await this.registry.ingestArtifact({
        ...art,
        organizationId: art.organizationId ?? input.organizationId ?? null, projectId: art.projectId ?? input.projectId ?? null, orderId: art.orderId ?? input.orderId ?? null,
        generationRunId: run.id, generatedByAgent: art.generatedByAgent ?? input.agent, generatedByModel: art.generatedByModel ?? input.model ?? null,
        approvalStatus: art.approvalStatus ?? 'AI_GENERATED',
        lineage: [...(art.lineage ?? []), ...sourceArtifactIds.map(objectId => ({ objectId, relation: 'GENERATED_FROM' as const, note: `by ${input.agent}` }))],
        actor: { type: 'agent', id: input.agent },
      })
      await this.db.generationOutput.create({ data: { runId: run.id, artifactId: artifact.id, role: role ?? 'primary' } })
      outputs.push(artifact)
    }
    await this.db.learningEvent.create({ data: { eventType: 'GENERATION_RECORDED', organizationId: run.organizationId, projectId: run.projectId, orderId: run.orderId, artifactId: outputs[0]?.id ?? null, generationRunId: run.id, actorType: 'agent', actorId: input.agent, summary: `${input.productType} generated by ${input.agent}${input.model ? ` (${input.model})` : ''}: ${input.requestSummary ?? ''}`.trim(), payload: { inputs: (input.inputs ?? []).length, outputs: outputs.length, status: run.status } } })
    await this.events.emit({ type: run.status === 'FAILED' ? KNOWLEDGE_EVENTS.generation.completed : KNOWLEDGE_EVENTS.generation.completed, source: 'knowledge', projectId: run.projectId, orgId: run.organizationId, entity: { type: 'generation_run', id: run.id }, payload: { productType: input.productType, agent: input.agent, model: input.model ?? null, status: run.status, outputs: outputs.map(o => o.id) }, initiatorType: 'AI', initiatorId: input.agent })
    return { run, outputs }
  }

  /** What a person did with the generation. Moves every output's approval with it. */
  async disposeGeneration(runId: string, disposition: 'accepted' | 'corrected' | 'rejected' | 'superseded', actor: { id: string; note?: string }): Promise<GenerationRunRecord> {
    const status = disposition === 'accepted' ? 'APPROVED' : disposition === 'corrected' ? 'CORRECTED' : disposition === 'rejected' ? 'REJECTED' : 'SUPERSEDED'
    const run: GenerationRunRecord = await this.db.generationRun.update({ where: { id: runId }, data: { status, finalDisposition: disposition, dispositionById: actor.id, dispositionAt: new Date() } })
    const outs = await this.db.generationOutput.findMany({ where: { runId } })
    for (const o of outs) {
      await this.registry.setApproval(o.artifactId, disposition === 'accepted' ? 'HUMAN_APPROVED' : disposition === 'corrected' ? 'HUMAN_REVIEWED' : disposition === 'rejected' ? 'REJECTED' : 'AI_GENERATED', { type: 'user', id: actor.id, note: actor.note })
    }
    const evt = disposition === 'accepted' ? KNOWLEDGE_EVENTS.generation.approved : disposition === 'rejected' ? KNOWLEDGE_EVENTS.generation.rejected : KNOWLEDGE_EVENTS.generation.corrected
    await this.db.learningEvent.create({ data: { eventType: disposition === 'accepted' ? 'GENERATION_APPROVED' : disposition === 'rejected' ? 'GENERATION_REJECTED' : 'GENERATION_CORRECTED', organizationId: run.organizationId, projectId: run.projectId, orderId: run.orderId, artifactId: outs[0]?.artifactId ?? null, generationRunId: runId, actorType: 'user', actorId: actor.id, summary: `${run.productType} run ${disposition} by ${actor.id}${actor.note ? `: ${actor.note}` : ''}`, payload: { disposition } } })
    await this.events.emit({ type: evt, source: 'knowledge', projectId: run.projectId, orgId: run.organizationId, entity: { type: 'generation_run', id: runId }, payload: { disposition, actor: actor.id }, initiatorType: 'USER', initiatorId: actor.id })
    return run
  }

  async getRun(id: string): Promise<(GenerationRunRecord & { inputs: unknown[]; outputs: unknown[] }) | null> {
    const run = await this.db.generationRun.findUnique({ where: { id } })
    if (!run) return null
    const [inputs, outputs] = await Promise.all([this.db.generationInput.findMany({ where: { runId: id } }), this.db.generationOutput.findMany({ where: { runId: id } })])
    return { ...run, inputs, outputs }
  }
}
