import { PrismaClient } from "@prisma/client";

const faqs = [
  {
    number: 1,
    section: "Section 1: What Is AI Concept Generation?",
    sectionSlug: "understanding",
    tags: ["ai-trust", "basics"],
    order: 1,
    question: "What exactly is AI Concept Generation?",
    answer: "AI Concept Generation is Kealee's automated design service that produces professional architectural concept drawings, site plans, and project renderings using advanced artificial intelligence \u2014 in 48 hours or less. You describe your project, choose a package, and our AI produces a complete visual concept you can review, revise, and use to move forward into full architecture and permitting.",
  },
  {
    number: 2,
    section: "Section 1: What Is AI Concept Generation?",
    sectionSlug: "understanding",
    tags: ["ai-trust", "basics"],
    order: 2,
    question: "Is this a real design service or just a computer-generated image?",
    answer: "It\u2019s a real, usable design deliverable \u2014 not just a pretty picture. Your AI concept includes scaled drawings, space planning, exterior/interior views (depending on your package), and a written project summary. These are the same foundational documents a traditional architect would produce in the early concept phase, just delivered in 48 hours instead of 3\u20136 weeks.",
  },
  {
    number: 3,
    section: "Section 1: What Is AI Concept Generation?",
    sectionSlug: "understanding",
    tags: ["ai-trust", "comparison"],
    order: 3,
    question: "How is AI different from hiring an architect?",
    answer: "Traditional architects charge $150\u2013$400/hour for early concept work that takes weeks. Our AI produces the same concept-phase deliverables in 48 hours at a fraction of the cost. The key difference: AI Concept Generation covers the early ideation and visualization stage. If your project moves forward, a licensed architect on our platform handles the full construction drawings, stamped plans, and permit submissions.",
  },
  {
    number: 4,
    section: "Section 1: What Is AI Concept Generation?",
    sectionSlug: "understanding",
    tags: ["basics"],
    order: 4,
    question: "Who is AI Concept Generation designed for?",
    answer: "It\u2019s built for two groups: (1) Property owners and developers who want to visualize and cost-validate a project before committing to expensive architect fees, and (2) Commercial contractors and businesses who need fast, professional concept documentation to present to clients, lenders, or local planning offices. Both residential and commercial projects are supported.",
  },
  {
    number: 5,
    section: "Section 1: What Is AI Concept Generation?",
    sectionSlug: "understanding",
    tags: ["process", "permits"],
    order: 5,
    question: "Can I use the AI concept to apply for permits?",
    answer: "Not directly. AI concepts are ideation and pre-design documents \u2014 they\u2019re great for planning approvals, lender presentations, client approvals, and design direction. To pull permits, you need stamped construction documents from a licensed architect, which is our Architecture phase. However, your AI concept becomes the foundation for that work, saving significant time and cost.",
  },
  {
    number: 6,
    section: "Section 1: What Is AI Concept Generation?",
    sectionSlug: "understanding",
    tags: ["basics"],
    order: 6,
    question: "What types of projects can AI Concept Generation handle?",
    answer: "We support residential additions, new home construction, ADUs (accessory dwelling units), commercial tenant improvements, office build-outs, retail spaces, mixed-use buildings, and light industrial facilities. If you\u2019re unsure whether your project qualifies, our KeaBot assistant can evaluate it in minutes.",
  },
  {
    number: 7,
    section: "Section 1: What Is AI Concept Generation?",
    sectionSlug: "understanding",
    tags: ["basics"],
    order: 7,
    question: "Is this service available outside the DC-Baltimore area?",
    answer: "AI Concept Generation is available nationwide \u2014 your concept is produced digitally and delivered online. However, if your project moves into Architecture, Permits, and Construction phases, Kealee\u2019s full-service support is strongest in the DC, Maryland, and Virginia corridor, where we have licensed architects and vetted contractors on the platform.",
  },
  {
    number: 8,
    section: "Section 1: What Is AI Concept Generation?",
    sectionSlug: "understanding",
    tags: ["ai-trust"],
    order: 8,
    question: "How accurate are the AI-generated designs?",
    answer: "The AI is trained on 500,000+ construction and architectural drawings, achieving approximately 94% accuracy in layout, proportion, and code-compliance considerations at the concept level. Your concept will reflect your stated project parameters, site constraints, and stylistic preferences. Revisions are included to fine-tune anything that doesn\u2019t match your vision.",
  },
  {
    number: 9,
    section: "Section 2: Pricing & Packages",
    sectionSlug: "pricing",
    tags: ["pricing"],
    featured: true,
    order: 9,
    question: "What are the AI Concept Generation packages and prices?",
    answer: "We offer four packages: Starter ($99) covers basic floor plan and exterior elevation for simple residential projects. Standard ($299) adds interior layouts, multiple elevations, and a project summary \u2014 ideal for most residential additions and small commercial jobs. Professional ($599) includes 3D renderings, site plan, detailed space programming, and a preliminary cost estimate. Enterprise ($899) delivers everything in Professional plus multiple design alternatives, a lender-ready package, and a planning board presentation set.",
  },
  {
    number: 10,
    section: "Section 2: Pricing & Packages",
    sectionSlug: "pricing",
    tags: ["pricing"],
    order: 10,
    question: "Why does the Starter package cost only $99?",
    answer: "Because AI eliminates the overhead of manual drafting, we can pass those savings directly to you. A traditional architectural firm would charge $1,500\u2013$5,000+ for the same deliverables. Our $99 Starter package gives you a professional starting point without the traditional price barrier \u2014 so you can validate your idea before investing further.",
  },
  {
    number: 11,
    section: "Section 2: Pricing & Packages",
    sectionSlug: "pricing",
    tags: ["pricing"],
    order: 11,
    question: "What\u2019s included in each package? Can I see a sample?",
    answer: "Yes \u2014 each service page on our website includes a downloadable sample concept package so you can see exactly what you\u2019ll receive before purchasing. The deliverables scale with package level: Starter gives you 2D floor plan + exterior elevation; Standard adds interior views and written summary; Professional adds 3D renderings and cost estimate; Enterprise adds design alternatives and presentation materials.",
  },
  {
    number: 12,
    section: "Section 2: Pricing & Packages",
    sectionSlug: "pricing",
    tags: ["pricing", "process"],
    order: 12,
    question: "Can I upgrade my package after purchasing?",
    answer: "Yes. If you purchase a Starter and decide you need the 3D renderings or cost estimate from Professional, you can upgrade at any time. You only pay the difference in price \u2014 not the full package cost again. Contact our team or use KeaBot to initiate an upgrade.",
  },
  {
    number: 13,
    section: "Section 2: Pricing & Packages",
    sectionSlug: "pricing",
    tags: ["pricing"],
    order: 13,
    question: "Are there any hidden fees?",
    answer: "No. Your package price is all-inclusive for the deliverables listed. The only additional costs would be: (1) If you request revisions beyond the included rounds (see revision policy), or (2) If you choose to move into Architecture, Permits, or Construction phases \u2014 each of which has its own separate pricing clearly listed on the platform.",
  },
  {
    number: 14,
    section: "Section 2: Pricing & Packages",
    sectionSlug: "pricing",
    tags: ["pricing"],
    order: 14,
    question: "Do you offer discounts for multiple projects?",
    answer: "Yes \u2014 contractors and developers with multiple active projects can apply for a Kealee Pro account, which provides volume pricing on AI Concept packages and priority turnaround. Contact our team to discuss your project pipeline and we\u2019ll build a custom arrangement.",
  },
  {
    number: 15,
    section: "Section 2: Pricing & Packages",
    sectionSlug: "pricing",
    tags: ["pricing"],
    featured: true,
    order: 15,
    question: "Is there a money-back guarantee?",
    answer: "Yes. If we cannot deliver your concept within 48 hours, or if the deliverables don\u2019t match the scope described on the service page, you\u2019re entitled to a full refund. We also offer one free revision round on all packages. Our goal is for you to be confident moving forward \u2014 not to feel locked into something that doesn\u2019t work for you.",
  },
  {
    number: 16,
    section: "Section 2: Pricing & Packages",
    sectionSlug: "pricing",
    tags: ["pricing", "payments"],
    order: 16,
    question: "Can I pay in installments?",
    answer: "AI Concept packages ($99\u2013$899) are pay-in-full at checkout via credit card, ACH, or digital payment. For clients moving into Architecture or full project management phases, we offer milestone-based payment schedules. Kealee\u2019s escrow system holds funds and releases them as project milestones are completed, protecting both you and the service providers.",
  },
  {
    number: 17,
    section: "Section 2: Pricing & Packages",
    sectionSlug: "pricing",
    tags: ["pricing", "comparison"],
    order: 17,
    question: "How does this price compare to hiring an architect directly?",
    answer: "An architect typically charges 10\u201315% of total project cost for full services, or $150\u2013$400/hour for early concept work. A basic concept package from a firm often runs $2,000\u2013$10,000 before you\u2019ve seen a single drawing. Kealee\u2019s AI Concept packages start at $99 and deliver professional-grade concept documents in 48 hours \u2014 making the entry cost 95%+ lower than traditional methods.",
  },
  {
    number: 18,
    section: "Section 3: How AI Works & Can I Trust It?",
    sectionSlug: "ai-trust",
    tags: ["ai-trust"],
    featured: true,
    order: 18,
    question: "I\u2019ve never used AI for construction before. Should I be worried?",
    answer: "Completely understandable \u2014 AI in construction is new for most people. Here\u2019s the reassurance: the AI handles the time-consuming drafting work that architects typically spend weeks on. It doesn\u2019t replace human judgment \u2014 it accelerates it. Every concept goes through a quality review before delivery, and you have full revision rights. Think of it the way GPS changed driving: the technology handles complex calculation, but you still decide where you\u2019re going.",
  },
  {
    number: 19,
    section: "Section 3: How AI Works & Can I Trust It?",
    sectionSlug: "ai-trust",
    tags: ["ai-trust"],
    order: 19,
    question: "What AI technology does Kealee use?",
    answer: "Our concept generation system uses a ResNet-50 and CLIP-based architecture for visual design generation, trained on over 500,000 construction drawings and architectural projects. Document organization uses OCR combined with DistilBERT, and our KeaBot assistant runs on a fine-tuned GPT-4 model trained on 100,000+ customer conversations and construction domain knowledge. All AI operates in the background \u2014 you never need to configure or manage it.",
  },
  {
    number: 20,
    section: "Section 3: How AI Works & Can I Trust It?",
    sectionSlug: "ai-trust",
    tags: ["ai-trust", "process"],
    order: 20,
    question: "Will the AI understand my specific project requirements?",
    answer: "Yes. When you submit your project, you provide key inputs: square footage, lot dimensions, intended use, number of rooms/spaces, style preferences, and any specific constraints. The AI uses these parameters as the foundation for your concept. The more detail you provide, the more accurate your first draft will be. The intake form walks you through every question step by step.",
  },
  {
    number: 21,
    section: "Section 3: How AI Works & Can I Trust It?",
    sectionSlug: "ai-trust",
    tags: ["ai-trust", "process"],
    order: 21,
    question: "What if the AI gets something wrong?",
    answer: "Every package includes at least one revision round. If your concept misses the mark on layout, style, or scope, submit revision notes and we\u2019ll update it \u2014 typically within 24 hours. For Professional and Enterprise packages, multiple revision rounds are included. Our quality review process catches most issues before delivery, but revisions are always available if needed.",
  },
  {
    number: 22,
    section: "Section 3: How AI Works & Can I Trust It?",
    sectionSlug: "ai-trust",
    tags: ["ai-trust", "permits"],
    order: 22,
    question: "Is the AI compliant with local building codes?",
    answer: "AI Concept Generation reflects general best practices and common code considerations at the concept level \u2014 it is not a code compliance review. Your full code compliance review happens during the Architecture phase when a licensed architect produces your stamped construction documents. The AI does flag common issues (setback violations, ceiling height minimums, egress requirements) to help you avoid obvious problems early.",
  },
  {
    number: 23,
    section: "Section 3: How AI Works & Can I Trust It?",
    sectionSlug: "ai-trust",
    tags: ["ai-trust", "process"],
    order: 23,
    question: "Who reviews the AI output before I receive it?",
    answer: "Every AI concept package goes through a platform quality review before delivery. Our team checks that the deliverables match your project description, are formatted correctly, and meet our quality standards. For Professional and Enterprise packages, a project coordinator reviews the concept in detail and may reach out with clarifying questions before finalizing.",
  },
  {
    number: 24,
    section: "Section 3: How AI Works & Can I Trust It?",
    sectionSlug: "ai-trust",
    tags: ["ai-trust"],
    order: 24,
    question: "Has AI Concept Generation been used on real projects?",
    answer: "Yes. Kealee has been in construction since 2002, and our AI platform has been used on commercial and residential projects throughout DC, Maryland, and Virginia. AI-accelerated projects have achieved 40\u201350% faster concept-to-permit timelines compared to traditional processes. We have case studies available \u2014 contact our team to request project examples relevant to your scope.",
  },
  {
    number: 25,
    section: "Section 3: How AI Works & Can I Trust It?",
    sectionSlug: "ai-trust",
    tags: ["ai-trust"],
    order: 25,
    question: "Can the AI handle complex or unusual projects?",
    answer: "The AI performs best on standard residential and commercial project types. For highly complex or unusual projects \u2014 landmark properties, historic renovations, highly custom architectural work \u2014 we recommend starting with a Professional or Enterprise package and using the included consultation to align expectations. Complex projects may benefit from transitioning directly to our Architecture phase for a more hands-on approach.",
  },
  {
    number: 26,
    section: "Section 4: The Process \u2014 Step by Step",
    sectionSlug: "process",
    tags: ["process"],
    featured: true,
    order: 26,
    question: "How do I get started?",
    answer: "Go to the AI Concept Generation page, choose your package, and click Purchase. You\u2019ll be walked through a project intake form (takes about 10\u201315 minutes) where you describe your project, upload any existing site plans or photos if you have them, and specify your design preferences. After payment processes, your project enters our AI pipeline immediately.",
  },
  {
    number: 27,
    section: "Section 4: The Process \u2014 Step by Step",
    sectionSlug: "process",
    tags: ["process"],
    order: 27,
    question: "What information do I need to provide?",
    answer: "You\u2019ll need: property address or general location, project type (addition, new build, renovation, etc.), approximate square footage, number of rooms or spaces, intended use (residential, commercial, mixed), any style preferences (modern, traditional, industrial, etc.), and specific requirements or constraints. You can also upload photos of the existing property, neighboring buildings for context, or inspiration images.",
  },
  {
    number: 28,
    section: "Section 4: The Process \u2014 Step by Step",
    sectionSlug: "process",
    tags: ["process"],
    order: 28,
    question: "What happens after I submit my project information?",
    answer: "Your project immediately enters the AI generation queue. The system processes your inputs, generates your concept drawings and documents, and a quality review is completed \u2014 all within 48 hours. You\u2019ll receive an email notification when your concept is ready, and you can view, download, and review everything directly in your Kealee project dashboard.",
  },
  {
    number: 29,
    section: "Section 4: The Process \u2014 Step by Step",
    sectionSlug: "process",
    tags: ["process"],
    featured: true,
    order: 29,
    question: "How long does it actually take to receive my concept?",
    answer: "Standard delivery is within 48 hours of your completed submission. For Professional and Enterprise packages, it\u2019s still 48 hours \u2014 the additional deliverables are generated in parallel, not sequentially. If there\u2019s ever a delay beyond 48 hours, you\u2019ll be notified proactively and may be eligible for a partial refund of your package fee.",
  },
  {
    number: 30,
    section: "Section 4: The Process \u2014 Step by Step",
    sectionSlug: "process",
    tags: ["process", "platform"],
    order: 30,
    question: "What does my project dashboard look like?",
    answer: "Your Kealee project dashboard is your central hub. You can see your project status in real time, view and download all deliverables, submit revision notes, communicate with our team, track any follow-on phases (Architecture, Permits, Construction), and manage payments. It\u2019s designed to work on desktop and mobile.",
  },
  {
    number: 31,
    section: "Section 4: The Process \u2014 Step by Step",
    sectionSlug: "process",
    tags: ["process"],
    order: 31,
    question: "How do I request revisions?",
    answer: "From your project dashboard, open your concept review and click \u2018Request Revision.\u2019 A simple form lets you describe what you\u2019d like changed \u2014 you can attach reference images or annotate specific areas of the drawings. Revisions are typically delivered within 24 hours. Standard packages include one revision round; Professional includes two; Enterprise includes three.",
  },
  {
    number: 32,
    section: "Section 4: The Process \u2014 Step by Step",
    sectionSlug: "process",
    tags: ["process", "next-steps"],
    order: 32,
    question: "What happens after my concept is approved?",
    answer: "That\u2019s entirely up to you. You can: (1) Use the concept for your own planning without moving forward, (2) Share it with contractors for early budget conversations, (3) Present it to lenders, stakeholders, or planning boards, or (4) Move forward into the Architecture phase where a licensed architect develops full construction documents based on your approved concept. There\u2019s no obligation to continue on the Kealee platform.",
  },
  {
    number: 33,
    section: "Section 4: The Process \u2014 Step by Step",
    sectionSlug: "process",
    tags: ["process", "next-steps"],
    featured: true,
    order: 33,
    question: "When does contractor matching happen?",
    answer: "Contractor matching does not begin until your design is finalized and permits are approved. This is an important distinction \u2014 we match you with vetted contractors only after you have approved construction documents, so contractors are bidding on a defined, permitted scope. This protects you from vague bids and mid-project scope disputes.",
  },
  {
    number: 34,
    section: "Section 4: The Process \u2014 Step by Step",
    sectionSlug: "process",
    tags: ["process"],
    order: 34,
    question: "Can I pause my project midway?",
    answer: "Yes. Your project and all deliverables remain in your Kealee dashboard indefinitely. If you need to pause \u2014 for budget reasons, personal timing, or any other reason \u2014 simply leave your project in its current state. When you\u2019re ready to resume, pick up exactly where you left off. There are no time limits or expiration dates on your account.",
  },
  {
    number: 35,
    section: "Section 4: The Process \u2014 Step by Step",
    sectionSlug: "process",
    tags: ["process"],
    order: 35,
    question: "What if I want to change the scope after my concept is delivered?",
    answer: "Scope changes after concept delivery depend on the extent of the change. Minor adjustments (room sizes, material preferences, layout tweaks) are handled through the revision process. Major scope changes (adding a second story, changing the project type, doubling square footage) may require a new concept submission. Contact our team and we\u2019ll advise on the best path forward \u2014 often we can apply a credit from your original purchase.",
  },
  {
    number: 36,
    section: "Section 5: Kealee vs. Traditional Options",
    sectionSlug: "comparison",
    tags: ["comparison"],
    order: 36,
    question: "Why should I use Kealee instead of hiring a local architect directly?",
    answer: "Kealee is not a replacement for your architect \u2014 it\u2019s a faster, lower-cost entry point to the same process. Traditional concept work takes 3\u20136 weeks and costs $2,000\u2013$10,000+. Kealee delivers it in 48 hours for $99\u2013$899. If you move into our Architecture phase, you get a licensed architect for your stamped documents at competitive rates, plus the platform coordination, permit services, and contractor matching all in one place.",
  },
  {
    number: 37,
    section: "Section 5: Kealee vs. Traditional Options",
    sectionSlug: "comparison",
    tags: ["comparison"],
    order: 37,
    question: "How is Kealee different from online tools like Canva or SmartDraw for floor plans?",
    answer: "Consumer floor plan tools are great for simple layouts, but they don\u2019t produce construction-grade documents. Kealee\u2019s AI generates documents that meet architectural drawing standards, include proper scale, and are formatted for use in the professional construction workflow \u2014 including serving as the basis for licensed architect drawings and permit submissions. It\u2019s a professional tool, not a design toy.",
  },
  {
    number: 38,
    section: "Section 5: Kealee vs. Traditional Options",
    sectionSlug: "comparison",
    tags: ["comparison"],
    order: 38,
    question: "What about services like Fiverr or Upwork for cheap architectural drawings?",
    answer: "Freelance platforms can be economical, but come with risks: inconsistent quality, unknown credentials, no accountability if the drawings don\u2019t meet code, and no connection to the next steps of your project. Kealee provides a consistent, platform-managed process with quality review, revision rights, and a clear path from concept through permits and construction \u2014 all with a company that\u2019s been in commercial construction since 2002.",
  },
  {
    number: 39,
    section: "Section 5: Kealee vs. Traditional Options",
    sectionSlug: "comparison",
    tags: ["comparison", "ai-trust"],
    order: 39,
    question: "Is Kealee\u2019s AI faster than a traditional architect?",
    answer: "Yes \u2014 significantly. AI concept generation takes 48 hours vs. 3\u20136 weeks for a traditional architect. Our full Architecture phase (licensed, stamped drawings) is 40\u201350% faster than traditional firms due to AI-assisted drafting. Permit submission is 30% faster through our electronic submission process. Overall project timelines are reduced by 30%+ compared to traditional methods.",
  },
  {
    number: 40,
    section: "Section 5: Kealee vs. Traditional Options",
    sectionSlug: "comparison",
    tags: ["basics"],
    order: 40,
    question: "Kealee is MBE-certified \u2014 what does that mean for my project?",
    answer: "MBE stands for Minority Business Enterprise, a certification recognizing Kealee Construction LLC as a minority-owned business. For clients with MBE/DBE participation goals on government contracts or projects with equity requirements, Kealee\u2019s involvement can help meet those targets. For all clients, MBE certification reflects our track record of meeting rigorous third-party business standards.",
  },
  {
    number: 41,
    section: "Section 6: Technical Questions & Platform",
    sectionSlug: "platform",
    tags: ["platform"],
    order: 41,
    question: "Do I need any special software to view my concept deliverables?",
    answer: "No. All concept deliverables are delivered as PDF files viewable in any web browser or PDF reader. No AutoCAD, no special software. If you move into the Architecture phase and need DWG files for your own use, those can be provided upon request.",
  },
  {
    number: 42,
    section: "Section 6: Technical Questions & Platform",
    sectionSlug: "platform",
    tags: ["platform"],
    order: 42,
    question: "Is my project information secure?",
    answer: "Yes. Your project data \u2014 including property details, design documents, and personal information \u2014 is stored securely using Supabase\u2019s enterprise-grade database infrastructure with encryption at rest and in transit. Kealee does not sell or share your project data with third parties. You retain full ownership of all deliverables.",
  },
  {
    number: 43,
    section: "Section 6: Technical Questions & Platform",
    sectionSlug: "platform",
    tags: ["platform"],
    order: 43,
    question: "Can multiple people on my team access the project dashboard?",
    answer: "Yes. Your Kealee account supports team access \u2014 you can invite partners, employees, or advisors to view and collaborate on your project dashboard. Access levels are customizable so you control who can view, comment, or take action on your project.",
  },
  {
    number: 44,
    section: "Section 6: Technical Questions & Platform",
    sectionSlug: "platform",
    tags: ["platform", "ai-trust"],
    featured: true,
    order: 44,
    question: "How does KeaBot work and what can it help me with?",
    answer: "KeaBot is Kealee\u2019s AI assistant, available 24/7 on the platform. It can answer questions about your project, explain the process, help you choose the right package, estimate timelines, and connect you to a human team member when needed. KeaBot is trained on construction domain knowledge and Kealee\u2019s specific services \u2014 it gives you answers relevant to your actual project, not generic responses.",
  },
  {
    number: 45,
    section: "Section 6: Technical Questions & Platform",
    sectionSlug: "platform",
    tags: ["platform"],
    order: 45,
    question: "What file formats are included in my concept deliverables?",
    answer: "Standard delivery includes PDF drawings and a PDF project summary. Professional and Enterprise packages also include a JPEG/PNG rendering set suitable for presentations. If you need specific formats for other software or presentations, contact our team after delivery and we\u2019ll accommodate where possible.",
  },
  {
    number: 46,
    section: "Section 6: Technical Questions & Platform",
    sectionSlug: "platform",
    tags: ["platform", "process"],
    order: 46,
    question: "Can I upload my own existing drawings or site plans?",
    answer: "Yes, and we strongly encourage it. Uploading existing surveys, site plans, or as-built drawings gives the AI better spatial context and produces a more accurate first concept. Supported upload formats include PDF, JPG, PNG, and DWG. There\u2019s no limit on uploads per project.",
  },
  {
    number: 47,
    section: "Section 7: Moving Forward \u2014 Concept to Construction",
    sectionSlug: "next-steps",
    tags: ["next-steps", "process"],
    featured: true,
    order: 47,
    question: "What happens after AI Concept Generation if I want to build?",
    answer: "The path forward has four clear phases: (1) Architecture \u2014 a licensed architect develops your full construction documents based on your approved concept (4\u20138 weeks, AI-accelerated); (2) Permits \u2014 electronic submission to your local jurisdiction (30% faster than traditional); (3) Contractor Matching \u2014 once permits are approved, we match you with vetted contractors who bid on your defined scope; (4) Construction \u2014 with optional Kealee PM oversight. Each phase is optional and priced separately.",
  },
  {
    number: 48,
    section: "Section 7: Moving Forward \u2014 Concept to Construction",
    sectionSlug: "next-steps",
    tags: ["next-steps"],
    order: 48,
    question: "How does Kealee ensure I\u2019m matched with a good contractor?",
    answer: "Contractor matching only happens after your project has approved permits and defined construction documents. Contractors on the Kealee platform are vetted for licensing, insurance, bonding, and performance history. They bid on your specific, documented scope \u2014 so you\u2019re comparing apples to apples, not vague estimates. Kealee\u2019s escrow system protects your payments, releasing funds only as milestones are verified.",
  },
  {
    number: 49,
    section: "Section 7: Moving Forward \u2014 Concept to Construction",
    sectionSlug: "next-steps",
    tags: ["next-steps"],
    order: 49,
    question: "Does Kealee manage construction after it starts?",
    answer: "Optional. Kealee offers Project Management packages ($1,750\u2013$16,500/month) for clients who want professional PM oversight of their construction phase. Our PM platform uses AI to reduce administrative work by 64%, giving your project manager more time on actual site and quality management. You can also manage construction independently using your Kealee project dashboard.",
  },
  {
    number: 50,
    section: "Section 7: Moving Forward \u2014 Concept to Construction",
    sectionSlug: "next-steps",
    tags: ["next-steps", "pricing"],
    order: 50,
    question: "What\u2019s the total cost of a project from concept to completion?",
    answer: "That depends entirely on your project scope. Here\u2019s a general framework: AI Concept ($99\u2013$899) + Architecture ($2,500\u2013$35,000) + Permits ($495\u2013$7,500) + Construction (contractor bids based on your scope) + optional PM ($1,750\u2013$16,500/month). Kealee\u2019s AI-accelerated process saves you 30%+ on timeline costs and 40\u201350% on the Architecture phase compared to traditional firms. Use our free Budget Calculator tool to get a project-specific estimate.",
  },
];

export async function seedFaqs(prisma: PrismaClient) {
  console.log("Seeding FAQs...");

  const result = await prisma.faq.createMany({
    data: faqs,
    skipDuplicates: true,
  });

  console.log(`Seeded ${result.count} FAQ records (${faqs.length} total, duplicates skipped)`);
  return result.count;
}

// Allow running directly: npx tsx prisma/seeds/faqs.ts
async function main() {
  const prisma = new PrismaClient();

  try {
    await seedFaqs(prisma);
  } catch (error) {
    console.error("FAQ seed failed:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

if (require.main === module) {
  main();
}
